/**
 * Public read-only view of a JobFolder via a share token.
 *
 * No authentication. The token model carries the auth — possession of
 * the URL grants access. Expired tokens return a 410-style page;
 * revoked tokens (deleted rows) return a 404.
 *
 * Rendered surfaces: the folder's JD, the linked resume (rendered
 * from its structured content), the cover letter, the interview prep,
 * and the notes. The role-play simulation is intentionally NOT
 * surfaced — it's an interactive experience tied to the owner's
 * account, not a document a mentor needs to review.
 */
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import type { ResumeContent, ResumeSection, ResumeItem } from "@/lib/resume/types";

export const dynamic = "force-dynamic";

const SECTION_KIND_HEADINGS: Record<string, string> = {
  experience: "Experience",
  education: "Education",
  projects: "Projects",
  skills: "Skills",
  certifications: "Certifications",
  publications: "Publications",
  awards: "Awards",
  volunteering: "Volunteering",
  summary: "Summary",
  other: "Other",
};

export const metadata: Metadata = {
  title: "Shared application folder",
  robots: { index: false, follow: false },
};

export default async function SharedFolderPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;

  const shareToken = await prisma.jobFolderShareToken.findUnique({
    where: { token },
    include: {
      folder: {
        include: {
          resume: { select: { id: true, name: true, content: true } },
        },
      },
    },
  });
  if (!shareToken) notFound();

  // Expired tokens — render a soft "expired" state so the mentor
  // knows why they're not seeing content. Better UX than a 404.
  if (shareToken.expiresAt && shareToken.expiresAt.getTime() < Date.now()) {
    return (
      <main className="min-h-screen bg-white text-gray-900 px-6 py-12">
        <div className="max-w-2xl mx-auto text-center">
          <h1 className="text-2xl font-bold">This share link has expired.</h1>
          <p className="mt-2 text-gray-600">
            Ask the person who sent it to generate a fresh link.
          </p>
        </div>
      </main>
    );
  }

  const folder = shareToken.folder;
  const owner = await prisma.user.findUnique({
    where: { id: folder.userId },
    select: { name: true },
  });
  const resumeContent = (folder.resume?.content ?? null) as ResumeContent | null;

  return (
    <main className="min-h-screen bg-white text-gray-900">
      <div className="max-w-3xl mx-auto px-6 py-10 sm:px-10 sm:py-14">
        <header className="mb-8">
          <p className="text-[11px] uppercase tracking-[0.22em] font-bold text-gray-500">
            Shared application folder
          </p>
          <h1 className="mt-1 text-3xl font-bold tracking-tight">{folder.title}</h1>
          <p className="mt-1 text-sm text-gray-600">
            Shared by {owner?.name ?? "a candidate"} · read-only
          </p>
          {shareToken.label && (
            <p className="mt-1 text-[12px] italic text-gray-500">
              Note from sender: {shareToken.label}
            </p>
          )}
        </header>

        <Section title="Job description">
          {folder.jdSnippet.trim() ? (
            <pre className="whitespace-pre-wrap font-sans text-[13.5px] leading-[1.65]">
              {folder.jdSnippet}
            </pre>
          ) : (
            <Empty>No JD captured.</Empty>
          )}
        </Section>

        <Section title="Resume">
          {!folder.resume ? (
            <Empty>No resume linked to this folder.</Empty>
          ) : !resumeContent ? (
            <Empty>Resume content not yet parsed.</Empty>
          ) : (
            <ResumeBlock content={resumeContent} />
          )}
        </Section>

        <Section title="Cover letter">
          {folder.coverLetter.trim() ? (
            <MarkdownBlock text={folder.coverLetter} />
          ) : (
            <Empty>No cover letter drafted yet.</Empty>
          )}
        </Section>

        <Section title="Interview prep">
          {folder.interviewPrep.trim() ? (
            <MarkdownBlock text={folder.interviewPrep} />
          ) : (
            <Empty>No interview prep drafted yet.</Empty>
          )}
        </Section>

        {folder.notes.trim() && (
          <Section title="Notes">
            <MarkdownBlock text={folder.notes} />
          </Section>
        )}

        <footer className="mt-12 pt-6 border-t border-gray-200 text-[11.5px] text-gray-500">
          Generated by the BHN Training Platform. The role-play simulation
          tied to this folder isn&apos;t included in shared views.
        </footer>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-9">
      <h2 className="text-[13px] font-bold uppercase tracking-[0.18em] text-gray-700 mb-3 pb-1 border-b border-gray-200">
        {title}
      </h2>
      <div className="text-[14px] leading-[1.7]">{children}</div>
    </section>
  );
}

function Empty({ children }: { children: React.ReactNode }) {
  return <p className="italic text-gray-400">{children}</p>;
}

function MarkdownBlock({ text }: { text: string }) {
  // Light-touch paragraph rendering — JD-pasted markdown is rarely
  // rich enough to need a real parser, and we want to keep the
  // public share view dependency-free.
  const paragraphs = text.split(/\n{2,}/).map((s) => s.trim()).filter(Boolean);
  return (
    <>
      {paragraphs.map((p, i) => (
        <p key={i} className="mb-3 whitespace-pre-wrap">{p}</p>
      ))}
    </>
  );
}

function ResumeBlock({ content }: { content: ResumeContent }) {
  const header = content.header as Record<string, unknown> | undefined;
  const sections = [...(content.sections ?? [])].sort(
    (a, b) => (a.position ?? 0) - (b.position ?? 0),
  );
  const headerLine = header
    ? [
        header.name && String(header.name),
        header.email && String(header.email),
        header.phone && String(header.phone),
        header.location && String(header.location),
      ].filter(Boolean).join(" · ")
    : "";
  return (
    <>
      {headerLine && (
        <p className="text-[12.5px] text-gray-600 mb-4">{headerLine}</p>
      )}
      {sections.map((section) => (
        <ResumeSectionView key={section.id} section={section} />
      ))}
    </>
  );
}

function ResumeSectionView({ section }: { section: ResumeSection }) {
  const heading =
    (section.title && section.title.trim()) ||
    SECTION_KIND_HEADINGS[section.kind] ||
    "Section";
  const items = [...(section.items ?? [])].sort(
    (a, b) => (a.position ?? 0) - (b.position ?? 0),
  );
  if (items.length === 0) return null;
  return (
    <div className="mb-5">
      <h3 className="text-[13px] font-bold uppercase tracking-[0.14em] text-gray-700 mb-2">
        {heading}
      </h3>
      {items.map((item) => (
        <ResumeItemView key={item.id} item={item} />
      ))}
    </div>
  );
}

function ResumeItemView({ item }: { item: ResumeItem }) {
  const titleLine = [item.title, item.subtitle].filter(Boolean).join(" — ");
  const dateLine = (() => {
    if (item.dateRange) return item.dateRange;
    const start = item.startDate ?? "";
    const end = item.current ? "Present" : (item.endDate ?? "");
    return start || end ? `${start} – ${end}` : "";
  })();
  const meta = [dateLine, item.metric, item.url].filter(Boolean).join("  ·  ");
  const bullets = [...(item.bullets ?? [])].sort(
    (a, b) => (a.position ?? 0) - (b.position ?? 0),
  );
  return (
    <div className="mb-3">
      {titleLine && <p className="font-semibold">{titleLine}</p>}
      {meta && <p className="text-[12px] text-gray-600">{meta}</p>}
      {item.description && <p className="mt-1 text-[13.5px]">{item.description}</p>}
      {bullets.length > 0 && (
        <ul className="mt-1 ml-5 list-disc space-y-1 text-[13.5px]">
          {bullets.map((b) => <li key={b.id}>{b.body}</li>)}
        </ul>
      )}
    </div>
  );
}
