/**
 * Onboarding tour content. Steps are filtered per role and per page; each
 * has a stable id stored on the user so progress survives across tours.
 *
 * When the changelog ships a noteworthy feature, append a step with the
 * same `since` version as the changelog entry. Returning users will get
 * a "What's new" mini-tour for steps with `since > user.lastSeenVersion`.
 */
export type StepRole = "trainee" | "evaluating" | "employer" | "instructor" | "admin" | "superadmin";

export interface TourStep {
  id: string;
  title: string;
  body: string;
  /** When user is on this path the step is shown next to the selector;
   *  otherwise we offer a button to navigate there. Skip the step if path
   *  is omitted and we have no selector — purely centered modal. */
  path?: string;
  /** CSS selector to anchor the tooltip to. */
  selector?: string;
  /** Tooltip placement relative to the anchor. */
  placement?: "top" | "right" | "bottom" | "left" | "center";
  /** Roles allowed to see this step. Default: all roles. */
  roles?: StepRole[];
  /** Optional CTA shown on the step (label + href). */
  cta?: { label: string; href: string };
  /** Version this step appeared in. Bump when adding new ones. */
  since: string;
}

/** Bump this whenever a new step is added below — used to re-trigger
 *  the tour for returning users with a friendlier "what's new" hint. */
export const TOUR_VERSION = "2026.05.19f";

export const TOUR_STEPS: TourStep[] = [
  // ─── Welcome ─────────────────────────────────────────────────────
  {
    id: "welcome",
    title: "Welcome to BHN Training",
    body: "Quick 90-second tour of what's on offer. You can pause anytime — we'll save your spot. Press Esc to minimize.",
    placement: "center",
    since: "2025.04",
  },
  // ─── New feature flag — Role-play Simulator ─────────────────────
  {
    id: "trainee.simulator",
    title: "New: Role-play any job",
    body: "Paste a job-posting URL and live through a 12-week quarter as that person — 1:1s, escalations, hiring, the QBR. Every choice moves five stats. At the end you get a performance review from your VP. Cached across trainees, so the same posting only generates once.",
    placement: "center",
    roles: ["trainee", "evaluating", "admin", "superadmin"],
    cta: { label: "Try the simulator", href: "/simulator" },
    since: "2026.05.19e",
  },

  // ─── Trainee path ────────────────────────────────────────────────
  {
    id: "trainee.first-login-cell-split",
    title: "First login? You split a cell.",
    body: "Brand-new trainees land on `/welcome/split-a-cell` on their very first dashboard visit — a 9-stage gamified passaging walkthrough (aspirate media → PBS rinse → trypsin → 3-min incubate → neutralize → re-seed) that mirrors the MSC culture cycle on the login screen. Plays once and the flag flips; from then on you go straight to the dashboard. Admins can replay any time via `/welcome/split-a-cell?replay=1` — the replay path never writes the flag.",
    placement: "center",
    roles: ["trainee", "evaluating", "admin", "superadmin"],
    since: "2026.05.18q",
    cta: { label: "Replay the ritual (admin)", href: "/welcome/split-a-cell?replay=1" },
  },
  {
    id: "trainee.dashboard",
    title: "Your home base",
    body: "The dashboard shows what's in progress, your credit balance, and quick links into the catalog and pathways.",
    path: "/dashboard",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2025.04",
  },
  {
    id: "trainee.catalog",
    title: "Find courses by meaning",
    body: "Type natural language — 'cleanroom gowning' or 'prep for fill-finish role' — and the catalog ranks results by what they actually cover.",
    path: "/courses",
    selector: "input[placeholder*='Search courses']",
    placement: "bottom",
    cta: { label: "Open the catalog", href: "/courses" },
    since: "2025.05",
  },
  {
    id: "trainee.pathways",
    title: "Training pathways",
    body: "Pathways group several courses into one learning journey with a single certificate at the end. Some are open to everyone, others require admin approval.",
    path: "/pathways",
    placement: "center",
    cta: { label: "Browse pathways", href: "/pathways" },
    roles: ["trainee", "evaluating"],
    since: "2025.04",
  },
  {
    id: "trainee.credits",
    title: "Your BHN credits",
    body: "You start with 200 credits. Apply for an additional 4,800 by submitting a quick form — an admin reviews each application personally.",
    path: "/credits",
    placement: "center",
    cta: { label: "View credits", href: "/credits" },
    roles: ["trainee", "evaluating"],
    since: "2025.04",
  },
  {
    id: "trainee.equip",
    title: "Equip — funding for your innovation",
    body: "The third BHN pillar after Engage (training) and Experience (placements). Apply for VentureConnect (≤$5K, conferences + pitch events) or VentureLift (≤$25K, two-stage: pre-screen → full application). 3-question wizard picks your stream; everything pre-fills from your profile; auto-saves as you type.",
    path: "/equip",
    placement: "center",
    cta: { label: "Open Equip", href: "/equip" },
    roles: ["trainee", "evaluating"],
    since: "2026.05.15h",
  },
  {
    id: "trainee.equip.stageTwo",
    title: "VentureLift Stage 2 unlocked",
    body: "If your pre-screening was approved, the my-applications row turns green and a 'Stage 2 unlocked' CTA appears. Click in to fill the full long-form application — project team, market, plan, budget builder, three appendix trays, three-signer block. Auto-saves every 800 ms; close the tab anytime.",
    path: "/equip/my-applications",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.16d",
  },
  {
    id: "trainee.rewards",
    title: "Earn the gear — BHN merch rewards",
    body: "Train 2,500 credits and the BHN Swag Bag (notepad + stress ball + a rotating mystery item) unlocks. Hit 5,000 and the BHN insulated stainless bottle unlocks too. Default pickup is at the BHN office at Leslie Dan Faculty of Pharmacy, U of T — far from Toronto? The claim form has a 'mail it to me' option (admin confirms postage first).",
    path: "/rewards",
    placement: "center",
    cta: { label: "Open Rewards", href: "/rewards" },
    roles: ["trainee", "evaluating"],
    since: "2026.05.09d",
  },
  {
    id: "trainee.themes",
    title: "Vote on themes — and pitch your own",
    body: "Mark a favourite theme, flag a least-favourite, and submit ideas for new ones. An admin reviews every proposal. If we build your idea, you earn a Theme Designer Bundle — a hand-picked thank-you with a custom \"I designed this theme\" pin, picked up at the same BHN office as the other rewards.",
    path: "/themes",
    placement: "center",
    cta: { label: "Open Theme feedback", href: "/themes" },
    since: "2026.05.10a",
  },
  {
    id: "trainee.buddy",
    title: "Find a learning buddy",
    body: "Pair up with someone for accountability — pick a course or pathway to share, see each other's progress, and leave async notes.",
    path: "/buddy",
    placement: "center",
    cta: { label: "Open buddies", href: "/buddy" },
    since: "2025.05",
  },
  {
    id: "trainee.profile",
    title: "Your profile",
    body: "Update your name, password, or request a role change from your profile. Click your name in the bottom-left of the sidebar anytime.",
    path: "/profile",
    placement: "center",
    cta: { label: "Open profile", href: "/profile" },
    since: "2025.04",
  },

  // ─── Instructor path ─────────────────────────────────────────────
  {
    id: "instructor.catalog",
    title: "Author courses",
    body: "As an instructor you can create courses, upload SCORM packages, edit course info, and add modules and assessments — right from the catalog.",
    path: "/courses",
    placement: "center",
    cta: { label: "Open catalog", href: "/courses" },
    roles: ["instructor"],
    since: "2025.04",
  },
  {
    id: "instructor.summary",
    title: "AI summaries help learners",
    body: "On every course detail page, click 'Generate summary' to create a learner-facing 3-paragraph summary grounded in the course's modules and assessments.",
    placement: "center",
    roles: ["instructor", "admin", "superadmin"],
    since: "2025.05",
  },

  // ─── Admin path ──────────────────────────────────────────────────
  {
    id: "admin.overview",
    title: "Admin dashboard",
    body: "Top-level operational view: users, enrollments, pathways, certificates. Most management lives in the Administration section in the sidebar.",
    path: "/admin",
    placement: "center",
    cta: { label: "Open admin", href: "/admin" },
    roles: ["admin", "superadmin"],
    since: "2025.04",
  },
  {
    id: "admin.users",
    title: "Bulk user actions",
    body: "Tick multiple rows on the Users page and a sticky action bar appears for batch activate, role change, credit adjust, or group assignment.",
    path: "/admin/users",
    placement: "center",
    cta: { label: "Open users", href: "/admin/users" },
    roles: ["admin", "superadmin"],
    since: "2025.04",
  },
  {
    id: "admin.creditApps",
    title: "Credit applications",
    body: "Trainees apply for additional credits — review each request with their documents and approve or reject from a single page.",
    path: "/admin/credit-applications",
    placement: "center",
    cta: { label: "Open queue", href: "/admin/credit-applications" },
    roles: ["admin", "superadmin"],
    since: "2025.05",
  },
  {
    id: "admin.pathwayEnrolls",
    title: "Pathway enrollment workflow",
    body: "Approve or reject pathway requests, manage waitlists, set capacity and close dates. New 'Pathway enrollments' tab in the sidebar.",
    path: "/admin/pathway-enrollments",
    placement: "center",
    cta: { label: "Open enrollments", href: "/admin/pathway-enrollments" },
    roles: ["admin", "superadmin"],
    since: "2025.05",
  },
  {
    id: "admin.analytics",
    title: "Analytics dashboard",
    body: "User growth, daily activity, the conversion funnel from sign-up to course completion, top events, role and theme distribution. Switch to All-time and export a one-page PDF report.",
    path: "/admin/analytics",
    placement: "center",
    cta: { label: "Open analytics", href: "/admin/analytics" },
    roles: ["admin", "superadmin"],
    since: "2025.05",
  },
  {
    id: "admin.committees",
    title: "Committees — Equip Review + HQP",
    body: "Manage two committee rosters from one page. Equip Review members get access to the /admin/equip funding queue without holding an admin role — useful for invited external reviewers. HQP members get a sidebar shortcut + welcome-screen badge. Add by email, optional one-line note, soft-revoke (audit trail survives). Adding a third committee is a code change in lib/committees/registry.ts, not a schema migration.",
    path: "/admin/committees",
    placement: "center",
    cta: { label: "Open committees", href: "/admin/committees" },
    roles: ["admin", "superadmin"],
    since: "2026.05.16a",
  },
  {
    id: "committee.badge",
    title: "You're on a committee",
    body: "If you've been added to Equip Review or HQP, look at the very top of your /dashboard for the committee badge. The new COMMITTEES section in your sidebar also surfaces shortcuts to your committee's primary page. Both auto-hide when you're not on any committee.",
    path: "/dashboard",
    placement: "center",
    since: "2026.05.16b",
  },
  {
    id: "admin.equipDeadlines",
    title: "Equip deadlines — list + calendar",
    body: "Schedule new funding windows, extend in-flight deadlines, close cycles early, reopen prematurely-closed ones. Default time is 12:00 PM Eastern on the selected date; adjust if you need an off-hours cut-off. Equip Review committee members can run this without an admin role. Applicants see a Next-deadlines card at the top of /equip.",
    path: "/admin/equip/deadlines",
    placement: "center",
    cta: { label: "Open deadlines", href: "/admin/equip/deadlines" },
    roles: ["admin", "superadmin"],
    since: "2026.05.16c",
  },
  {
    id: "admin.equipOverview",
    title: "Equip program overview",
    body: "Aggregate health of the Equip pillar at a glance. Stat tiles for apps in flight + approved this quarter + $ approved YTD + open windows. Three alert cards for stalled apps + closing deadlines. Per-stream funnels for VC + VL. Routes-scoped to render in the Studio design system.",
    path: "/admin/equip/overview",
    placement: "center",
    cta: { label: "Open overview", href: "/admin/equip/overview" },
    roles: ["admin", "superadmin"],
    since: "2026.05.16e",
  },

  // ─── Superadmin only ─────────────────────────────────────────────
  {
    id: "superadmin.actAs",
    title: "View as another role",
    body: "Above the theme picker in the sidebar, switch to Trainee / Instructor / Admin to see the platform exactly as they do — admin permissions are paused while in this mode.",
    placement: "center",
    roles: ["superadmin"],
    since: "2025.05",
  },

  // ─── Universal closers ───────────────────────────────────────────
  {
    id: "themes",
    title: "Pick your theme",
    body: "Seven curated themes, light and dark. Find the picker at the bottom of the sidebar — your choice persists across sessions.",
    placement: "center",
    since: "2025.05",
  },
  {
    id: "changelog",
    title: "What's new",
    body: "Every release lands in the change log on the sidebar — trainees see 'What's new', staff see the full Change log with per-entry visibility.",
    placement: "center",
    since: "2025.05",
  },
  {
    id: "event-forms",
    title: "Event registrations live on Pathways",
    body: "Programmes and bootcamps that need a sign-up form now appear as teal cards on the Pathways page. Click one to fill it out — your last response is kept on file. Admins can edit fields in place and export every submission as a CSV.",
    path: "/pathways",
    placement: "center",
    since: "2026.05",
    cta: { label: "Open Pathways", href: "/pathways" },
  },
  {
    id: "bold-hero",
    title: "A bolder welcome",
    body: "The dashboard, pathways, and catalog now open with a full-bleed hero — mesh gradient, drifting organic blobs, your name in gradient type, and stat tiles with asymmetric corners. Less of a default form, more of a place that recognises you.",
    path: "/dashboard",
    placement: "center",
    since: "2026.05.07b",
  },
  {
    id: "cinematic-redesign",
    title: "Cinematic, rebuilt to match HR Overview",
    body: "The Cinematic design system now wraps the page header in one rounded panel — deep editorial cover banner up top, identity row overlapping it with a tinted body, eyebrow + giant gradient title + description sitting on the same canvas. Same vocabulary as the HR overview at /employer. Pages that opt into the cinematic DS now read as one cohesive brand stage instead of a cover plus a separate description card.",
    path: "/admin/design-system",
    selector: "[data-design-system-showroom]",
    placement: "center",
    since: "2026.05.17a",
    roles: ["admin", "superadmin"],
    cta: { label: "See the showroom", href: "/admin/design-system" },
  },
  {
    id: "auto-thumbnails",
    title: "Course catalog now has AI cover art",
    body: "We've filled in the catalog with one-word AI thumbnails. Each card's cover image is generated from the strongest word in the course title (or its category if set), rendered as a clean editorial illustration. If a course is missing one, run scripts/auto-thumbnail-courses.ts.",
    path: "/courses",
    placement: "center",
    since: "2026.05.07a",
    roles: ["instructor", "admin", "superadmin"],
    cta: { label: "Open the catalog", href: "/courses" },
  },
  {
    id: "employer-invites",
    title: "Invite employer HR partners by link",
    body: "Administration → Employer invites is where you onboard partner companies. Drop in an email, copy the generated link, and send it through your usual channel — when they click through they're guided to set a name + password and land on /employer with the Employer HR role assigned automatically.",
    path: "/admin/employer-invites",
    placement: "center",
    since: "2026.05.07j",
    roles: ["admin", "superadmin"],
  },
  {
    id: "catalog-admin",
    title: "Catalog admin tools",
    body: "Hover any course card on the catalog — admins now see a pencil for quick-edit and a checkbox for bulk-select. Pick a few cards, then use the floating Apply filters button at the bottom to assign topic / delivery / provider in one go. The picker options themselves live at Administration → Course filters.",
    path: "/courses",
    placement: "center",
    since: "2026.05.07i",
    roles: ["admin", "superadmin"],
  },
  {
    id: "catalog-filters",
    title: "Filter the catalog",
    body: "The course catalog now has a filter rail on the left — pick topics, delivery types, providers, or filter to special instructor-led programs. Selections live in the URL so you can share or bookmark a filtered view.",
    path: "/courses",
    placement: "center",
    since: "2026.05.07h",
    cta: { label: "Open the catalog", href: "/courses" },
  },
  {
    id: "catalog-filters-compact",
    title: "Catalog filter strip is now compact + dark",
    body: "We rebuilt the catalog filter as a tight dark control strip — same chips, less real estate. The 'Special programs & workshops (instructor-led)' toggle is now featured in the header as a glowing amber pill, since that's the one most people are reaching for.",
    path: "/courses",
    placement: "center",
    since: "2026.05.15a",
    cta: { label: "Open the catalog", href: "/courses" },
  },
  {
    id: "course-thumbnails-overlay",
    title: "Batch-tone course thumbnails",
    body: "Open /admin/course-thumbnails — there's a new Colour / gradient overlay panel above the rows. Tick the courses you want, dial in colour + angle + opacity + blend mode, and stamp the treatment onto all of them in one click. Non-destructive: the underlying SDXL art is untouched and you can clear the overlay any time.",
    path: "/admin/course-thumbnails",
    placement: "center",
    since: "2026.05.15b",
    roles: ["admin", "superadmin"],
    cta: { label: "Open thumbnails admin", href: "/admin/cover-art" },
  },
  {
    id: "cover-art-admin",
    title: "Cover art admin now includes pathways",
    body: "The cover-art tool (previously /admin/course-thumbnails, now /admin/cover-art) manages AI thumbnails and colour overlays for courses AND pathways in one list. Each row shows its kind (course / pathway) and routes regenerate calls to the right pipeline. Overlay batching splits mixed selections across both tables under the hood.",
    path: "/admin/cover-art",
    placement: "center",
    since: "2026.05.15f",
    roles: ["admin", "superadmin"],
    cta: { label: "Open cover art admin", href: "/admin/cover-art" },
  },
  {
    id: "employer-profile-hero",
    title: "Your company profile, now with presence",
    body: "/employer/profile opens with a cinematic hero showing your logo, name, identity chips, and a live stat strip of postings, applicants, and interviews — this is the face trainees see on every internship you post. Edit form sits below; the hero refreshes the moment you save.",
    path: "/employer/profile",
    placement: "center",
    since: "2026.05.15c",
    roles: ["employer", "admin", "superadmin"],
    cta: { label: "Open my profile", href: "/employer/profile" },
  },
  {
    id: "employer-profile-flagship",
    title: "Profile is now your hiring brand page",
    body: "/employer/profile is now a flagship layout — full-bleed cover banner, overlapping identity card with a 160px logo, three oversized stats, an About pull-quote, and a preview of your live postings as trainees would see them. The edit form is collapsed by default once your profile is in good shape so the polished surfaces carry the page.",
    path: "/employer/profile",
    placement: "center",
    since: "2026.05.15d",
    roles: ["employer", "admin", "superadmin"],
    cta: { label: "Open my profile", href: "/employer" },
  },
  {
    id: "employer-home-brand-stage",
    title: "Employer home is now your brand stage",
    body: "The /employer overview opens with the cinematic profile layout — cover banner, identity card, stats, action queue, hiring shopfront. Click the pencil top-right to open the edit modal, which leads with the URL auto-fill: paste your site and the AI pulls industry, HQ, size, founding year, logo, and description in one round trip.",
    path: "/employer",
    placement: "center",
    since: "2026.05.15g",
    roles: ["employer", "admin", "superadmin"],
    cta: { label: "Open my employer home", href: "/employer" },
  },
  {
    id: "internship-board",
    title: "Internship Opportunities is live",
    body: "EXPERIENCE → Internship Opportunities lists open postings from BioHubNet's industry partners. Browse, then apply through the company's own site. Admins post by pasting a job description — the AI parses it into structured fields.",
    path: "/internships",
    placement: "center",
    since: "2026.05.07g",
    cta: { label: "Open the board", href: "/internships" },
  },
  {
    id: "experience-track",
    title: "Experience track is open",
    body: "Looking for an internship or full-time placement? Open EXPERIENCE → Talent Application in the sidebar. It collects your bio, supervisor letter, transcript, resume, and a one-minute STAR video introduction. We share your application with vetted industry partners.",
    path: "/forms/talent-application",
    placement: "center",
    since: "2026.05.07f",
    cta: { label: "Open the application", href: "/forms/talent-application" },
  },
  {
    id: "refined-palette",
    title: "A quieter, more refined palette",
    body: "Daylight, Nightfall, and Scientific now read more editorial than tech-startup — desaturated slate-navy brand, warm putty / charcoal backgrounds, warm graphite text. Less saturation, more sophistication. Hi-Tech keeps its neon edges as the maximalist option.",
    placement: "center",
    since: "2026.05.07d",
  },
  {
    id: "trimmed-themes",
    title: "Three core themes, all distinct",
    body: "Open the Theme picker — Daylight, Nightfall, and Hi-Tech (JetBrains Mono on near-black with neon edges). Each one ships its own typography, surface treatment, and corner radii — switching themes changes the whole design language, not just colour.",
    selector: "[aria-label=\"Change theme\"]",
    placement: "right",
    since: "2026.05.07c",
  },
  {
    id: "ai-greeting",
    title: "A fresh greeting for every visit",
    body: "Below 'Hi, {your name}.' on your dashboard, a small AI-written tagline now appears — tailored to the time of day and your role. Hover the line and you'll see chips to thumbs-up, thumbs-down, regenerate, or turn the feature off entirely if it ever feels too much.",
    placement: "center",
    since: "2026.05.07k",
  },
  {
    id: "rosalind-theme",
    title: "Meet Rosalind",
    body: "New theme inspired by Rosalind Franklin and herbarium-style notebooks: warm parchment background, sage-green CTAs, dusty-rose accent, italic serif headings. Open the Theme picker to try it.",
    selector: "[aria-label=\"Change theme\"]",
    placement: "right",
    since: "2026.05.07k",
  },
  {
    id: "greenwood-immersive",
    title: "Greenwood is now a forest you can walk into",
    body: "Switch to Greenwood (Flavours → Greenwood) and the platform turns into a forest scene that shifts with your local hour — mist at dawn, dappled sunlight at noon, golden dusk, fireflies after dark. Leaves drift across the page all day, and a small caption at the bottom-right reports what the forest is doing right now (\"a cardinal calls from the cedar\", \"fireflies hover near the brook\"). Reduced-motion users get the time-of-day tint without the animation.",
    selector: "[aria-label=\"Change theme\"]",
    placement: "right",
    since: "2026.05.17a",
  },
  {
    id: "atompunk-theme",
    title: "Atom Punk — 1950s atomic age",
    body: "New flavour in the theme picker: Atom Punk. Aged paper cream + atomic teal + tangerine sunset + canary pop. Slab-serif headlines on a geometric sans body, 2-4 px corner radii (atomic-age geometry, not playful), sunset-over-the-test-site hero gradient. Reads like a vintage Tomorrowland brochure or a Vault-Tec pamphlet. Open the theme picker to try it.",
    selector: "[aria-label=\"Change theme\"]",
    placement: "right",
    since: "2026.05.17b",
  },
  {
    id: "cinematic-hero-single-stage",
    title: "Page heroes are now one continuous editorial stage",
    body: "The cinematic page hero is now a single full-bleed gradient stage instead of a cover-banner + paper-body two-tier composition. The title block sits at the bottom of the stage (magazine-cover composition); the auroras + noise + bottom scrim live in the visual real estate above. Theme-driven palette throughout, with per-theme title-shimmer overrides so contrast stays correct on every theme — including Icecream's light pink hero, which swaps the title to a deep berry ramp.",
    placement: "center",
    since: "2026.05.17g",
  },
  {
    id: "login-half-sketch-and-aquarium",
    title: "Sign out and check the new /login — it's a biotech aquarium now",
    body: "The login page got a full rebuild. The BHN four-petal mark sits at the bottom-right corner as a 480-pixel design study — LEFT half is pencil sketch on construction grid (multi-stroke wobbly outlines, dashed symmetry circles, axis labels), RIGHT half is the finished gradient mark, joined by an organic wavy boundary with the colour brushed-on across the seam. Behind the form, biotech glyphs (DNA, antibody, mRNA, LNP, cell, bioreactor, T-flask) drift on lab-swim animations — and they're now mouse-interactive: click-and-drag to pull them anywhere, or just brush your cursor past to poke them sideways. A six-stage MSC passaging cycle vignette (seed → grow → 80% confluent → trypsin → aspirate → re-seed) loops in the top-right corner. Five O₂ + CO₂ molecules float around as the incubator atmosphere. Sign out and have a play.",
    placement: "center",
    cta: { label: "Open /login in a new tab", href: "/login" },
    since: "2026.05.18a",
  },
  {
    id: "login-rotation-and-ribosome",
    title: "Login backdrop tuned — gentler poke, slow rotation, plus a ribosome",
    body: "Three refinements on the live /login atmosphere. (1) The cursor-poke now uses velocity-based physics instead of a direct push — force eases quadratically to zero at the radius edge so glyphs glide away rather than jump. Poke radius widened to 150 px so the drift starts before the cursor reaches the glyph. (2) Every glyph now slowly rotates around a per-instance random centre of weight (60–140 s per full turn, random 25–75 % transform-origin on both axes, 50/50 clockwise/counter-clockwise) — some twist in place, some trace a wider orbital arc, none of them spin in unison. (3) New ribosome glyph translating an mRNA strand in the middle band of the backdrop, with the large + small subunits, 5′/3′ ends labelled, a growing peptide chain emerging from the exit tunnel, and a synchronized pulse on the active-site codon + newest amino acid so it reads as mid-synthesis.",
    placement: "center",
    cta: { label: "Open /login in a new tab", href: "/login" },
    since: "2026.05.18b",
  },
  {
    id: "login-periphery-and-unified-ctas",
    title: "Login page — periphery-only glyphs + matching brand-gradient CTAs",
    body: "Three more refinements. (1) Every floating glyph now lives in a strict LEFT / RIGHT edge band (within ~6 % of the viewport edge). Combined with the rotation orbit + swim translate + the cursor-poke physics that pushes glyphs AWAY from the cursor (which lives in the centre over the form), they can no longer wander into the middle. (2) Trimmed three pieces of chrome: the `// p < 0.05, results pending` mono footnote, the `Spec. / Sign in / Join` horizontal section divider, and all five small O₂ / CO₂ atoms. (3) Both CTAs in the access-pair spread now wear the SAME brand-gradient treatment with the inner shine sweep — the Sign-in button used to be flat white-on-slate, now it matches the Sign-up gradient exactly. Differentiation through copy and column context, not treatment.",
    placement: "center",
    cta: { label: "Open /login in a new tab", href: "/login" },
    since: "2026.05.18c",
  },
  {
    id: "dash-equip-deadlines-loot-vault-sakura",
    title: "Dashboard — real EQUIP deadlines, playful Loot Vault, Sakura promo in the picker",
    body: "Three updates to the trainee dashboard. (1) EQUIP pillar column now LISTS the next VC + VL funding windows (with extended pips) instead of a bare \"X windows open\" count — a planning surface, not just a pulse. (2) The Loot Vault at the bottom is back to its full playful style — rainbow gradient panel, floating gift/sparkle glyphs, big mono credits scoreboard with a frosted 3-stat row, glowing milestone bar with circular tier markers. Whole panel links into /rewards. (3) The Sakura promo card that used to sit on the dashboard has moved into the theme picker: open the palette (bottom-left of the sidebar) and a featured \"Try Sakura · X d left\" card sits at the very top of the dropdown for any active limited-time theme. Discovery is now beside the action.",
    placement: "center",
    since: "2026.05.18d",
  },
  {
    id: "full-site-audit-sweep",
    title: "Site-wide accessibility, nav, and polish sweep",
    body: "Big audit-driven sweep. Login form now has visible focus rings on every field + the Sign-up Link + the Sign-in submit. ThemePicker / ThemeCycler buttons grew to 44 × 44 px touch targets. Subtle-text colour on Sakura, Icecream, and Greenwood themes deepened so hints clear the 4.5:1 contrast threshold. MscCultureCycle (the MSC passaging vignette on /login) now respects prefers-reduced-motion. /compliance moved to /admin/compliance — old URL redirects. Access requests added to the admin sidebar (previously orphaned). EQUIP pillar capped at 3 deadlines + a 'more' link. Loot Vault gradient + band wash both retuned to a refined 3-stop indigo→violet→magenta ramp. StylizedMark backdrop now visible on smaller screens. ThemePicker dropdown gained menu / radio-group semantics + a softer (non-rose) Featured promo card. Login petal backdrop's 'culturing' gradient text now declares a contrast-checkable solid fallback.",
    placement: "center",
    since: "2026.05.18e",
  },
  {
    id: "dash-deadline-driven-board",
    title: "Dashboard rebuilt around 'WE ARE DEADLINE-DRIVEN'",
    body: "Trainee dashboard now leads with a four-column DEADLINE-DRIVEN board mirroring the biohubnet.ca card. Each column lists deadline-driven items pulled from real data — ENGAGE (pathways + admin-curated highlights), EXPERIENCE (active internships + Knowledge Exchange + Mobility Award), EQUIP (VentureLift / VentureConnect with their amount + audience spelled out), EVENTS (upcoming workshops with location + time). VC and VL are no longer acronyms-only — every card spells them out and explains who they're for. A compact three-column 'your training / placement / funding' status strip sits below the board for personal state. Loot Vault is now a single-row strip (about half its previous height). Whole page got tighter — section padding reduced, gaps trimmed.",
    placement: "center",
    since: "2026.05.18f",
  },
  {
    id: "dash-equip-events-consistency",
    title: "Dashboard polish — EQUIP shows one VC + one VL, EVENTS reads the calendar",
    body: "Three refinements on the trainee DEADLINE-DRIVEN board. (1) EQUIP now shows ONE next-open round per stream (one VentureConnect card + one VentureLift card) instead of the next 5 in date order — guarantees both streams appear; closed/passed windows never show. (2) EVENTS now reads from the same `BhnEvent` calendar source the public `/events` page uses, so the dashboard event cards match what trainees see on the calendar. (3) Section padding, eyebrows, and column rhythm normalised across the page so the dashboard reads as one designed surface.",
    placement: "center",
    since: "2026.05.18g",
  },
  {
    id: "dash-open-opportunities-ds-native",
    title: "Open opportunities — section rebuilt native to the design system",
    body: "The four-pillar opportunities board no longer wears the navy banner + rounded panel chrome from the biohubnet.ca mimicry. Rebuilt to match the platform's flat-section + theme-token design system: standard SectionEyebrow header + gradient hairline, italic audience subtitle, hairline-divided columns, theme-aware item titles + descriptions, light status pills (bg-rose-50 / bg-sky-50 / bg-amber-50 with ring outlines) matching the platform's existing status-badge family. The section now sits rhythmically alongside For You / Reminders / Loot Vault — same wash pattern, same chrome — instead of barging in as a marketing-card outlier.",
    placement: "center",
    since: "2026.05.18h",
  },
  {
    id: "dash-team-note",
    title: "A note from the team — under the hero",
    body: "There's a short editorial blurb from the BHN founders sitting just under the trainee hero now — italic serif body addressing you by name, with hopes for each pillar (a course that surprises, a placement that opens a door, a funding round that gets your idea moving, a few people whose company you'd keep beyond the platform). Closes with `We're rooting for you`. Designed flat and native to the DS — same section chrome as the rest of the page, with a four-petal LogoMark + uppercase tracked team attribution at the bottom.",
    placement: "center",
    since: "2026.05.18i",
  },
  {
    id: "dash-hero-editorial",
    title: "Trainee hero — bespoke editorial composition",
    body: "Trainee dashboard's head banner is now an editorial composition — DASHBOARD masthead with mono date + four-petal mark, italic-serif `Welcome back,` line, your first name set HUGE (6xl→8xl italic serif on the theme's hero-title gradient), a short hairline, a state-aware lead sentence, white-pill + ghost-pill CTAs, and a hairline-separated right-column stats stack (In progress / Credits / Certificates) on lg+. Same theme-aware `.hero-mesh-brand` base, with two extra blurred mesh blobs + a faint constellation grid for atmospheric depth.",
    placement: "center",
    since: "2026.05.18j",
  },
  {
    id: "dash-hero-fractal-glass",
    title: "Hero — fractal glass shards floating in the background",
    body: "Three angular glass panels are floating in the trainee hero's background now — translucent rounded shards that catch the underlying mesh through backdrop-blur + saturate (glassmorphism), with an SVG fractal-noise filter inside each at low opacity for a richer 'frosted' texture than a plain blur. Large diagonal pane mid-left (rotated −12°), small accent upper-right near the LogoMark (+8°), medium pane lower-right (−6°). Glass edges + inner highlights mimic real glass catching light. Hidden below md to keep mobile lean.",
    placement: "center",
    since: "2026.05.18k",
  },
  {
    id: "dash-hero-reeded-glass",
    title: "Hero — reeded / fluted glass (real refraction)",
    body: "The hero now reads as one panel of theme-tinted reeded glass — vertical-rib texture across the whole background with the mesh blobs visibly sliced into vertical bands behind it. Built with SVG feTurbulence (horizontal-streaked noise) + feDisplacementMap (real per-vertical-band horizontal offset), so each rib actually refracts what's behind it the way real fluted glass does. Plus a pair of layered repeating-linear-gradients drawing the physical ridge highlights + a fine micro-texture between grooves. Theme-aware via the same --hero-mesh-1..4 tokens, so every theme paints its own palette through the same glass.",
    placement: "center",
    since: "2026.05.18l",
  },
  {
    id: "all-heroes-redesign-login-stage",
    title: "All page heroes — major redesign (no floaters, visible reeded glass)",
    body: "Every cinematic page header on the platform now wears the /login spotlight stage as its backdrop — deep radial dome from the theme's hero-mesh-1, aurora wash + warm spotlight cone (mirroring the /login centre pool), visible reeded-glass vertical ribs at strong contrast (the 'fractal glass' effect the user was after — actual lines you can see, not subtle), a StylizedMark backdrop peeking from the bottom-right corner, edge vignette, and SVG noise grain. NO floating glyphs. The trainee dashboard hero keeps its bespoke editorial layout but its atmospheric layers were refactored to the same recipe so the platform reads as one design language. Also cleaned up /equip/my-applications — stray back-link + hero icon removed.",
    placement: "center",
    since: "2026.05.18m",
  },
  {
    id: "course-card-redesign-2col",
    title: "Course catalog cards — new two-column layout with all the metadata",
    body: "Course cards on /courses have been rebuilt to mirror the legacy BHN course-card design. Each tile now shows: short course code eyebrow (BIOP210 etc.) + bold title + 4-line description + orange Request-to-Enroll / Enroll CTA on the LEFT, and a colour-coded chip stack (credit/free, delivery mode, provider) + Enroll-by date + Duration (cohort window or minutes) on the RIGHT. Admin quick-edit dialog grew a Catalog Card Fields section covering Code / Credit cost / Enroll-by / Cohort start / Cohort end / Requires approval — everything on the card is editable from the pencil that pops on hover.",
    placement: "center",
    cta: { label: "Open /courses", href: "/courses" },
    since: "2026.05.18n",
  },
  {
    id: "course-favorites",
    title: "Course favorites — heart any card to bookmark it",
    body: "The heart icon on the top-right of each catalog card is now interactive — tap to add the course to your favorites, tap again to remove it. Filled rose when favorited, outline when not. A new 'Favorites · {N}' filter chip appears at the top of /courses once you've hearted at least one course; toggling it narrows the catalog to just your favorites. The state is per-user and persists across sessions.",
    placement: "center",
    cta: { label: "Open /courses", href: "/courses" },
    since: "2026.05.18o",
  },
  {
    id: "dash-hero-reeded-hothouse",
    title: "Trainee hero — full redesign, reeded-glass hothouse",
    body: "The dashboard head banner has been completely redesigned. The hero is now a piece of designed art — five stylised palm fronds painted in your theme's mesh colours, atmospherically blurred, then sliced into vertical bands by a real SVG feDisplacementMap filter (the same way a sheet of reeded / fluted glass works as a strip of cylindrical lenses). Vertical rib highlights + a finer micro-texture between grooves give the glass its 3D ridge quality; a frost wash + edge vignette + noise grain finish the editorial print feel. Every colour is a theme-mesh token so the art adapts per theme.",
    placement: "center",
    cta: { label: "Open /dashboard", href: "/dashboard" },
    since: "2026.05.18p",
  },
  {
    id: "aurora-theme",
    title: "Aurora — the original cinematic gradient as a theme",
    body: "New flavour in the theme picker: Aurora. Deep near-black-navy stage with the four signature cinematic auroras (cyan, pink, canary, green) and a royal-purple brand ramp. The exact gradient that was previously hardcoded into every cinematic hero, now available as a switchable theme. Magazine-cover-at-midnight feel.",
    selector: "[aria-label=\"Change theme\"]",
    placement: "right",
    since: "2026.05.17f",
  },
  {
    id: "cinematic-hero-theme-driven",
    title: "Cinematic hero — editorial drama, theme-driven",
    body: "Page heroes across the dashboard now render as a deep editorial cover (theme-flavored gradient + four dreamy blurred auroras + fine SVG noise + horizon hairline) with a paper body popping out from underneath, holding the icon disc, eyebrow, big gradient-text title, and description on the card. The gradient + every aurora colour come from each theme's hero tokens — Light gets cyan/mint/blue auroras on deep teal, Atom Punk gets atomic teal + tangerine + canary on blueprint navy, Sakura gets blossom on wine, Greenwood gets sage + canary on forest. Switch themes (theme picker, bottom-left of the sidebar) and every hero recolours immediately.",
    selector: "[aria-label=\"Change theme\"]",
    placement: "right",
    since: "2026.05.17e",
  },
  {
    id: "system-status-superadmin",
    title: "System status — for superadmins",
    body: "If you're superadmin, Administration → System status now shows DB ping, AI usage, security signals, and a one-click panel to seed or remove the test employer + trainee + posting + submission set.",
    path: "/admin/system-status",
    placement: "center",
    roles: ["superadmin"],
    since: "2026.05.07k",
    cta: { label: "Open System status", href: "/admin/system-status" },
  },
  {
    id: "newsletter-three-state",
    title: "Newsletter opt-in, three options",
    body: "Sign-up form now asks 'Yes, sign me up' (default), 'I'm already subscribed', or 'No thanks' — instead of a single tick-box. Stops accidentally double-adding existing BioHubNet subscribers.",
    placement: "center",
    since: "2026.05.07l",
  },
  {
    id: "newsletter-export-admin",
    title: "Newsletter exports — for admins",
    body: "Administration → Newsletter exports lists every new opt-in waiting to be added to the BioHubNet ESP. Pick a format (one-per-line / CSV / comma), copy to clipboard, paste into Mailchimp, then click 'Mark as exported' so they don't appear next time. The All tab and a per-row 'Re-arm' button cover edge cases.",
    path: "/admin/newsletter",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07l",
    cta: { label: "Open Newsletter exports", href: "/admin/newsletter" },
  },
  {
    id: "skill-profile",
    title: "Your skill profile is live",
    body: "Open EXPERIENCE → My Skills to see what we know about you. Skills come from completed courses, your talent application, or you can self-claim. Employers use this to score you against their roles.",
    path: "/profile/skills",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.07m",
    cta: { label: "View my skills", href: "/profile/skills" },
  },
  {
    id: "skill-gap-widget",
    title: "See how you match against open roles",
    body: "On the dashboard, the new 'How you match' widget lets you pick any active internship and shows your match score, the skills you bring, what you're missing, and which BHN courses would close the gap.",
    path: "/dashboard",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.07m",
  },
  {
    id: "applicant-kanban",
    title: "Applicant kanban with skill scoring",
    body: "Open any of your postings → Applicants. Each applicant gets a 0–100 skill match, a breakdown of which skills they bring vs miss, and links to the BHN courses that taught them. Drag through New / Reviewing / Shortlisted / Phone screen / Onsite / Offer.",
    placement: "center",
    roles: ["employer", "admin", "superadmin"],
    since: "2026.05.07m",
  },
  {
    id: "interview-scheduler",
    title: "One-click interview scheduling",
    body: "From an applicant's drawer, click Schedule interview, propose 1–5 time slots and a format. The applicant accepts from /interviews on their dashboard. No external calendar OAuth — minimal friction.",
    placement: "center",
    roles: ["employer", "admin", "superadmin"],
    since: "2026.05.07m",
  },
  {
    id: "skill-ontology-admin",
    title: "Skill ontology curation — admins",
    body: "/admin/skills lists every Skill, alias, and which courses / postings / users use it. Merge duplicates, add aliases, deprecate stale entries. AI proposes new skills when content flows in; you approve or merge them here.",
    path: "/admin/skills",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07m",
    cta: { label: "Open skill ontology", href: "/admin/skills" },
  },
  {
    id: "public-marketing-pages",
    title: "/for-employers and /for-trainees",
    body: "Public marketing pages live at /for-employers and /for-trainees, pitching the platform without requiring sign-in. Visitors leave their email and an admin approves from /admin/access-requests.",
    placement: "center",
    since: "2026.05.07m",
  },
  {
    id: "per-admin-sandbox",
    title: "Per-admin sandbox accounts",
    body: "Administration → Sandbox accounts. Each admin spawns one Employer HR + one Trainee pair (idempotent, deterministic emails). Test in parallel with other admins without stomping on shared data. Pair includes a starter posting and a talent-application submission so the kanban / scoring / interview flows all light up immediately.",
    path: "/admin/sandboxes",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07n",
    cta: { label: "Open Sandbox accounts", href: "/admin/sandboxes" },
  },
  {
    id: "demo-filler",
    title: "Fill with sample data",
    body: "Long forms (talent application, posting form, employer profile, trainee profile) now have a 'Fill with sample' chip — admin-only. Click and pick from 5 curated presets so consecutive demos don't all look identical.",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07n",
  },
  {
    id: "my-application",
    title: "Build your application once, reuse it everywhere",
    body: "Open EXPERIENCE → My Application (or visit /profile/application). Three slots: a resume (PDF / DOCX), a 1-minute video introduction, and a short elevator pitch. Each saves independently — upload the resume now, write the pitch later. Talent applications and partner introductions pull from these so you don't re-upload the same files for every employer.",
    path: "/profile/application",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.08a",
    cta: { label: "Open My Application", href: "/profile/application" },
  },
  {
    id: "my-application-sample-admin",
    title: "Fill My Application with a sample (including the video)",
    body: "On /profile/application, admins now see a 'Fill with sample' panel at the top. One click generates a multi-section resume PDF, records an ~8 s WebM video introduction from a canvas animation, and sets a sample elevator pitch — all through the real upload pipeline. Useful for screenshot runs and demoing the candidate snapshot without recording yourself.",
    path: "/profile/application",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.08b",
    cta: { label: "Open My Application", href: "/profile/application" },
  },
  {
    id: "talent-app-prefill",
    title: "Talent Application now pre-fills from My Application",
    body: "Open /forms/talent-application — if you've built a resume, video, and pitch on My Application, they're already imported. A blue banner explains where the values came from and how to edit. Empty submission fields no longer clobber non-empty My-Application defaults, so re-opening a half-finished draft is safe.",
    path: "/forms/talent-application",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.08c",
    cta: { label: "Open the application", href: "/forms/talent-application" },
  },
  {
    id: "admin-security-reports",
    title: "Security reports — for admins",
    body: "Administration → Platform → Security now hosts our internal security reviews. The 8-May-2026 report covers our pre-emptive response to the Canvas / Instructure breach (what we found in BHN that matched the same attack class, what we shipped, what's recommended next). Show this to leadership when they ask 'is BHN safe from what's in the news?'.",
    path: "/admin/security",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.08e",
    cta: { label: "Open Security reports", href: "/admin/security" },
  },
  {
    id: "security-mfa",
    title: "Multi-factor authentication is now available",
    body: "Open /profile/security to enable MFA on your account. We support any authenticator app — Google Authenticator, 1Password, Authy. After you enable it, every sign-in asks for a 6-digit code in addition to your password. Highly recommended for admins and anyone with access to learner data. Five failed sign-ins now also lock the account for 30 minutes; password choices are checked against the top 200 leaked-password list.",
    path: "/profile/security",
    placement: "center",
    roles: ["trainee", "evaluating", "instructor", "admin", "superadmin", "employer"],
    since: "2026.05.09c",
    cta: { label: "Open security settings", href: "/profile/security" },
  },
  {
    id: "adaptive-mvp",
    title: "Topic mastery, review bookmarks, video checkpoints",
    body: "Three new primitives have shipped on the learner side. The course detail page now shows a topic-by-topic mastery heatmap based on your assessment attempts. Star any assessment question to save it for review — due bookmarks surface as a 'Today's reviews' card on your dashboard. And video modules with author-placed checkpoints will pause at each one for a quick comprehension check. Cheap MVPs; the deeper Bayesian-knowledge-tracing / SM-2 / auto-chunking versions can come later if these earn their keep.",
    path: "/dashboard",
    placement: "center",
    roles: ["trainee", "evaluating", "instructor", "admin", "superadmin"],
    since: "2026.05.09b",
    cta: { label: "Open dashboard", href: "/dashboard" },
  },
  {
    id: "internship-finder-flow",
    title: "Internships: apply, match, save, track",
    body: "The internship finder grew up. Open EXPERIENCE → Internship Opportunities to browse, then click any posting: you'll see a match score against your skills, the contact email, and a 'Send my application' button that opens your mail client with your pitch + resume URL pre-filled. The same click marks the posting as applied so it appears under EXPERIENCE → My Applications with the employer's current stage. Save a heart on any posting to come back later — saved postings with deadlines in the next 7 days surface on your dashboard.",
    path: "/internships",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.08h",
    cta: { label: "Browse internships", href: "/internships" },
  },
  {
    id: "daily-fresh-theme",
    title: "A fresh theme each day — try without committing",
    body: "Look for a small card at the top of your dashboard suggesting a new theme. 'Try it' applies the theme for this session only — no commitment. Once you're trying, the card lets you 'Keep it' (save to your profile) or 'Maybe later' (revert). The rotation skips your current theme so it's always something new. Right now Sakura — a limited-time cherry-blossom theme — is featured as the daily pick until 31 May.",
    path: "/dashboard",
    placement: "center",
    roles: ["trainee", "evaluating", "instructor", "admin", "superadmin", "employer"],
    since: "2026.05.08g",
    cta: { label: "Open dashboard", href: "/dashboard" },
  },
  {
    id: "security-program-rollout",
    title: "Security program: ready to flip on when you are",
    body: "All five recommendations from the leadership report have been developed. Three are live (CodeQL + Dependabot + secret scanning, pentest playbook, public /security page + security.txt). Two more are wired in but env-gated: signed-URL R2 access (R2_USE_SIGNED_URLS) and registration hardening with Cloudflare Turnstile + email verification (NEXT_PUBLIC_TURNSTILE_SITE_KEY, BHN_REQUIRE_EMAIL_VERIFY, SMTP_*). Flip the env vars in Vercel when ops is ready.",
    path: "/admin/security",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.08f",
    cta: { label: "Open Security reports", href: "/admin/security" },
  },
  {
    id: "demo-workspaces",
    title: "Demo workspaces for prospective employers",
    body: "Administration → Demo workspaces lets you mint a one-shot link for a partner. They click, enter their name, and land in a populated workspace — 3 sample postings, 10 applicants spread across the funnel, scheduled interviews. Time-limited (default 7 days); the sweeper auto-deletes when the timer runs out.",
    path: "/admin/demo-workspaces",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07n",
    cta: { label: "Open Demo workspaces", href: "/admin/demo-workspaces" },
  },
  {
    id: "talent-pool-comments",
    title: "Comment on talent applications (admin + employer)",
    body: "The new shared /talent-pool surface lets admins and employers browse approved talent-application submissions and leave private comments on each. Comments stay invisible to the applicant. Commenting is locked until an admin has reviewed + approved the applicant's eligibility — the lock keeps the review gate enforceable across reviewers. Find it under Engage → Experience → Talent pool (admin) or Employer portal → Talent pool.",
    path: "/talent-pool",
    placement: "center",
    roles: ["admin", "superadmin", "employer", "instructor"],
    since: "2026.05.12e",
    cta: { label: "Open talent pool", href: "/talent-pool" },
  },
  {
    id: "leave-pool-and-exit-survey",
    title: "You can now leave the talent pool (with an optional exit survey)",
    body: "On /forms/talent-application, scroll to 'Leave the talent pool'. Pick a reason and either submit the exit survey now or skip and come back later via a one-shot link we'll generate for you. Found a job? Changed direction? Let us know — your feedback shapes the experience for the next cohort.",
    path: "/forms/talent-application",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.12e",
  },
  {
    id: "admin-feedback-dashboard",
    title: "Aggregated trainee feedback — /admin/feedback",
    body: "New dashboard under Admin · Platform: total responses, NPS, ratings per dimension, exit-reason breakdown, and individual responses with the full text answers + follow-up opt-in state. Mint single-use feedback-invitation links from the same page — useful for following up with someone who left without filling the inline survey, or running an out-of-band NPS check.",
    path: "/admin/feedback",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.12e",
    cta: { label: "Open feedback dashboard", href: "/admin/feedback" },
  },
  {
    id: "pathway-cohorts",
    title: "Pathways now run in cohorts",
    body: "Pathways can be split into cohorts (Spring 2026, Fall 2026, …), each with its own capacity, dates, and waitlist policy. On any pathway with cohorts, you'll see a card per cohort with a live state badge — Open / Waitlist only / Full / Closed / Opens soon. Pick the cohort that fits your schedule. Admins manage cohorts inline on the pathway detail page; pathways without cohorts continue to behave as before.",
    path: "/pathways",
    placement: "center",
    since: "2026.05.12d",
    cta: { label: "Open pathways", href: "/pathways" },
  },
  {
    id: "talent-review-gate",
    title: "Talent applications now go through admin review",
    body: "New talent-application submissions are pending until an admin approves them, then become visible in the talent pool / partner-visible directory. You'll see your own review state on /forms/talent-application and a notification when a decision is made. Admins have a Skip-approval fast-path for obvious-fit candidates — audit-logged separately.",
    path: "/forms/talent-application",
    placement: "center",
    since: "2026.05.12d",
  },
  {
    id: "experience-program-guide",
    title: "New: program guide at /experience",
    body: "End-to-end explainer for the EXPERIENCE program — Application Builder → Talent Application → Internship Opportunities → Application Tracker → Interviews. Includes a flow chart with one branching node (admin review). Every mention of a sidebar item is a clickable pill — hover it, and the matching row in your sidebar pulses so you can find the control instantly. Find it at the top of the EXPERIENCE section in the sidebar.",
    placement: "center",
    since: "2026.05.13a",
    cta: { label: "Open the program guide", href: "/experience" },
  },
  {
    id: "editable-copy",
    title: "New: edit page text inline",
    body: "Admins can now rewrite page headlines, subtitles, and hero copy without a deploy. Hover any text on /courses, /events, /rewards, or /pathways and a small pencil appears — click it to open a modal editor. Or open Administration → Platform → Editable copy for every editable string in one place, with a chip showing which ones have been overridden. Reset reverts a string to the in-code default.",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.12h",
    cta: { label: "Open editable copy", href: "/admin/copy" },
  },
  {
    id: "events-calendar-and-rewards-hero",
    title: "New: events calendar, rewards journey, form clear",
    body: "Three things to try: 1) /events now has a monthly calendar grid alongside the upcoming list — click any event day to jump straight in. Admins get demo-seed buttons there too. 2) /rewards opens with a 'journey' progress bar showing your position between every reward tier, plus a much louder lifetime-credits headline. 3) Every form now has a Clear button next to Submit — one confirm and the whole form resets to blank. Bonus: the View-as switcher in the sidebar is now compact (icon-only quick-toggles), and staff visiting any /events/[slug] page get a sticky admin edit bar pinned to the top.",
    placement: "center",
    since: "2026.05.12g",
    cta: { label: "Open events", href: "/events" },
  },
  {
    id: "keyboard-shortcuts",
    title: "New: keyboard shortcuts",
    body: "Press ? from anywhere to see the cheat-sheet. Default bindings: X flips between your real role and trainee-view (admin / superadmin), 1-4 jump to Dashboard / Catalog / My Courses / Events. Rebind any of them at Profile · Shortcuts — settings live on this device. Admin extras: there's also a new admin-only 'Leave' button on /my-courses for fast cleanup after testing player flows, and the trainee 3-course cap is now tunable at /admin/settings.",
    placement: "center",
    since: "2026.05.12f",
    cta: { label: "Open Shortcuts", href: "/profile/shortcuts" },
  },
  {
    id: "credit-expiry-policy",
    title: "Your training credits have a 365-day life",
    body: "Per the BioHubNet ENGAGE policy, awarded training credits expire 365 days from their grant date. We'll email you 90, 30, and 7 days before any expiry — and a banner on your dashboard ramps urgency as the deadline gets closer — so you have time to enroll in courses you want to take. Open the /credits page to see your balance, when your next grant expires, and apply for additional credits if you're an eligible HQP at one of the 14 partner Ontario institutions.",
    path: "/credits",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.12c",
    cta: { label: "Open my credits", href: "/credits" },
  },
  {
    id: "phantom-users",
    title: "Phantom users — spawn-and-forget test accounts",
    body: "Open Administration → Platform → Phantom users. Spawn up to 50 throwaway accounts in a batch (trainee / evaluating / employer / instructor) — each gets a plausible name + phantom-xxxx@bhn.test email + one-click magic-token sign-in. Trainees start with 200 credits so they can enroll in courses immediately. Use them in Manage Enrollments, event registrations, internship pipeline — anywhere a real user works. They auto-delete when their TTL expires (default 24 h, hourly cron sweep). No cleanup to remember.",
    path: "/admin/phantom-users",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.12b",
    cta: { label: "Open phantom users", href: "/admin/phantom-users" },
  },
  {
    id: "greenwood-theme",
    title: "New theme — Greenwood",
    body: "Open the theme picker (bottom-left of the sidebar) and look under Flavours. Greenwood is a forest-inspired light theme: mossy sage-cream surfaces, fern-green CTAs, deep-humus text, and a dashboard hero that reads like looking up at the canopy at golden hour. Calm, organic, easy on the eyes — try it for a session before you commit.",
    placement: "center",
    since: "2026.05.12a",
    cta: { label: "Try Greenwood", href: "/dashboard?try-theme=greenwood" },
  },
  {
    id: "erd-maturity-design-research",
    title: "New: Design & Research admin group + public Roadmap",
    body: "Three new admin pages under Administration → Design & Research:\n\n  • Design system — every token + component pattern rendered live.\n  • Insights — per-period 'what users told us' synthesis. Read the signals, write the note, publish to changelog.\n  • Experience metrics — UX-charter KPIs (queue depth, approval latency, transparency cadence).\n\nA public Roadmap (Now / Next / Later) is now in the sidebar misc group — same view for trainees, admins, and employers.\n\nFor the framing: docs/ux/charter.md names the three user outcomes the platform optimises for, and docs/design-system.md is the canonical companion to the live page.",
    path: "/admin",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.13d",
    cta: { label: "Open insights", href: "/admin/insights" },
  },
  {
    id: "matching-config-panel",
    title: "Tune the AI matching engine from /admin/matching-config",
    body: "The fit scorer's constants are now editable from a UI — no deploy needed. Open Administration → AI matching engine (or click the link in the Superadmin shortcuts at the bottom of /admin). Three sections: subscore weights (sliders, must sum to 100), score bands (where Weak / Possible / Strong cuts off), and 6 cosine/threshold knobs. The live tester at the bottom lets you pick a real trainee × posting and re-score them with your UNSAVED form values, so you can preview the impact of a weight change before committing. Every save audits.",
    path: "/admin/matching-config",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.14f",
    cta: { label: "Open matching config", href: "/admin/matching-config" },
  },
  {
    id: "admin-dashboard-redesign",
    title: "Admin home redesigned around first-hour shortcuts",
    body: "Open /dashboard with admin rights — the home page now leads with eight large quick-action tiles (Demo workspaces, Invite employer, New posting, Talent applicants, Phantom users, View-as, Users, System status / Audit). On fresh installs, a Setup checklist appears above them with the 5 milestones every BHN deployment needs in place (spawn demo workspace, invite first employer, first posting, first course, first talent application). The checklist auto-hides once everything's set up. Approval queues collapse to a single 'all clear' badge when empty, the stat row is now slim chips instead of big tiles, and the hero CTA is context-aware (Review queue / Continue setup / Admin overview). Secondary CTA went from 'Users' to 'View as'.",
    path: "/dashboard",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.14e",
    cta: { label: "Open admin home", href: "/dashboard" },
  },
  {
    id: "mailchimp-doi-signup",
    title: "Newsletter signups now flow through Mailchimp with double-opt-in",
    body: "Two changes on /register: the newsletter radio now defaults to *No thanks* (CASL/GDPR require an active tick, not a pre-selected one), and when a user does pick *Yes, sign me up* the server pushes them to Mailchimp with `status=pending` — Mailchimp emails the confirmation link, and only the click flips them to subscribed. Watch the rollup on /admin/newsletter: the All tab has a new **Mailchimp** column with per-row pills (Pending DOI / Confirmed / Unsubscribed / Cleaned / Push failed). Wire `MAILCHIMP_API_KEY` + `MAILCHIMP_LIST_ID` + `MAILCHIMP_WEBHOOK_SECRET` in env, point Mailchimp's webhook at `/api/webhooks/mailchimp?secret=…`, and you're live.",
    path: "/admin/newsletter",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.14d",
    cta: { label: "Open newsletter admin", href: "/admin/newsletter" },
  },
  {
    id: "talent-applicants-rebuild",
    title: "Talent applicants — match score, inline previews, team-private comments",
    body: "Open `/employer/applicants` (Employer portal → Applicants). Each talent-application card now shows an AI match-score chip against your active postings (Strong / Possible / Weak fit + 0–100 + best-matching posting title — admins see platform-wide), a one-click resume preview that opens inline (PDF, with open-in-tab as the escape hatch), an inline 1-minute video player (native MP4 / WebM, embedded YouTube + Vimeo + Loom), and a team-private comments thread per applicant (trainees never see it; comments load lazily when you open the section). The optional note candidates leave at apply time is also now saved as a separate cover-letter field on the application — visible on the per-applicant detail page.",
    path: "/employer/applicants",
    placement: "center",
    roles: ["employer", "admin", "superadmin", "instructor"],
    since: "2026.05.14c",
    cta: { label: "Open Talent applicants", href: "/employer/applicants" },
  },
  {
    id: "application-prep-coach",
    title: "AI prep coach for every posting — 4 steps, you write, AI scaffolds",
    body: "On any internship posting, look for **Prepare for this posting** next to Apply. Opens a 4-step coach: (1) compare your resume to the JD with AI keyword analysis, (2) draft bullets to close any gaps, (3) work through common interview questions with fill-in-the-blank scaffolding + decoders for what they're really asking, (4) scaffold STAR stories with structure validation + on-demand AI polish. STAR stories save to a reusable Story Bank at /profile/stories. Design principle: AI scaffolds, you write — nothing goes out under your name that wasn't yours.",
    path: "/profile/stories",
    placement: "center",
    roles: ["trainee", "evaluating", "instructor", "admin", "superadmin"],
    since: "2026.05.14b",
    cta: { label: "Open Story Bank", href: "/profile/stories" },
  },
  {
    id: "ai-matching-launch",
    title: "AI matching: postings ranked for you with full receipts",
    body: "New under EXPERIENCE: `Matches for you` at /profile/matches. Every open internship posting is now scored 0–100 against your skill profile + completed pathways, with the full receipts — direct skill overlap, semantic similarity (your adjacent skills that count), pathway alignment, the gaps, and honest caveats when confidence is low. The same explanation panel appears on every posting detail page. Full design notes in docs/ux/decisions/0004-ai-matching-explainability.md.",
    path: "/profile/matches",
    placement: "center",
    roles: ["trainee", "evaluating", "instructor", "admin", "superadmin"],
    since: "2026.05.14a",
    cta: { label: "Open my matches", href: "/profile/matches" },
  },
  {
    id: "internal-roadmap",
    title: "Internal roadmap at /roadmap (superadmin only)",
    body: "There's an internal /roadmap page — Now / Next / Later horizons for the platform. Visible to superadmin only; tentative commitments shouldn't be telegraphed to trainees or employers before they ship. The public-facing 'what shipped' surface stays at /changelog.",
    path: "/roadmap",
    placement: "center",
    roles: ["superadmin"],
    since: "2026.05.14",
    cta: { label: "Open roadmap", href: "/roadmap" },
  },
  {
    id: "playwright-smoke-pack",
    title: "Every PR now goes through Playwright before merge",
    body: "Six headless-browser smoke tests run against every PR's Vercel preview. The symposium registration → admin approve → confirmed flow is fully wired; the other five (login, role switch, workshop booking, permanent-delete promotion, SCORM completion) have strategy outlines and are marked `test.fixme` until filled in.\n\nWhen a PR check goes red, the failure includes a screen recording, DOM trace, and screenshots — drop them into `npx playwright show-report` locally for frame-by-frame replay. See `tests/e2e/README.md` for the full guide.",
    path: "/admin",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.13c",
  },
  {
    id: "events-workshop-approval-quota",
    title: "Tours & workshops now require admin approval",
    body: "Big change to the symposium tour/workshop flow:\n\n  • Every booking starts in **pending** — your seat isn't held until the BHN events team approves it. The form and the workshops browse page both flag this prominently so registrants know to expect a 1–2 day approval wait.\n  • Each slot has its own **20-seat capacity + 5 waitlist spots** (admin-editable per workshop). When both are full, the booking endpoint returns 'waitlist full' and the button says so.\n  • Tour/workshop registration is now **independent of the symposium-day registration** — people can attend one without the other. After each success we cross-prompt: 'You're registered for the symposium but didn't pick a tour — want to?' and vice versa.\n\nFor admins: the registrations queue shows a new 'Pending approval' tile, the attendee detail page has a green Approve button, and each pending workshop booking gets its own per-row Approve action.",
    path: "/admin/events",
    placement: "center",
    since: "2026.05.13b",
    cta: { label: "Open events admin", href: "/admin/events" },
  },
  {
    id: "events-admin-attendee-ops",
    title: "Full attendee operations on the registrations page",
    body: "Open Administration → Engage → Events → any event → Registrations. New: row checkboxes + sticky bulk-action bar (check in / clear check-in / cancel / reinstate); a 'Has note' filter chip; •••• menu per row for resend email and cancel/reinstate. Click any attendee name for a full detail page — edit every field, cancel/reinstate, resend email, manage their workshop bookings (book or cancel on their behalf with waitlist promotion), and leave an internal admin note (VIP / press / special handling). Cancelling a registration auto-releases their workshop bookings and promotes waitlisters.",
    path: "/admin/events",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.11d",
    cta: { label: "Open events admin", href: "/admin/events" },
  },
  {
    id: "events-workshop-pick-in-register",
    title: "Pick workshops while you register",
    body: "The Symposium registration form now includes the full Training Week menu — workshops + tours grouped by day, with live spots-taken counters. Pick up to 2 in the same step that creates your registration. If a slot is full you'll join its waitlist automatically with your position assigned on submit. Skip it if you'd rather choose later — your event dashboard at /events/[slug]/me/workshops has the same picker available any time before the event.",
    path: "/events/2025-annual-symposium/register",
    placement: "center",
    roles: ["trainee", "evaluating", "instructor", "admin", "superadmin"],
    since: "2026.05.11c",
    cta: { label: "Open the registration form", href: "/events/2025-annual-symposium/register" },
  },
  {
    id: "events-discovery",
    title: "The Symposium is now one click away",
    body: "A new 'Events' item under ENGAGE in the sidebar takes you to /events — the public listing of upcoming BHN editions. You'll also see a banner at the top of your dashboard whenever there's an event coming up: 'Register' if you're not in yet, or 'Open my event dashboard' once you've confirmed. The banner auto-hides after the event ends.",
    path: "/dashboard",
    placement: "center",
    roles: ["trainee", "evaluating", "instructor", "admin", "superadmin"],
    since: "2026.05.11b",
    cta: { label: "See upcoming events", href: "/events" },
  },
  {
    id: "events-module",
    title: "Annual Symposium & Training Week is live",
    body: "The /events/2025-annual-symposium page is now the public home for the Symposium + Training Week — workshops, agenda, speakers, sponsors, venue. Trainees register in one click, get a QR pass, and use /events/[slug]/me to browse workshops (book up to 2), pick a breakout for the symposium day, and check their schedule. Admins manage everything under Administration → Engage → Events: edit basics, run the day-of check-in queue, export the attendee CSV for catering / badges / accessibility. Workshops, sessions, speakers, and sponsors are still seeded via prisma/seed-events.ts for now — dedicated CRUD UIs come in a future phase.",
    path: "/dashboard",
    placement: "center",
    since: "2026.05.11a",
    cta: { label: "Open Events admin", href: "/admin/events" },
  },
  {
    id: "complete",
    title: "You're all set",
    body: "Reopen this tour anytime from 'Take the tour' in the sidebar — the compass icon at the bottom-left, sitting next to the theme picker. New features will surface here as they ship.",
    placement: "center",
    since: "2025.04",
  },
];
