/**
 * Onboarding tour content. Steps are filtered per role and per page; each
 * has a stable id stored on the user so progress survives across tours.
 *
 * When the changelog ships a noteworthy feature, append a step with the
 * same `since` version as the changelog entry. Returning users will get
 * a "What's new" mini-tour for steps with `since > user.lastSeenVersion`.
 */
export type StepRole = "trainee" | "evaluating" | "employer" | "instructor" | "admin" | "superadmin";

export interface TourStep {
  id: string;
  title: string;
  body: string;
  /** When user is on this path the step is shown next to the selector;
   *  otherwise we offer a button to navigate there. Skip the step if path
   *  is omitted and we have no selector — purely centered modal. */
  path?: string;
  /** CSS selector to anchor the tooltip to. */
  selector?: string;
  /** Tooltip placement relative to the anchor. */
  placement?: "top" | "right" | "bottom" | "left" | "center";
  /** Roles allowed to see this step. Default: all roles. */
  roles?: StepRole[];
  /** Optional CTA shown on the step (label + href). */
  cta?: { label: string; href: string };
  /** Version this step appeared in. Bump when adding new ones. */
  since: string;
}

/** Bump this whenever a new step is added below — used to re-trigger
 *  the tour for returning users with a friendlier "what's new" hint. */
export const TOUR_VERSION = "2026.05.08h";

export const TOUR_STEPS: TourStep[] = [
  // ─── Welcome ─────────────────────────────────────────────────────
  {
    id: "welcome",
    title: "Welcome to BHN Training",
    body: "Quick 90-second tour of what's on offer. You can pause anytime — we'll save your spot. Press Esc to minimize.",
    placement: "center",
    since: "2025.04",
  },

  // ─── Trainee path ────────────────────────────────────────────────
  {
    id: "trainee.dashboard",
    title: "Your home base",
    body: "The dashboard shows what's in progress, your credit balance, and quick links into the catalog and pathways.",
    path: "/dashboard",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2025.04",
  },
  {
    id: "trainee.catalog",
    title: "Find courses by meaning",
    body: "Type natural language — 'cleanroom gowning' or 'prep for fill-finish role' — and the catalog ranks results by what they actually cover.",
    path: "/courses",
    selector: "input[placeholder*='Search courses']",
    placement: "bottom",
    cta: { label: "Open the catalog", href: "/courses" },
    since: "2025.05",
  },
  {
    id: "trainee.pathways",
    title: "Training pathways",
    body: "Pathways group several courses into one learning journey with a single certificate at the end. Some are open to everyone, others require admin approval.",
    path: "/pathways",
    placement: "center",
    cta: { label: "Browse pathways", href: "/pathways" },
    roles: ["trainee", "evaluating"],
    since: "2025.04",
  },
  {
    id: "trainee.credits",
    title: "Your BHN credits",
    body: "You start with 200 credits. Apply for an additional 4,800 by submitting a quick form — an admin reviews each application personally.",
    path: "/credits",
    placement: "center",
    cta: { label: "View credits", href: "/credits" },
    roles: ["trainee", "evaluating"],
    since: "2025.04",
  },
  {
    id: "trainee.buddy",
    title: "Find a learning buddy",
    body: "Pair up with someone for accountability — pick a course or pathway to share, see each other's progress, and leave async notes.",
    path: "/buddy",
    placement: "center",
    cta: { label: "Open buddies", href: "/buddy" },
    since: "2025.05",
  },
  {
    id: "trainee.profile",
    title: "Your profile",
    body: "Update your name, password, or request a role change from your profile. Click your name in the bottom-left of the sidebar anytime.",
    path: "/profile",
    placement: "center",
    cta: { label: "Open profile", href: "/profile" },
    since: "2025.04",
  },

  // ─── Instructor path ─────────────────────────────────────────────
  {
    id: "instructor.catalog",
    title: "Author courses",
    body: "As an instructor you can create courses, upload SCORM packages, edit course info, and add modules and assessments — right from the catalog.",
    path: "/courses",
    placement: "center",
    cta: { label: "Open catalog", href: "/courses" },
    roles: ["instructor"],
    since: "2025.04",
  },
  {
    id: "instructor.summary",
    title: "AI summaries help learners",
    body: "On every course detail page, click 'Generate summary' to create a learner-facing 3-paragraph summary grounded in the course's modules and assessments.",
    placement: "center",
    roles: ["instructor", "admin", "superadmin"],
    since: "2025.05",
  },

  // ─── Admin path ──────────────────────────────────────────────────
  {
    id: "admin.overview",
    title: "Admin dashboard",
    body: "Top-level operational view: users, enrollments, pathways, certificates. Most management lives in the Administration section in the sidebar.",
    path: "/admin",
    placement: "center",
    cta: { label: "Open admin", href: "/admin" },
    roles: ["admin", "superadmin"],
    since: "2025.04",
  },
  {
    id: "admin.users",
    title: "Bulk user actions",
    body: "Tick multiple rows on the Users page and a sticky action bar appears for batch activate, role change, credit adjust, or group assignment.",
    path: "/admin/users",
    placement: "center",
    cta: { label: "Open users", href: "/admin/users" },
    roles: ["admin", "superadmin"],
    since: "2025.04",
  },
  {
    id: "admin.creditApps",
    title: "Credit applications",
    body: "Trainees apply for additional credits — review each request with their documents and approve or reject from a single page.",
    path: "/admin/credit-applications",
    placement: "center",
    cta: { label: "Open queue", href: "/admin/credit-applications" },
    roles: ["admin", "superadmin"],
    since: "2025.05",
  },
  {
    id: "admin.pathwayEnrolls",
    title: "Pathway enrollment workflow",
    body: "Approve or reject pathway requests, manage waitlists, set capacity and close dates. New 'Pathway enrollments' tab in the sidebar.",
    path: "/admin/pathway-enrollments",
    placement: "center",
    cta: { label: "Open enrollments", href: "/admin/pathway-enrollments" },
    roles: ["admin", "superadmin"],
    since: "2025.05",
  },
  {
    id: "admin.analytics",
    title: "Analytics dashboard",
    body: "User growth, daily activity, the conversion funnel from sign-up to course completion, top events, role and theme distribution. Switch to All-time and export a one-page PDF report.",
    path: "/admin/analytics",
    placement: "center",
    cta: { label: "Open analytics", href: "/admin/analytics" },
    roles: ["admin", "superadmin"],
    since: "2025.05",
  },

  // ─── Superadmin only ─────────────────────────────────────────────
  {
    id: "superadmin.actAs",
    title: "View as another role",
    body: "Above the theme picker in the sidebar, switch to Trainee / Instructor / Admin to see the platform exactly as they do — admin permissions are paused while in this mode.",
    placement: "center",
    roles: ["superadmin"],
    since: "2025.05",
  },

  // ─── Universal closers ───────────────────────────────────────────
  {
    id: "themes",
    title: "Pick your theme",
    body: "Ten elegant themes, light and dark. Find the picker at the bottom of the sidebar — your choice persists across sessions.",
    placement: "center",
    since: "2025.05",
  },
  {
    id: "changelog",
    title: "What's new",
    body: "Every release lands in the change log on the sidebar — trainees see 'What's new', staff see the full Change log with per-entry visibility.",
    placement: "center",
    since: "2025.05",
  },
  {
    id: "event-forms",
    title: "Event registrations live on Pathways",
    body: "Programmes and bootcamps that need a sign-up form now appear as teal cards on the Pathways page. Click one to fill it out — your last response is kept on file. Admins can edit fields in place and export every submission as a CSV.",
    path: "/pathways",
    placement: "center",
    since: "2026.05",
    cta: { label: "Open Pathways", href: "/pathways" },
  },
  {
    id: "bold-hero",
    title: "A bolder welcome",
    body: "The dashboard, pathways, and catalog now open with a full-bleed hero — mesh gradient, drifting organic blobs, your name in gradient type, and stat tiles with asymmetric corners. Less of a default form, more of a place that recognises you.",
    path: "/dashboard",
    placement: "center",
    since: "2026.05.07b",
  },
  {
    id: "auto-thumbnails",
    title: "Course catalog now has AI cover art",
    body: "We've filled in the catalog with one-word AI thumbnails. Each card's cover image is generated from the strongest word in the course title (or its category if set), rendered as a clean editorial illustration. If a course is missing one, run scripts/auto-thumbnail-courses.ts.",
    path: "/courses",
    placement: "center",
    since: "2026.05.07a",
    roles: ["instructor", "admin", "superadmin"],
    cta: { label: "Open the catalog", href: "/courses" },
  },
  {
    id: "employer-invites",
    title: "Invite employer HR partners by link",
    body: "Administration → Employer invites is where you onboard partner companies. Drop in an email, copy the generated link, and send it through your usual channel — when they click through they're guided to set a name + password and land on /employer with the Employer HR role assigned automatically.",
    path: "/admin/employer-invites",
    placement: "center",
    since: "2026.05.07j",
    roles: ["admin", "superadmin"],
  },
  {
    id: "catalog-admin",
    title: "Catalog admin tools",
    body: "Hover any course card on the catalog — admins now see a pencil for quick-edit and a checkbox for bulk-select. Pick a few cards, then use the floating Apply filters button at the bottom to assign topic / delivery / provider in one go. The picker options themselves live at Administration → Course filters.",
    path: "/courses",
    placement: "center",
    since: "2026.05.07i",
    roles: ["admin", "superadmin"],
  },
  {
    id: "catalog-filters",
    title: "Filter the catalog",
    body: "The course catalog now has a filter rail on the left — pick topics, delivery types, providers, or filter to special instructor-led programs. Selections live in the URL so you can share or bookmark a filtered view.",
    path: "/courses",
    placement: "center",
    since: "2026.05.07h",
    cta: { label: "Open the catalog", href: "/courses" },
  },
  {
    id: "internship-board",
    title: "Internship Opportunities is live",
    body: "EXPERIENCE → Internship Opportunities lists open postings from BioHubNet's industry partners. Browse, then apply through the company's own site. Admins post by pasting a job description — the AI parses it into structured fields.",
    path: "/internships",
    placement: "center",
    since: "2026.05.07g",
    cta: { label: "Open the board", href: "/internships" },
  },
  {
    id: "experience-track",
    title: "Experience track is open",
    body: "Looking for an internship or full-time placement? Open EXPERIENCE → Talent Application in the sidebar. It collects your bio, supervisor letter, transcript, resume, and a one-minute STAR video introduction. We share your application with vetted industry partners.",
    path: "/forms/talent-application",
    placement: "center",
    since: "2026.05.07f",
    cta: { label: "Open the application", href: "/forms/talent-application" },
  },
  {
    id: "refined-palette",
    title: "A quieter, more refined palette",
    body: "Daylight, Nightfall, and Scientific now read more editorial than tech-startup — desaturated slate-navy brand, warm putty / charcoal backgrounds, warm graphite text. Less saturation, more sophistication. Hi-Tech keeps its neon edges as the maximalist option.",
    placement: "center",
    since: "2026.05.07d",
  },
  {
    id: "trimmed-themes",
    title: "Four themes, all distinct",
    body: "Open the Theme picker — Daylight, Nightfall, Scientific (Charter serif on cool slate), and Hi-Tech (JetBrains Mono on near-black with neon edges). Each one ships its own typography, surface treatment, and corner radii — switching themes changes the whole design language, not just colour.",
    selector: "[aria-label=\"Change theme\"]",
    placement: "right",
    since: "2026.05.07c",
  },
  {
    id: "ai-greeting",
    title: "A fresh greeting for every visit",
    body: "Below 'Hi, {your name}.' on your dashboard, a small AI-written tagline now appears — tailored to the time of day and your role. Hover the line and you'll see chips to thumbs-up, thumbs-down, regenerate, or turn the feature off entirely if it ever feels too much.",
    placement: "center",
    since: "2026.05.07k",
  },
  {
    id: "rosalind-theme",
    title: "Meet Rosalind",
    body: "New theme inspired by Rosalind Franklin and herbarium-style notebooks: warm parchment background, sage-green CTAs, dusty-rose accent, italic serif headings. Open the Theme picker to try it.",
    selector: "[aria-label=\"Change theme\"]",
    placement: "right",
    since: "2026.05.07k",
  },
  {
    id: "system-status-superadmin",
    title: "System status — for superadmins",
    body: "If you're superadmin, Administration → System status now shows DB ping, AI usage, security signals, and a one-click panel to seed or remove the test employer + trainee + posting + submission set.",
    path: "/admin/system-status",
    placement: "center",
    roles: ["superadmin"],
    since: "2026.05.07k",
    cta: { label: "Open System status", href: "/admin/system-status" },
  },
  {
    id: "newsletter-three-state",
    title: "Newsletter opt-in, three options",
    body: "Sign-up form now asks 'Yes, sign me up' (default), 'I'm already subscribed', or 'No thanks' — instead of a single tick-box. Stops accidentally double-adding existing BioHubNet subscribers.",
    placement: "center",
    since: "2026.05.07l",
  },
  {
    id: "newsletter-export-admin",
    title: "Newsletter exports — for admins",
    body: "Administration → Newsletter exports lists every new opt-in waiting to be added to the BioHubNet ESP. Pick a format (one-per-line / CSV / comma), copy to clipboard, paste into Mailchimp, then click 'Mark as exported' so they don't appear next time. The All tab and a per-row 'Re-arm' button cover edge cases.",
    path: "/admin/newsletter",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07l",
    cta: { label: "Open Newsletter exports", href: "/admin/newsletter" },
  },
  {
    id: "skill-profile",
    title: "Your skill profile is live",
    body: "Open EXPERIENCE → My Skills to see what we know about you. Skills come from completed courses, your talent application, or you can self-claim. Employers use this to score you against their roles.",
    path: "/profile/skills",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.07m",
    cta: { label: "View my skills", href: "/profile/skills" },
  },
  {
    id: "skill-gap-widget",
    title: "See how you match against open roles",
    body: "On the dashboard, the new 'How you match' widget lets you pick any active internship and shows your match score, the skills you bring, what you're missing, and which BHN courses would close the gap.",
    path: "/dashboard",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.07m",
  },
  {
    id: "applicant-kanban",
    title: "Applicant kanban with skill scoring",
    body: "Open any of your postings → Applicants. Each applicant gets a 0–100 skill match, a breakdown of which skills they bring vs miss, and links to the BHN courses that taught them. Drag through New / Reviewing / Shortlisted / Phone screen / Onsite / Offer.",
    placement: "center",
    roles: ["employer", "admin", "superadmin"],
    since: "2026.05.07m",
  },
  {
    id: "interview-scheduler",
    title: "One-click interview scheduling",
    body: "From an applicant's drawer, click Schedule interview, propose 1–5 time slots and a format. The applicant accepts from /interviews on their dashboard. No external calendar OAuth — minimal friction.",
    placement: "center",
    roles: ["employer", "admin", "superadmin"],
    since: "2026.05.07m",
  },
  {
    id: "skill-ontology-admin",
    title: "Skill ontology curation — admins",
    body: "/admin/skills lists every Skill, alias, and which courses / postings / users use it. Merge duplicates, add aliases, deprecate stale entries. AI proposes new skills when content flows in; you approve or merge them here.",
    path: "/admin/skills",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07m",
    cta: { label: "Open skill ontology", href: "/admin/skills" },
  },
  {
    id: "public-marketing-pages",
    title: "/for-employers and /for-trainees",
    body: "Public marketing pages live at /for-employers and /for-trainees, pitching the platform without requiring sign-in. Visitors leave their email and an admin approves from /admin/access-requests.",
    placement: "center",
    since: "2026.05.07m",
  },
  {
    id: "per-admin-sandbox",
    title: "Per-admin sandbox accounts",
    body: "Administration → Sandbox accounts. Each admin spawns one Employer HR + one Trainee pair (idempotent, deterministic emails). Test in parallel with other admins without stomping on shared data. Pair includes a starter posting and a talent-application submission so the kanban / scoring / interview flows all light up immediately.",
    path: "/admin/sandboxes",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07n",
    cta: { label: "Open Sandbox accounts", href: "/admin/sandboxes" },
  },
  {
    id: "demo-filler",
    title: "Fill with sample data",
    body: "Long forms (talent application, posting form, employer profile, trainee profile) now have a 'Fill with sample' chip — admin-only. Click and pick from 5 curated presets so consecutive demos don't all look identical.",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07n",
  },
  {
    id: "my-application",
    title: "Build your application once, reuse it everywhere",
    body: "Open EXPERIENCE → My Application (or visit /profile/application). Three slots: a resume (PDF / DOCX), a 1-minute video introduction, and a short elevator pitch. Each saves independently — upload the resume now, write the pitch later. Talent applications and partner introductions pull from these so you don't re-upload the same files for every employer.",
    path: "/profile/application",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.08a",
    cta: { label: "Open My Application", href: "/profile/application" },
  },
  {
    id: "my-application-sample-admin",
    title: "Fill My Application with a sample (including the video)",
    body: "On /profile/application, admins now see a 'Fill with sample' panel at the top. One click generates a multi-section resume PDF, records an ~8 s WebM video introduction from a canvas animation, and sets a sample elevator pitch — all through the real upload pipeline. Useful for screenshot runs and demoing the candidate snapshot without recording yourself.",
    path: "/profile/application",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.08b",
    cta: { label: "Open My Application", href: "/profile/application" },
  },
  {
    id: "talent-app-prefill",
    title: "Talent Application now pre-fills from My Application",
    body: "Open /forms/talent-application — if you've built a resume, video, and pitch on My Application, they're already imported. A blue banner explains where the values came from and how to edit. Empty submission fields no longer clobber non-empty My-Application defaults, so re-opening a half-finished draft is safe.",
    path: "/forms/talent-application",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.08c",
    cta: { label: "Open the application", href: "/forms/talent-application" },
  },
  {
    id: "admin-security-reports",
    title: "Security reports — for admins",
    body: "Administration → Platform → Security now hosts our internal security reviews. The 8-May-2026 report covers our pre-emptive response to the Canvas / Instructure breach (what we found in BHN that matched the same attack class, what we shipped, what's recommended next). Show this to leadership when they ask 'is BHN safe from what's in the news?'.",
    path: "/admin/security",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.08e",
    cta: { label: "Open Security reports", href: "/admin/security" },
  },
  {
    id: "internship-finder-flow",
    title: "Internships: apply, match, save, track",
    body: "The internship finder grew up. Open EXPERIENCE → Internship Opportunities to browse, then click any posting: you'll see a match score against your skills, the contact email, and a 'Send my application' button that opens your mail client with your pitch + resume URL pre-filled. The same click marks the posting as applied so it appears under EXPERIENCE → My Applications with the employer's current stage. Save a heart on any posting to come back later — saved postings with deadlines in the next 7 days surface on your dashboard.",
    path: "/internships",
    placement: "center",
    roles: ["trainee", "evaluating"],
    since: "2026.05.08h",
    cta: { label: "Browse internships", href: "/internships" },
  },
  {
    id: "daily-fresh-theme",
    title: "A fresh theme each day — try without committing",
    body: "Look for a small card at the top of your dashboard suggesting a new theme. 'Try it' applies the theme for this session only — no commitment. Once you're trying, the card lets you 'Keep it' (save to your profile) or 'Maybe later' (revert). The rotation skips your current theme so it's always something new. Right now Sakura — a limited-time cherry-blossom theme — is featured as the daily pick until 31 May.",
    path: "/dashboard",
    placement: "center",
    roles: ["trainee", "evaluating", "instructor", "admin", "superadmin", "employer"],
    since: "2026.05.08g",
    cta: { label: "Open dashboard", href: "/dashboard" },
  },
  {
    id: "security-program-rollout",
    title: "Security program: ready to flip on when you are",
    body: "All five recommendations from the leadership report have been developed. Three are live (CodeQL + Dependabot + secret scanning, pentest playbook, public /security page + security.txt). Two more are wired in but env-gated: signed-URL R2 access (R2_USE_SIGNED_URLS) and registration hardening with Cloudflare Turnstile + email verification (NEXT_PUBLIC_TURNSTILE_SITE_KEY, BHN_REQUIRE_EMAIL_VERIFY, SMTP_*). Flip the env vars in Vercel when ops is ready.",
    path: "/admin/security",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.08f",
    cta: { label: "Open Security reports", href: "/admin/security" },
  },
  {
    id: "demo-workspaces",
    title: "Demo workspaces for prospective employers",
    body: "Administration → Demo workspaces lets you mint a one-shot link for a partner. They click, enter their name, and land in a populated workspace — 3 sample postings, 10 applicants spread across the funnel, scheduled interviews. Time-limited (default 7 days); the sweeper auto-deletes when the timer runs out.",
    path: "/admin/demo-workspaces",
    placement: "center",
    roles: ["admin", "superadmin"],
    since: "2026.05.07n",
    cta: { label: "Open Demo workspaces", href: "/admin/demo-workspaces" },
  },
  {
    id: "complete",
    title: "You're all set",
    body: "Reopen this tour anytime from 'Take the tour' in the sidebar (or the small ? button at the bottom-left). New features will surface here as they ship.",
    placement: "center",
    since: "2025.04",
  },
];
