/** Auto-generated from the source xlsx — DO NOT edit by hand.
 *  To refresh after the xlsx is updated, re-run the extraction.
 *  Source: 'Biomanufacturing Companies & Facilities in Canada.xlsx'
 *  (sheets: "compiled biomanufacturing facil" + "initial find") */

export interface FacilitySeed {
  name: string;
  url: string | null;
  status: string | null;       // 'Being built' / 'Already built' / null
  province: string | null;
  city: string | null;
  address: string | null;
  specialization: string | null;
  scale: string | null;
  notes: string | null;
  lat: number;
  lng: number;
}

export const FACILITY_SEED: FacilitySeed[] = [
  {
    name: "A&C (A&C Pharm. Tech)",
    url: null,
    status: null,
    province: "QC",
    city: "Montreal",
    address: null,
    specialization: "GMP excipients & raw materials",
    scale: "101–250 employees",
    notes: "Supplies input materials for biomanufacturing",
    lat: 45.508000,
    lng: -73.566355,
  },
  {
    name: "ACIC Pharmaceuticals",
    url: "https://acic.com/",
    status: "Already built",
    province: "Ontario",
    city: "Brantford",
    address: null,
    specialization: "Full-service CDMO focusing on sterile injectable biologics and vaccines; GMP drug substance and fill-finish.",
    scale: "Mid-size operation based in Montréal; multiple aseptic lines serving global markets.",
    notes: "Link",
    lat: 51.295628,
    lng: -85.465697,
  },
  {
    name: "ARSI Canada",
    url: "https://www.arsicanada.com/",
    status: "Already built",
    province: "Ontario",
    city: "Mississauga",
    address: null,
    specialization: "Analytical research services including stability testing, QC/QA labs, pharma analytics.",
    scale: "Canadian network of labs—med–large analytical service capacity.",
    notes: "Link",
    lat: 43.582291,
    lng: -79.641958,
  },
  {
    name: "AbCellera",
    url: null,
    status: null,
    province: "British Columbia",
    city: "Vancouver",
    address: null,
    specialization: "Antibody discovery platform",
    scale: "Expanding with major investment",
    notes: "Supported COVID-19 antibody programs",
    lat: 49.289387,
    lng: -123.119972,
  },
  {
    name: "Acanthas Pharma",
    url: null,
    status: null,
    province: "Ontario",
    city: "Dundas",
    address: null,
    specialization: "Clinical-stage biotech developing peptide-targeted radiotherapeutics for cancer treatment (e.g., CCR8-targeted agents).",
    scale: "Small team (~20–30) based in Montréal with preclinical/early clinical operations.",
    notes: "Link",
    lat: 51.103972,
    lng: -85.375953,
  },
  {
    name: "AcuPharma Solutions",
    url: "http://acupharmasolutions.com/",
    status: "Already built",
    province: "Ontario",
    city: "Mississauga",
    address: null,
    specialization: "Contract Research, Manufacturing & Consulting",
    scale: null,
    notes: null,
    lat: 43.594675,
    lng: -79.639859,
  },
  {
    name: "Acuitas Therapeutics",
    url: "https://acuitastx.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Vancouver",
    address: null,
    specialization: "Lipid nanoparticle (LNP) delivery systems for nucleic acid therapeutics (e.g., mRNA, siRNA, CRISPR) — platform technology behind Pfizer–BioNTech COVID‑19 vaccine; also collaborating with Bayer for gene editing delivery",
    scale: "IP used in Pfizer-BioNTech vaccine;~98–120 employees (recent growth ~25%) with estimated annual revenue of CAD 15–19 million; global partnerships (Pfizer, CureVac, Bayer)",
    notes: "Link",
    lat: 49.277301,
    lng: -123.127343,
  },
  {
    name: "Alanza",
    url: "https://alanzainc.com/",
    status: "Already built",
    province: "Ontario",
    city: "Thornhill",
    address: null,
    specialization: "Contract Manufacturing - Vials, Sterile Formulations",
    scale: null,
    notes: null,
    lat: 51.371454,
    lng: -85.447118,
  },
  {
    name: "Alberta Cell Therapy Manufacturing",
    url: "https://biocanrx.com/alberta-cell-therapy-manufacturing",
    status: "Already built",
    province: "Alberta",
    city: "Edmonton",
    address: null,
    specialization: null,
    scale: null,
    notes: null,
    lat: 53.544226,
    lng: -113.505085,
  },
  {
    name: "Altasciences",
    url: "https://www.altasciences.com/",
    status: "Already built",
    province: "QC",
    city: "Laval",
    address: null,
    specialization: "CRO & CDMO for preclinical to early phase",
    scale: "~1,000 employees",
    notes: "Cross-border early-phase services",
    lat: 45.599847,
    lng: -73.712271,
  },
  {
    name: "Apotex / Apobiologix",
    url: "https://www.apobiologix.com/",
    status: "Already built",
    province: "Ontario",
    city: "Etobicoke",
    address: null,
    specialization: "Generics & biosimilars",
    scale: "Thousands of employees",
    notes: "Canada's largest generic pharma company",
    lat: 51.111761,
    lng: -85.413549,
  },
  {
    name: "Aramis Biotechnologies",
    url: "https://aramisbiotechnologies.com/en/",
    status: "Being built",
    province: "QC",
    city: "Quebec City",
    address: null,
    specialization: "Plant-based biologics & vaccines",
    scale: "SIF-supported, expansion underway",
    notes: "New vaccine platform based on plant systems",
    lat: 46.817497,
    lng: -71.206921,
  },
  {
    name: "Aspect Biosystems",
    url: "https://www.ic.gc.ca/eic/site/125.nsf/eng/home",
    status: "Being built",
    province: "British Columbia",
    city: "Vancouver",
    address: null,
    specialization: "3D bioprinting of human tissues for therapeutics development",
    scale: null,
    notes: "Link",
    lat: 49.290126,
    lng: -123.132544,
  },
  {
    name: "AtomVie Global Radiopharma",
    url: "https://www.atomvie.com/",
    status: "Already built",
    province: "Ontario",
    city: "Hamilton",
    address: null,
    specialization: "Radiopharmaceuticals for oncology diagnostics and therapeutics; production of short-lived isotopes and cold kits.",
    scale: "Based in Toronto; small to mid-size manufacturing and distribution center.",
    notes: "Link",
    lat: 43.263040,
    lng: -79.866345,
  },
  {
    name: "BIOVECTRA",
    url: "https://www.biovectra.com/facilities/",
    status: "Being built",
    province: "Prince Edward Island",
    city: "Charlottetown",
    address: null,
    specialization: "CDMO with capabilities in small molecules (APIs), complex chemistry, and microbial/biologic fermentation (including mRNA/pDNA). Offers process development, pilot-to-commercial scale production, formulation, analytical testing, and aseptic fill–finish. Utilizes both stainless-steel and single-use fermenters, including 100 L–17,000 L scales. Recognized for excellence in biologics with the 2025 Outsourced Pharma CDMO Leadership Award.",
    scale: "Operates 5 GMP facilities in Atlantic Canada: Charlottetown (4 sites), Windsor NS (biologics), totalling ~25,000 m². Fermentation capacity: ~118,000 L chemical reactors, 64,000 L bioreactors. Active workforce of 550+ employees, part of Agilent since acquisition.",
    notes: "Link",
    lat: 46.246881,
    lng: -63.129244,
  },
  {
    name: "Bausch Health",
    url: "https://www.bauschhealth.com/",
    status: "Already built",
    province: "Quebec",
    city: "Laval",
    address: null,
    specialization: "Pharmaceuticals: R&D, formulation, clinical manufacturing, fill-finish, OTC packaging",
    scale: "~338,000 ft²",
    notes: "Corporate HQ; co-located R&D and manufacturing; exports ~70% of production; serves global markets .",
    lat: 45.602766,
    lng: -73.720668,
  },
  {
    name: "Bausch Health (Steinbach Site; formerly Biovail)",
    url: "https://www.bauschhealth.com/",
    status: "Already built",
    province: "Manitoba",
    city: "Steinbach",
    address: null,
    specialization: "Oral solid dosage: controlled-release tablets/capsules",
    scale: "~241,000 ft²; ~1.2 billion tablets/capsules produced annually across ~12 products",
    notes: "Full-service pharma manufacturing; ~500 employees; operates 24/5 with some weekend shifts; major North American production hub .",
    lat: 53.898064,
    lng: -98.862922,
  },
  {
    name: "Baxter",
    url: "https://www.baxter.com/",
    status: "Already built",
    province: "Ontario",
    city: "Alliston",
    address: null,
    specialization: "Medication Delivery",
    scale: null,
    notes: null,
    lat: 51.131624,
    lng: -85.444185,
  },
  {
    name: "BioAccelerator",
    url: "https://peibioalliance.com/bioaccelerator/",
    status: "Already built",
    province: "Prince Edward Island",
    city: "Charlottetown",
    address: null,
    specialization: "Bioscience scale-up center for Atlantic Canada",
    scale: null,
    notes: "Link",
    lat: 46.246540,
    lng: -63.128611,
  },
  {
    name: "Biodextris",
    url: "https://www.biodextris.com/",
    status: "Being built",
    province: "Quebec",
    city: "Laval",
    address: null,
    specialization: "Analytical and process development for vaccines/biologics, manufacturing services of prokaryote and eukaryote-derived proteins",
    scale: null,
    notes: null,
    lat: 45.613971,
    lng: -73.706886,
  },
  {
    name: "Biologics Manufacturing Centre (NRC)",
    url: "https://bmc-cppb.ca/",
    status: "Already built",
    province: "Quebec",
    city: "Montreal",
    address: null,
    specialization: "Biologics (vaccines, proteins)",
    scale: "~2M doses/month",
    notes: "Publicly funded, end-to-end GMP vaccine capacity",
    lat: 45.502569,
    lng: -73.555945,
  },
  {
    name: "Biomatik",
    url: "https://www.biomatik.com/",
    status: "Already built",
    province: "Ontario",
    city: "Kitchener",
    address: null,
    specialization: "Biologics contract manufacturer of proteins, antibodies, plasmids, and enzymes for life science research.",
    scale: "Located in Kitchener, ON; employs ~50–70 staff; focused on preclinical and research-grade production.",
    notes: "Link",
    lat: 43.448685,
    lng: -80.491251,
  },
  {
    name: "Biotherapeutics Manufacturing Centre",
    url: "https://www.ohri.ca/bmc/",
    status: "Already built",
    province: "Ontario",
    city: "#VALUE!",
    address: null,
    specialization: null,
    scale: null,
    notes: null,
    lat: 51.352621,
    lng: -85.287644,
  },
  {
    name: "C3i Center",
    url: "https://c3icenter.com/",
    status: "Already built",
    province: "Quebec",
    city: "Montreal",
    address: null,
    specialization: "Canada’s only fully validated cGMP cell & gene therapy CDMO, covering cell-line development through commercial manufacture, including viral vector and master cell bank production",
    scale: "37,000 ft² facility with 14 cleanrooms; FDA/EMA/Health Canada compliant; commercial capacity.",
    notes: "Link",
    lat: 45.506610,
    lng: -73.578200,
  },
  {
    name: "Canadian Critical Drug Initiative",
    url: "https://appliedpharma.ca/ccdi-growing-the-life-sciences-industry/",
    status: "Being built",
    province: "Alberta",
    city: "Montreal",
    address: null,
    specialization: null,
    scale: null,
    notes: "What the Facility Does\": \"Federal-funded facility focused on critical medicines manufacturing",
    lat: 45.495170,
    lng: -73.572355,
  },
  {
    name: "CellCarta",
    url: "https://cellcarta.com/",
    status: "Already built",
    province: "Quebec",
    city: "Montreal",
    address: null,
    specialization: "Biomarker & specialty lab services",
    scale: "International sites",
    notes: "Precision medicine support",
    lat: 45.491615,
    lng: -73.573713,
  },
  {
    name: "Contract Pharmaceuticals",
    url: null,
    status: null,
    province: "Ontario",
    city: "Mississauga",
    address: null,
    specialization: "Custom synthesis and manufacturing of active pharmaceutical ingredients (APIs) and intermediates.",
    scale: "small-mid scale with niche chemical synthesis expertise.",
    notes: "Link",
    lat: 43.577467,
    lng: -79.633802,
  },
  {
    name: "Contract Pharmaceuticals Ltd. (CPL)",
    url: "https://cplltd.com/",
    status: "Already built",
    province: "Ontario",
    city: "Mississauga",
    address: null,
    specialization: "Liquids & semi-solids (CDMO)",
    scale: "~300 employees",
    notes: "Focus on non-sterile manufacturing",
    lat: 43.579424,
    lng: -79.649429,
  },
  {
    name: "Corealis Pharma",
    url: "https://www.corealispharma.com/",
    status: "Already built",
    province: "Quebec",
    city: "Laval",
    address: null,
    specialization: "Contract Oral Dosage Forms",
    scale: null,
    notes: null,
    lat: 45.609856,
    lng: -73.715644,
  },
  {
    name: "Dalton Pharma Services",
    url: "https://www.dalton.com/",
    status: "Already built",
    province: "Ontario",
    city: "Toronto",
    address: null,
    specialization: "Specialized CDMO for medical isotopes (PET/SPECT), radiochemistry, and API services.",
    scale: "Canadian operations with small-scale facilities supporting nuclear medicine supply chains.",
    notes: "Link",
    lat: 43.650084,
    lng: -79.390172,
  },
  {
    name: "Delpharm",
    url: "https://www.delpharm.com/en/",
    status: "Already built",
    province: "Quebec",
    city: "Boucherville",
    address: null,
    specialization: "Contract Manufacturing",
    scale: "Multiple global plants; Canadian presence supports packaging and API fill-finish; mid-large facility.",
    notes: "Link",
    lat: 52.869993,
    lng: -73.418104,
  },
  {
    name: "Emergent Biosolutions",
    url: "https://www.emergentbiosolutions.com/",
    status: "Already built",
    province: "Manitoba",
    city: "Winnipeg",
    address: null,
    specialization: "Produces vaccines and antibody therapeutics for infectious diseases and biodefense; products include anthrax vaccine (BioThrax) and opioid antagonist Narcan; active in COVID‑19 vaccine manufacturing",
    scale: "U.S.-based multinational with ~1,600 employees; global manufacturing footprint and high revenue (~USD 1–2 B)",
    notes: "Link",
    lat: 49.898653,
    lng: -97.135781,
  },
  {
    name: "Entos Pharmaceuticals",
    url: "https://www.entospharma.com/",
    status: "Being built",
    province: "Alberta",
    city: "Edmonton",
    address: null,
    specialization: "Genetic medicines (DNA vaccines, therapeutics)",
    scale: "~103,000 ft² GMP facility",
    notes: "New R&D + manufacturing site; Genetic medicines and mRNA therapeutics production",
    lat: 53.538207,
    lng: -113.488301,
  },
  {
    name: "Eurofins CDMO",
    url: null,
    status: null,
    province: "Ontario",
    city: "Mississauga",
    address: null,
    specialization: "Pharmaceutical contract manufacturing under Eurofins Pharma; includes APIs, formulations, biotech.",
    scale: "Canadian branches with small-to-mid scale GMP sites.",
    notes: "Link",
    lat: 43.598089,
    lng: -79.636140,
  },
  {
    name: "GSK Canada",
    url: "https://ca.gsk.com/en-ca/",
    status: "Already built",
    province: "Quebec",
    city: "Quebec City",
    address: null,
    specialization: "Flu vaccines",
    scale: "Multi-year supply production",
    notes: "Global flu vaccine production site",
    lat: 46.822128,
    lng: -71.201376,
  },
  {
    name: "Genevant Sciences",
    url: "https://www.genevant.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Vancouver",
    address: null,
    specialization: "Lipid nanoparticle (LNP) platform for mRNA, siRNA, and gene-editing delivery; holds broad LNP IP and is advancing clinical programs in collaboration with companies like Editas",
    scale: "Based in Vancouver; around 50–100 employees",
    notes: "Link",
    lat: 49.274622,
    lng: -123.123593,
  },
  {
    name: "Genvion",
    url: "https://genvion.ca/",
    status: "Already built",
    province: "Manitoba",
    city: "Winnipeg",
    address: null,
    specialization: null,
    scale: null,
    notes: "Link",
    lat: 49.906849,
    lng: -97.135040,
  },
  {
    name: "Groupe PARIMA",
    url: "http://groupeparima.com/",
    status: "Already built",
    province: "Quebec",
    city: "Montreal",
    address: null,
    specialization: "Non-sterile semi-solids, liquids, suspensions CDMO; product development, validation, QC, analytical testing",
    scale: "67,000 ft² modern facility; serving ~30+ global markets; inspected by FDA, EMA, TMMDA, HC.",
    notes: "Link",
    lat: 45.503067,
    lng: -73.562869,
  },
  {
    name: "ImmunoPrecise Antibodies",
    url: "https://www.ipatherapeutics.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Victoria",
    address: null,
    specialization: "Custom antibody discovery, engineering, and production services (murine/human antibodies, CAR-T reagents).",
    scale: "~200 employees; two Canadian facilities (Victoria, BC & Montréal, QC); publicly traded (TSX:IPA).",
    notes: "Link",
    lat: 48.421897,
    lng: -123.376830,
  },
  {
    name: "Jubilant HollisterStier",
    url: "https://www.jublhs.com/",
    status: "Being built",
    province: "Quebec",
    city: "Kirkland",
    address: null,
    specialization: "Canadian-based sterile injectable and vaccine fill-and-finish CDMO; multiple GMP lines; capacity scaled for pandemic and seasonal vaccines. Operates in Kirkland, QC (fill–finish), and elsewhere",
    scale: null,
    notes: "Link",
    lat: 52.884536,
    lng: -73.618778,
  },
  {
    name: "Laboratoires Confab",
    url: "https://confab.com/",
    status: "Already built",
    province: "Quebec",
    city: "Longueuil",
    address: null,
    specialization: "Oral/Topical dosage manufacturing (CDMO)",
    scale: "~300 employees",
    notes: "Non-sterile commercial-scale facility",
    lat: 52.853195,
    lng: -73.416227,
  },
  {
    name: "Liminal BioSciences",
    url: "https://liminalbiosciences.com/",
    status: "Already built",
    province: "Quebec",
    city: "Laval",
    address: null,
    specialization: "Plasma-derived therapeutics",
    scale: "Publicly traded",
    notes: "Focus on fibrosis and liver diseases",
    lat: 45.615633,
    lng: -73.716848,
  },
  {
    name: "Medicago (now defunct)",
    url: null,
    status: null,
    province: "Quebec",
    city: "Quebec City",
    address: null,
    specialization: "Plant-based vaccines",
    scale: "Former COVID vaccine developer",
    notes: "Ceased operations in 2023 due to funding / market issues",
    lat: 46.809280,
    lng: -71.218610,
  },
  {
    name: "Moderna Canada",
    url: null,
    status: null,
    province: "Quebec",
    city: "Laval",
    address: null,
    specialization: "mRNA vaccines",
    scale: "~100M doses/year (expandable)",
    notes: "New facility, pandemic preparedness focus",
    lat: 45.615672,
    lng: -73.701673,
  },
  {
    name: "NanoVation Therapeutics",
    url: "https://nanovationtx.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Vancouver",
    address: null,
    specialization: "Develops next-gen lipid nanoparticle (LNP) platforms for nucleic-acid delivery targeting extrahepatic tissues, including proprietary long-circulating LNP (lcLNP™) technology that enhances potency, safety, and stability of gene medicines",
    scale: "team of lipid chemists and RNA specialists; focused on preclinical development and partnerships",
    notes: "Link",
    lat: 49.286431,
    lng: -123.123205,
  },
  {
    name: "Norgen Biotek",
    url: "https://norgenbiotek.com/",
    status: "Already built",
    province: "Ontario",
    city: "Hamilton",
    address: null,
    specialization: "Products for sample collection, sample preparation and sample detection. Comprehensive research services",
    scale: null,
    notes: null,
    lat: 43.265649,
    lng: -79.872088,
  },
  {
    name: "Northern RNA",
    url: "https://northernrna.com/",
    status: "Being built",
    province: "Alberta",
    city: "Calgary",
    address: null,
    specialization: "RNA raw material production",
    scale: "Regional capacity building",
    notes: "Part of Alberta's RNA supply chain",
    lat: 51.039057,
    lng: -114.077981,
  },
  {
    name: "Novel Bio",
    url: "https://www.novel-bio.com/",
    status: "Already built",
    province: "Ontario",
    city: "Whitby",
    address: null,
    specialization: "Plasmid DNA Production",
    scale: null,
    notes: null,
    lat: 51.272210,
    lng: -85.394378,
  },
  {
    name: "Novocol Pharma",
    url: null,
    status: null,
    province: "Ontario",
    city: "Burlington",
    address: null,
    specialization: "Sterile injectable CDMO with fill-finish capabilities.",
    scale: null,
    notes: "Link",
    lat: 51.129496,
    lng: -85.327403,
  },
  {
    name: "NuBiyota Headquarters / R&D",
    url: "https://nubiyota.com/",
    status: "Already built",
    province: "Ontario",
    city: "Guelph",
    address: null,
    specialization: "Microbiome R&D, donor screening, strain banking",
    scale: "Not publicly disclosed — dedicated lab space",
    notes: "Hosts core MET platform development; origin site licensed from University of Guelph .",
    lat: 43.546830,
    lng: -80.238652,
  },
  {
    name: "OmniaBio",
    url: "https://omniabio.com/",
    status: "Already built",
    province: "Ontario",
    city: "Hamilton",
    address: null,
    specialization: "Full-service CGT (cell & gene therapy) CDMO offering end-to-end capabilities—from process development to large-scale clinical and commercial manufacturing.  Integrates AI, robotics, and closed‑unit systems for lentiviral, autologous/allogeneic cell therapies, iPSC, and viral vectors.  Offers development & analytical services with GMP compliance across FDA, EMA, and Health Canada.",
    scale: "Canada’s largest CGT-focused CDMO. Hamilton, ON: 120,000 ft² (now expanded to ~160,000 ft²) intelligent factory at McMaster Innovation Park, with 26 clean rooms and AI/automation workflows. Launched October 2024, employing ~250 staff with >$580 M investment backed by Invest Ontario.  Toronto site at MaRS Discovery District: ~10 ISO Class 7 clean rooms with development and GMP suites",
    notes: "Link",
    lat: 43.267641,
    lng: -79.870871,
  },
  {
    name: "O’Hara Technologies Manufacturing Plant",
    url: "https://www.oharatech.com/",
    status: "Already built",
    province: "Ontario",
    city: "Richmond Hill",
    address: null,
    specialization: "Design & fabrication of solid-dosage processing equipment (tablet coaters, dryers, granulators, blenders)",
    scale: "~65,000 ft² production floor bionity.com+11oharatech.com+11yellowpages.ca+11",
    notes: "Houses metal fabrication, welding, assembly, instrumentation teams; outputs from lab-scale to high-volume continuous systems . Built to ISO, GMP/cGMP, CE standards; low utility footprint oharatech.com.",
    lat: 51.223620,
    lng: -85.407404,
  },
  {
    name: "PBG BioPharma",
    url: "https://www.pbgbiopharma.com/",
    status: "Already built",
    province: "Alberta",
    city: "PBG BioPharma",
    address: null,
    specialization: "Biotech Contract Manufacturing",
    scale: null,
    notes: null,
    lat: 53.816195,
    lng: -116.538266,
  },
  {
    name: "PCI Pharma Services",
    url: "https://pci.com/",
    status: "Already built",
    province: "Ontario",
    city: "Burlington",
    address: null,
    specialization: "Full-service pharma services: clinical/commercial manufacturing, packaging, cold chain, serialization.",
    scale: "Mid-to-large operations in Canada, including site in Brantford, ON and Vancouver, BC; part of global PCI group.",
    notes: "Link",
    lat: 51.341424,
    lng: -85.346552,
  },
  {
    name: "Patheon",
    url: "https://www.patheon.com/us/en/home.html",
    status: "Already built",
    province: "Ontario",
    city: "Whitby",
    address: null,
    specialization: "Full-service CDMO: small-molecule APIs, biologics, viral vectors, plasmids, formulations, clinical logistics, and packaging",
    scale: "Multinational, widely spread",
    notes: "Link",
    lat: 51.131073,
    lng: -85.459065,
  },
  {
    name: "Pharma Medica Research",
    url: "https://www.pharmamedica.com/",
    status: "Already built",
    province: "Ontario",
    city: "Mississauga",
    address: null,
    specialization: "Bioanalytics, clinical trials, CDMO",
    scale: "250–500 employees",
    notes: "Full-service clinical CRO + labs",
    lat: 43.578525,
    lng: -79.646941,
  },
  {
    name: "Pillar5 Pharma",
    url: "https://pillar5pharma-anjac.com/",
    status: "Already built",
    province: "Ontario",
    city: "Arnprior",
    address: null,
    specialization: "Contract Everything",
    scale: "small to mid-scale.",
    notes: "Link",
    lat: 51.402636,
    lng: -85.314466,
  },
  {
    name: "Qeen Biotechnologies",
    url: "https://qeen-bio.com/",
    status: "Already built",
    province: "Quebec",
    city: "Gatineau",
    address: null,
    specialization: "Bacteriophages",
    scale: null,
    notes: null,
    lat: 53.081224,
    lng: -73.440866,
  },
  {
    name: "Resilience",
    url: "https://resilience.com/",
    status: "Already built",
    province: "Ontario",
    city: "Mississauga",
    address: null,
    specialization: "Biomanufacturing",
    scale: null,
    notes: null,
    lat: 43.577276,
    lng: -79.638803,
  },
  {
    name: "Resonetics",
    url: "https://resonetics.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Surrey",
    address: null,
    specialization: "Contract Medical Device Manufacturing & Development",
    scale: null,
    notes: null,
    lat: 53.781213,
    lng: -127.636509,
  },
  {
    name: "STEMCELL Technologies",
    url: "https://www.stemcell.com/",
    status: "Being built",
    province: "British Columbia",
    city: "Burnaby",
    address: null,
    specialization: "Cell therapy tools, GMP reagents",
    scale: ">1,000 jobs",
    notes: "Largest Canadian biotech, expanding cell/gene therapy tools",
    lat: 49.239477,
    lng: -122.982066,
  },
  {
    name: "Sanofi Pasteur",
    url: null,
    status: null,
    province: "Ontario",
    city: "Toronto",
    address: null,
    specialization: "Vaccines (Influenza), Fill & Finish",
    scale: "~$925M facility, ~1,225 jobs",
    notes: "Major flu vaccine producer, large-scale infrastructure",
    lat: 43.642861,
    lng: -79.376946,
  },
  {
    name: "StarFish Medical",
    url: "https://starfishmedical.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Victoria",
    address: null,
    specialization: "Contract Medical Device Manufacturing & Development",
    scale: null,
    notes: null,
    lat: 48.422804,
    lng: -123.362217,
  },
  {
    name: "Teva canada",
    url: "https://www.tevacanada.com/en/about-teva/manufacturing-facilities/",
    status: "Already built",
    province: "Ontario",
    city: "Whitchurch-Stouffville",
    address: "30 Novopharm Ct, Scarborough, ON M1B 2K9",
    specialization: null,
    scale: null,
    notes: null,
    lat: 51.239917,
    lng: -85.187055,
  },
  {
    name: "Therapure Biopharma",
    url: "https://www.therapurebio.com/",
    status: "Already built",
    province: "Ontario",
    city: "Mississauga",
    address: null,
    specialization: "Protein therapeutics, CDMO services",
    scale: "~130,000 ft², ~300 employees",
    notes: "Advanced protein process development",
    lat: 43.598020,
    lng: -79.649779,
  },
  {
    name: "Virogen Biotechnology",
    url: "https://www.virogen.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Richmond",
    address: null,
    specialization: "Antigens and Antibodies",
    scale: null,
    notes: null,
    lat: 49.176503,
    lng: -123.124708,
  },
  {
    name: "Viva Pharmaceutical",
    url: "https://www.vivapharm.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Richmond",
    address: null,
    specialization: "Custom Manufacturing",
    scale: "Largest GMP cert facility in BC: ~52,000 ft² on 73,000 ft² site; Health Canada & FDA licensed; halal certified",
    notes: "Link",
    lat: 49.161763,
    lng: -123.130265,
  },
  {
    name: "Zymeworks",
    url: "https://www.zymeworks.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Vancouver",
    address: null,
    specialization: "Bispecific antibodies, protein therapeutics",
    scale: "~275 employees",
    notes: "Public company, innovative biologics platform",
    lat: 49.285315,
    lng: -123.129032,
  },
  {
    name: "uBriGene",
    url: "https://www.ubrigene.com/",
    status: "Already built",
    province: "British Columbia",
    city: "Richmond",
    address: null,
    specialization: "Cell & Gene Therapy CDMO",
    scale: null,
    notes: null,
    lat: 49.166614,
    lng: -123.141312,
  },
];
