/** Auto-generated from the source xlsx — DO NOT edit by hand.
 *  To refresh after the xlsx is updated, re-run the extraction.
 *  Source: 'Biomanufacturing Companies & Facilities in Canada.xlsx'
 *  (sheets: "compiled biomanufacturing facil" + "initial find") */

export interface FacilitySeed {
  name: string;
  url: string | null;
  status: string | null;       // 'Being built' / 'Already built' / null
  province: string | null;
  city: string | null;
  address: string | null;
  specialization: string | null;
  scale: string | null;
  notes: string | null;
  lat: number;
  lng: number;
}

export const FACILITY_SEED: FacilitySeed[] = [
  {
    name: "A&C (A&C Pharm. Tech)",
    url: null,
    status: null,
    province: "QC",
    city: "Montreal",
    address: null,
    specialization: "GMP excipients & raw materials",
    scale: "101–250 employees",
    notes: "Supplies input materials for biomanufacturing",
    lat: 45.508000,
    lng: -73.566355,
  },
  {
    name: "ACIC Pharmaceuticals",
    url: "https://acic.com/",
    status: "Already built",
    province: "ON",
    city: "Brantford",
    address: null,
    specialization: "Full-service CDMO focusing on sterile injectable biologics and vaccines; GMP drug substance and fill-finish.",
    scale: "Mid-size CDMO with multiple aseptic lines serving global markets.",
    notes: null,
    lat: 43.1394,
    lng: -80.2644,
  },
  {
    name: "ARSI Canada",
    url: "https://www.arsicanada.com/",
    status: "Already built",
    province: "ON",
    city: "Mississauga",
    address: null,
    specialization: "Analytical research services including stability testing, QC/QA labs, pharma analytics.",
    scale: "Canadian network of labs—med–large analytical service capacity.",
    notes: null,
    lat: 43.582291,
    lng: -79.641958,
  },
  {
    name: "AbCellera",
    url: null,
    status: null,
    province: "BC",
    city: "Vancouver",
    address: null,
    specialization: "Antibody discovery platform",
    scale: "Expanding with major investment",
    notes: "Supported COVID-19 antibody programs",
    lat: 49.289387,
    lng: -123.119972,
  },
  {
    name: "Acanthas Pharma",
    url: null,
    status: null,
    province: "ON",
    city: "Dundas",
    address: null,
    specialization: "Clinical-stage biotech developing peptide-targeted radiotherapeutics for cancer treatment (e.g., CCR8-targeted agents).",
    scale: "Small team (~20–30) with preclinical/early clinical operations.",
    notes: null,
    lat: 43.2664,
    lng: -79.9586,
  },
  {
    name: "AcuPharma Solutions",
    url: "http://acupharmasolutions.com/",
    status: "Already built",
    province: "ON",
    city: "Mississauga",
    address: null,
    specialization: "Contract Research, Manufacturing & Consulting",
    scale: null,
    notes: null,
    lat: 43.594675,
    lng: -79.639859,
  },
  {
    name: "Acuitas Therapeutics",
    url: "https://acuitastx.com/",
    status: "Already built",
    province: "BC",
    city: "Vancouver",
    address: null,
    specialization: "Lipid nanoparticle (LNP) delivery systems for nucleic acid therapeutics (e.g., mRNA, siRNA, CRISPR) — platform technology behind Pfizer–BioNTech COVID‑19 vaccine; also collaborating with Bayer for gene editing delivery",
    scale: "IP used in Pfizer-BioNTech vaccine;~98–120 employees (recent growth ~25%) with estimated annual revenue of CAD 15–19 million; global partnerships (Pfizer, CureVac, Bayer)",
    notes: null,
    lat: 49.277301,
    lng: -123.127343,
  },
  {
    name: "Alanza",
    url: "https://alanzainc.com/",
    status: "Already built",
    province: "ON",
    city: "Thornhill",
    address: null,
    specialization: "Contract Manufacturing - Vials, Sterile Formulations",
    scale: null,
    notes: null,
    lat: 43.8161,
    lng: -79.4242,
  },
  {
    name: "Alberta Cell Therapy Manufacturing",
    url: "https://biocanrx.com/alberta-cell-therapy-manufacturing",
    status: "Already built",
    province: "AB",
    city: "Edmonton",
    address: null,
    specialization: null,
    scale: null,
    notes: null,
    lat: 53.544226,
    lng: -113.505085,
  },
  {
    name: "Altasciences",
    url: "https://www.altasciences.com/",
    status: "Already built",
    province: "QC",
    city: "Laval",
    address: null,
    specialization: "CRO & CDMO for preclinical to early phase",
    scale: "~1,000 employees",
    notes: "Cross-border early-phase services",
    lat: 45.599847,
    lng: -73.712271,
  },
  {
    name: "Apotex / Apobiologix",
    url: "https://www.apobiologix.com/",
    status: "Already built",
    province: "ON",
    city: "Etobicoke",
    address: null,
    specialization: "Generics & biosimilars",
    scale: "Thousands of employees",
    notes: "Canada's largest generic pharma company",
    lat: 43.6205,
    lng: -79.5132,
  },
  {
    name: "Aramis Biotechnologies",
    url: "https://aramisbiotechnologies.com/en/",
    status: "Being built",
    province: "QC",
    city: "Quebec City",
    address: null,
    specialization: "Plant-based biologics & vaccines",
    scale: "SIF-supported, expansion underway",
    notes: "New vaccine platform based on plant systems",
    lat: 46.817497,
    lng: -71.206921,
  },
  {
    name: "Aspect Biosystems",
    url: "https://www.ic.gc.ca/eic/site/125.nsf/eng/home",
    status: "Being built",
    province: "BC",
    city: "Vancouver",
    address: null,
    specialization: "3D bioprinting of human tissues for therapeutics development",
    scale: null,
    notes: null,
    lat: 49.290126,
    lng: -123.132544,
  },
  {
    name: "AtomVie Global Radiopharma",
    url: "https://www.atomvie.com/",
    status: "Already built",
    province: "ON",
    city: "Hamilton",
    address: null,
    specialization: "Radiopharmaceuticals for oncology diagnostics and therapeutics; production of short-lived isotopes and cold kits.",
    scale: "Hamilton-based manufacturing + global distribution; spun out of McMaster radioisotope work.",
    notes: null,
    lat: 43.263040,
    lng: -79.866345,
  },
  {
    name: "BIOVECTRA",
    url: "https://www.biovectra.com/facilities/",
    status: "Being built",
    province: "PE",
    city: "Charlottetown",
    address: null,
    specialization: "CDMO with capabilities in small molecules (APIs), complex chemistry, and microbial/biologic fermentation (including mRNA/pDNA). Offers process development, pilot-to-commercial scale production, formulation, analytical testing, and aseptic fill–finish. Utilizes both stainless-steel and single-use fermenters, including 100 L–17,000 L scales. Recognized for excellence in biologics with the 2025 Outsourced Pharma CDMO Leadership Award.",
    scale: "Operates 5 GMP facilities in Atlantic Canada: Charlottetown (4 sites), Windsor NS (biologics), totalling ~25,000 m². Fermentation capacity: ~118,000 L chemical reactors, 64,000 L bioreactors. Active workforce of 550+ employees, part of Agilent since acquisition.",
    notes: null,
    lat: 46.246881,
    lng: -63.129244,
  },
  {
    name: "Bausch Health",
    url: "https://www.bauschhealth.com/",
    status: "Already built",
    province: "QC",
    city: "Laval",
    address: null,
    specialization: "Pharmaceuticals: R&D, formulation, clinical manufacturing, fill-finish, OTC packaging",
    scale: "~338,000 ft²",
    notes: "Corporate HQ; co-located R&D and manufacturing; exports ~70% of production; serves global markets .",
    lat: 45.602766,
    lng: -73.720668,
  },
  {
    name: "Bausch Health (Steinbach Site; formerly Biovail)",
    url: "https://www.bauschhealth.com/",
    status: "Already built",
    province: "MB",
    city: "Steinbach",
    address: null,
    specialization: "Oral solid dosage: controlled-release tablets/capsules",
    scale: "~241,000 ft²; ~1.2 billion tablets/capsules produced annually across ~12 products",
    notes: "Full-service pharma manufacturing; ~500 employees; operates 24/5 with some weekend shifts; major North American production hub .",
    lat: 53.898064,
    lng: -98.862922,
  },
  {
    name: "Baxter",
    url: "https://www.baxter.com/",
    status: "Already built",
    province: "ON",
    city: "Alliston",
    address: null,
    specialization: "Medication Delivery",
    scale: null,
    notes: null,
    lat: 44.1546,
    lng: -79.8662,
  },
  {
    name: "BioAccelerator",
    url: "https://peibioalliance.com/bioaccelerator/",
    status: "Already built",
    province: "PE",
    city: "Charlottetown",
    address: null,
    specialization: "Bioscience scale-up center for Atlantic Canada",
    scale: null,
    notes: null,
    lat: 46.246540,
    lng: -63.128611,
  },
  {
    name: "Biodextris",
    url: "https://www.biodextris.com/",
    status: "Being built",
    province: "QC",
    city: "Laval",
    address: null,
    specialization: "Analytical and process development for vaccines/biologics, manufacturing services of prokaryote and eukaryote-derived proteins",
    scale: null,
    notes: null,
    lat: 45.613971,
    lng: -73.706886,
  },
  {
    name: "Biologics Manufacturing Centre (NRC)",
    url: "https://bmc-cppb.ca/",
    status: "Already built",
    province: "QC",
    city: "Montreal",
    address: null,
    specialization: "Biologics (vaccines, proteins)",
    scale: "~2M doses/month",
    notes: "Publicly funded, end-to-end GMP vaccine capacity",
    lat: 45.502569,
    lng: -73.555945,
  },
  {
    name: "Biomatik",
    url: "https://www.biomatik.com/",
    status: "Already built",
    province: "ON",
    city: "Kitchener",
    address: null,
    specialization: "Biologics contract manufacturer of proteins, antibodies, plasmids, and enzymes for life science research.",
    scale: "Located in Kitchener, ON; employs ~50–70 staff; focused on preclinical and research-grade production.",
    notes: null,
    lat: 43.448685,
    lng: -80.491251,
  },
  {
    name: "Biotherapeutics Manufacturing Centre",
    url: "https://www.ohri.ca/bmc/",
    status: "Already built",
    province: "ON",
    city: "Ottawa",
    address: null,
    specialization: null,
    scale: null,
    notes: null,
    lat: 45.4015,
    lng: -75.6418,
  },
  {
    name: "C3i Center",
    url: "https://c3icenter.com/",
    status: "Already built",
    province: "QC",
    city: "Montreal",
    address: null,
    specialization: "Canada’s only fully validated cGMP cell & gene therapy CDMO, covering cell-line development through commercial manufacture, including viral vector and master cell bank production",
    scale: "37,000 ft² facility with 14 cleanrooms; FDA/EMA/Health Canada compliant; commercial capacity.",
    notes: null,
    lat: 45.506610,
    lng: -73.578200,
  },
  {
    name: "Canadian Critical Drug Initiative",
    url: "https://appliedpharma.ca/ccdi-growing-the-life-sciences-industry/",
    status: "Being built",
    province: "QC",
    city: "Montreal",
    address: null,
    specialization: null,
    scale: null,
    notes: "Federal-funded multi-site initiative for critical medicines manufacturing. Montreal node — see also the Critical Medicines Production Centre at the U Alberta Research Park for the Edmonton site.",
    lat: 45.495170,
    lng: -73.572355,
  },
  {
    name: "CellCarta",
    url: "https://cellcarta.com/",
    status: "Already built",
    province: "QC",
    city: "Montreal",
    address: null,
    specialization: "Biomarker & specialty lab services",
    scale: "International sites",
    notes: "Precision medicine support",
    lat: 45.491615,
    lng: -73.573713,
  },
  {
    name: "Contract Pharmaceuticals",
    url: null,
    status: null,
    province: "ON",
    city: "Mississauga",
    address: null,
    specialization: "Custom synthesis and manufacturing of active pharmaceutical ingredients (APIs) and intermediates.",
    scale: "small-mid scale with niche chemical synthesis expertise.",
    notes: null,
    lat: 43.577467,
    lng: -79.633802,
  },
  {
    name: "Contract Pharmaceuticals Ltd. (CPL)",
    url: "https://cplltd.com/",
    status: "Already built",
    province: "ON",
    city: "Mississauga",
    address: null,
    specialization: "Liquids & semi-solids (CDMO)",
    scale: "~300 employees",
    notes: "Focus on non-sterile manufacturing",
    lat: 43.579424,
    lng: -79.649429,
  },
  {
    name: "Corealis Pharma",
    url: "https://www.corealispharma.com/",
    status: "Already built",
    province: "QC",
    city: "Laval",
    address: null,
    specialization: "Contract Oral Dosage Forms",
    scale: null,
    notes: null,
    lat: 45.609856,
    lng: -73.715644,
  },
  {
    name: "Dalton Pharma Services",
    url: "https://www.dalton.com/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: null,
    specialization: "Specialized CDMO for medical isotopes (PET/SPECT), radiochemistry, and API services.",
    scale: "Canadian operations with small-scale facilities supporting nuclear medicine supply chains.",
    notes: null,
    lat: 43.650084,
    lng: -79.390172,
  },
  {
    name: "Delpharm",
    url: "https://www.delpharm.com/en/",
    status: "Already built",
    province: "QC",
    city: "Boucherville",
    address: null,
    specialization: "Contract Manufacturing",
    scale: "Multiple global plants; Canadian presence supports packaging and API fill-finish; mid-large facility.",
    notes: null,
    lat: 52.869993,
    lng: -73.418104,
  },
  {
    name: "Emergent Biosolutions",
    url: "https://www.emergentbiosolutions.com/",
    status: "Already built",
    province: "MB",
    city: "Winnipeg",
    address: null,
    specialization: "Produces vaccines and antibody therapeutics for infectious diseases and biodefense; products include anthrax vaccine (BioThrax) and opioid antagonist Narcan; active in COVID‑19 vaccine manufacturing",
    scale: "U.S.-based multinational with ~1,600 employees; global manufacturing footprint and high revenue (~USD 1–2 B)",
    notes: null,
    lat: 49.898653,
    lng: -97.135781,
  },
  {
    name: "Entos Pharmaceuticals",
    url: "https://www.entospharma.com/",
    status: "Being built",
    province: "AB",
    city: "Edmonton",
    address: null,
    specialization: "Genetic medicines (DNA vaccines, therapeutics)",
    scale: "~103,000 ft² GMP facility",
    notes: "New R&D + manufacturing site; Genetic medicines and mRNA therapeutics production",
    lat: 53.538207,
    lng: -113.488301,
  },
  {
    name: "Eurofins CDMO",
    url: null,
    status: null,
    province: "ON",
    city: "Mississauga",
    address: null,
    specialization: "Pharmaceutical contract manufacturing under Eurofins Pharma; includes APIs, formulations, biotech.",
    scale: "Canadian branches with small-to-mid scale GMP sites.",
    notes: null,
    lat: 43.598089,
    lng: -79.636140,
  },
  {
    name: "GSK Canada",
    url: "https://ca.gsk.com/en-ca/",
    status: "Already built",
    province: "QC",
    city: "Quebec City",
    address: null,
    specialization: "Flu vaccines",
    scale: "Multi-year supply production",
    notes: "Global flu vaccine production site",
    lat: 46.822128,
    lng: -71.201376,
  },
  {
    name: "Genevant Sciences",
    url: "https://www.genevant.com/",
    status: "Already built",
    province: "BC",
    city: "Vancouver",
    address: null,
    specialization: "Lipid nanoparticle (LNP) platform for mRNA, siRNA, and gene-editing delivery; holds broad LNP IP and is advancing clinical programs in collaboration with companies like Editas",
    scale: "Based in Vancouver; around 50–100 employees",
    notes: null,
    lat: 49.274622,
    lng: -123.123593,
  },
  {
    name: "Genvion",
    url: "https://genvion.ca/",
    status: "Already built",
    province: "MB",
    city: "Winnipeg",
    address: null,
    specialization: null,
    scale: null,
    notes: null,
    lat: 49.906849,
    lng: -97.135040,
  },
  {
    name: "Groupe PARIMA",
    url: "http://groupeparima.com/",
    status: "Already built",
    province: "QC",
    city: "Montreal",
    address: null,
    specialization: "Non-sterile semi-solids, liquids, suspensions CDMO; product development, validation, QC, analytical testing",
    scale: "67,000 ft² modern facility; serving ~30+ global markets; inspected by FDA, EMA, TMMDA, HC.",
    notes: null,
    lat: 45.503067,
    lng: -73.562869,
  },
  {
    name: "ImmunoPrecise Antibodies",
    url: "https://www.ipatherapeutics.com/",
    status: "Already built",
    province: "BC",
    city: "Victoria",
    address: null,
    specialization: "Custom antibody discovery, engineering, and production services (murine/human antibodies, CAR-T reagents).",
    scale: "~200 employees; two Canadian facilities (Victoria, BC & Montréal, QC); publicly traded (TSX:IPA).",
    notes: null,
    lat: 48.421897,
    lng: -123.376830,
  },
  {
    name: "Jubilant HollisterStier",
    url: "https://www.jublhs.com/",
    status: "Being built",
    province: "QC",
    city: "Kirkland",
    address: null,
    specialization: "Canadian-based sterile injectable and vaccine fill-and-finish CDMO; multiple GMP lines; capacity scaled for pandemic and seasonal vaccines. Operates in Kirkland, QC (fill–finish), and elsewhere",
    scale: null,
    notes: null,
    lat: 52.884536,
    lng: -73.618778,
  },
  {
    name: "Laboratoires Confab",
    url: "https://confab.com/",
    status: "Already built",
    province: "QC",
    city: "Longueuil",
    address: null,
    specialization: "Oral/Topical dosage manufacturing (CDMO)",
    scale: "~300 employees",
    notes: "Non-sterile commercial-scale facility",
    lat: 52.853195,
    lng: -73.416227,
  },
  {
    name: "Liminal BioSciences",
    url: "https://liminalbiosciences.com/",
    status: "Already built",
    province: "QC",
    city: "Laval",
    address: null,
    specialization: "Plasma-derived therapeutics",
    scale: "Publicly traded",
    notes: "Focus on fibrosis and liver diseases",
    lat: 45.615633,
    lng: -73.716848,
  },
  {
    name: "Medicago (now defunct)",
    url: null,
    status: null,
    province: "QC",
    city: "Quebec City",
    address: null,
    specialization: "Plant-based vaccines",
    scale: "Former COVID vaccine developer",
    notes: "Ceased operations in 2023 due to funding / market issues",
    lat: 46.809280,
    lng: -71.218610,
  },
  {
    name: "Moderna Canada",
    url: null,
    status: null,
    province: "QC",
    city: "Laval",
    address: null,
    specialization: "mRNA vaccines",
    scale: "~100M doses/year (expandable)",
    notes: "New facility, pandemic preparedness focus",
    lat: 45.615672,
    lng: -73.701673,
  },
  {
    name: "NanoVation Therapeutics",
    url: "https://nanovationtx.com/",
    status: "Already built",
    province: "BC",
    city: "Vancouver",
    address: null,
    specialization: "Develops next-gen lipid nanoparticle (LNP) platforms for nucleic-acid delivery targeting extrahepatic tissues, including proprietary long-circulating LNP (lcLNP™) technology that enhances potency, safety, and stability of gene medicines",
    scale: "team of lipid chemists and RNA specialists; focused on preclinical development and partnerships",
    notes: null,
    lat: 49.286431,
    lng: -123.123205,
  },
  {
    name: "Norgen Biotek",
    url: "https://norgenbiotek.com/",
    status: "Already built",
    province: "ON",
    city: "Hamilton",
    address: null,
    specialization: "Products for sample collection, sample preparation and sample detection. Comprehensive research services",
    scale: null,
    notes: null,
    lat: 43.265649,
    lng: -79.872088,
  },
  {
    name: "Northern RNA",
    url: "https://northernrna.com/",
    status: "Being built",
    province: "AB",
    city: "Calgary",
    address: null,
    specialization: "RNA raw material production",
    scale: "Regional capacity building",
    notes: "Part of Alberta's RNA supply chain",
    lat: 51.039057,
    lng: -114.077981,
  },
  {
    name: "Novel Bio",
    url: "https://www.novel-bio.com/",
    status: "Already built",
    province: "ON",
    city: "Whitby",
    address: null,
    specialization: "Plasmid DNA Production",
    scale: null,
    notes: null,
    lat: 43.8975,
    lng: -78.9428,
  },
  {
    name: "Novocol Pharma",
    url: null,
    status: null,
    province: "ON",
    city: "Burlington",
    address: null,
    specialization: "Sterile injectable CDMO with fill-finish capabilities.",
    scale: null,
    notes: null,
    lat: 43.3200,
    lng: -79.7950,
  },
  {
    name: "NuBiyota Headquarters / R&D",
    url: "https://nubiyota.com/",
    status: "Already built",
    province: "ON",
    city: "Guelph",
    address: null,
    specialization: "Microbiome R&D, donor screening, strain banking",
    scale: "Not publicly disclosed — dedicated lab space",
    notes: "Hosts core MET platform development; origin site licensed from University of Guelph .",
    lat: 43.546830,
    lng: -80.238652,
  },
  {
    name: "OmniaBio",
    url: "https://omniabio.com/",
    status: "Already built",
    province: "ON",
    city: "Hamilton",
    address: null,
    specialization: "Full-service CGT (cell & gene therapy) CDMO offering end-to-end capabilities—from process development to large-scale clinical and commercial manufacturing.  Integrates AI, robotics, and closed‑unit systems for lentiviral, autologous/allogeneic cell therapies, iPSC, and viral vectors.  Offers development & analytical services with GMP compliance across FDA, EMA, and Health Canada.",
    scale: "Canada’s largest CGT-focused CDMO. Hamilton, ON: 120,000 ft² (now expanded to ~160,000 ft²) intelligent factory at McMaster Innovation Park, with 26 clean rooms and AI/automation workflows. Launched October 2024, employing ~250 staff with >$580 M investment backed by Invest Ontario.  Toronto site at MaRS Discovery District: ~10 ISO Class 7 clean rooms with development and GMP suites",
    notes: null,
    lat: 43.267641,
    lng: -79.870871,
  },
  {
    name: "O’Hara Technologies Manufacturing Plant",
    url: "https://www.oharatech.com/",
    status: "Already built",
    province: "ON",
    city: "Richmond Hill",
    address: null,
    specialization: "Design & fabrication of solid-dosage processing equipment (tablet coaters, dryers, granulators, blenders)",
    scale: "~65,000 ft² production floor.",
    notes: "Houses metal fabrication, welding, assembly, instrumentation teams; outputs range from lab-scale to high-volume continuous systems. Built to ISO + GMP/cGMP + CE standards.",
    lat: 43.8828,
    lng: -79.4403,
  },
  {
    name: "PBG BioPharma",
    url: "https://www.pbgbiopharma.com/",
    status: "Already built",
    province: "AB",
    city: "PBG BioPharma",
    address: null,
    specialization: "Biotech Contract Manufacturing",
    scale: null,
    notes: null,
    lat: 53.816195,
    lng: -116.538266,
  },
  {
    name: "PCI Pharma Services",
    url: "https://pci.com/",
    status: "Already built",
    province: "ON",
    city: "Burlington",
    address: null,
    specialization: "Full-service pharma services: clinical/commercial manufacturing, packaging, cold chain, serialization.",
    scale: "Mid-to-large operations in Canada, including site in Brantford, ON and Vancouver, BC; part of global PCI group.",
    notes: null,
    lat: 43.3300,
    lng: -79.8050,
  },
  {
    name: "Patheon",
    url: "https://www.patheon.com/us/en/home.html",
    status: "Already built",
    province: "ON",
    city: "Whitby",
    address: null,
    specialization: "Full-service CDMO: small-molecule APIs, biologics, viral vectors, plasmids, formulations, clinical logistics, and packaging",
    scale: "Multinational, widely spread",
    notes: null,
    lat: 43.9020,
    lng: -78.9470,
  },
  {
    name: "Pharma Medica Research",
    url: "https://www.pharmamedica.com/",
    status: "Already built",
    province: "ON",
    city: "Mississauga",
    address: null,
    specialization: "Bioanalytics, clinical trials, CDMO",
    scale: "250–500 employees",
    notes: "Full-service clinical CRO + labs",
    lat: 43.578525,
    lng: -79.646941,
  },
  {
    name: "Pillar5 Pharma",
    url: "https://pillar5pharma-anjac.com/",
    status: "Already built",
    province: "ON",
    city: "Arnprior",
    address: null,
    specialization: "Contract Everything",
    scale: "small to mid-scale.",
    notes: null,
    lat: 45.4339,
    lng: -76.3463,
  },
  {
    name: "Qeen Biotechnologies",
    url: "https://qeen-bio.com/",
    status: "Already built",
    province: "QC",
    city: "Gatineau",
    address: null,
    specialization: "Bacteriophages",
    scale: null,
    notes: null,
    lat: 53.081224,
    lng: -73.440866,
  },
  {
    name: "Resilience",
    url: "https://resilience.com/",
    status: "Already built",
    province: "ON",
    city: "Mississauga",
    address: null,
    specialization: "Biomanufacturing",
    scale: null,
    notes: null,
    lat: 43.577276,
    lng: -79.638803,
  },
  {
    name: "Resonetics",
    url: "https://resonetics.com/",
    status: "Already built",
    province: "BC",
    city: "Surrey",
    address: null,
    specialization: "Contract Medical Device Manufacturing & Development",
    scale: null,
    notes: null,
    lat: 53.781213,
    lng: -127.636509,
  },
  {
    name: "STEMCELL Technologies",
    url: "https://www.stemcell.com/",
    status: "Being built",
    province: "BC",
    city: "Burnaby",
    address: null,
    specialization: "Cell therapy tools, GMP reagents",
    scale: ">1,000 jobs",
    notes: "Largest Canadian biotech, expanding cell/gene therapy tools",
    lat: 49.239477,
    lng: -122.982066,
  },
  {
    name: "Sanofi Pasteur",
    url: "https://www.sanofi.ca/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "1755 Steeles Ave W, North York, ON M2R 3T4",
    specialization: "Vaccines (influenza + pediatric/adult) — drug substance + fill-finish; pandemic-preparedness expansion underway.",
    scale: "Canada's largest vaccine plant; ~1,225 jobs. New $431M facility opened May 2024; second flu/pandemic plant under construction (expected 2027). $1B+ campus investment.",
    notes: "Sanofi Pasteur Connaught Campus — descended from Connaught Labs (founded 1914). One of the world's longest continuously operating vaccine manufacturers.",
    lat: 43.7847,
    lng: -79.4682,
  },
  {
    name: "StarFish Medical",
    url: "https://starfishmedical.com/",
    status: "Already built",
    province: "BC",
    city: "Victoria",
    address: null,
    specialization: "Contract Medical Device Manufacturing & Development",
    scale: null,
    notes: null,
    lat: 48.422804,
    lng: -123.362217,
  },
  {
    name: "Teva canada",
    url: "https://www.tevacanada.com/en/about-teva/manufacturing-facilities/",
    status: "Already built",
    province: "ON",
    city: "Whitchurch-Stouffville",
    address: "30 Novopharm Ct, Scarborough, ON M1B 2K9",
    specialization: null,
    scale: null,
    notes: null,
    lat: 43.9711,
    lng: -79.2452,
  },
  {
    name: "Therapure Biopharma",
    url: "https://www.therapurebio.com/",
    status: "Already built",
    province: "ON",
    city: "Mississauga",
    address: null,
    specialization: "Protein therapeutics, CDMO services",
    scale: "~130,000 ft², ~300 employees",
    notes: "Advanced protein process development",
    lat: 43.598020,
    lng: -79.649779,
  },
  {
    name: "Virogen Biotechnology",
    url: "https://www.virogen.com/",
    status: "Already built",
    province: "BC",
    city: "Richmond",
    address: null,
    specialization: "Antigens and Antibodies",
    scale: null,
    notes: null,
    lat: 49.176503,
    lng: -123.124708,
  },
  {
    name: "Viva Pharmaceutical",
    url: "https://www.vivapharm.com/",
    status: "Already built",
    province: "BC",
    city: "Richmond",
    address: null,
    specialization: "Custom Manufacturing",
    scale: "Largest GMP cert facility in BC: ~52,000 ft² on 73,000 ft² site; Health Canada & FDA licensed; halal certified",
    notes: null,
    lat: 49.161763,
    lng: -123.130265,
  },
  {
    name: "Zymeworks",
    url: "https://www.zymeworks.com/",
    status: "Already built",
    province: "BC",
    city: "Vancouver",
    address: null,
    specialization: "Bispecific antibodies, protein therapeutics",
    scale: "~275 employees",
    notes: "Public company, innovative biologics platform",
    lat: 49.285315,
    lng: -123.129032,
  },
  {
    name: "uBriGene",
    url: "https://www.ubrigene.com/",
    status: "Already built",
    province: "BC",
    city: "Richmond",
    address: null,
    specialization: "Cell & Gene Therapy CDMO",
    scale: null,
    notes: null,
    lat: 49.166614,
    lng: -123.141312,
  },

  // ─── 2026-05-26 web-scan additions ─────────────────────────────
  //
  // Pulled from a web research pass across BIOTECanada's directory,
  // ISED's Biomanufacturing Projects page, adMare BioInnovations
  // portfolio, BioCanRx affiliates, and individual company sites.
  // Deduplicated against the original xlsx import — entries here are
  // sites that weren't in the source spreadsheet. lat/lng use the
  // city center with small jitter for multi-tenant addresses so the
  // dots don't overlap on the map.
  {
    name: "BlueRock Therapeutics",
    url: "https://www.bluerocktx.com/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "MaRS Discovery District, 661 University Ave, Toronto, ON M5G 1M1",
    specialization: "iPSC-derived engineered cell therapies (neurology + ophthalmology) with in-house GMP manufacturing.",
    scale: "Bayer subsidiary; ~14,000 sq ft pilot GMP facility plus expanded R&D/manufacturing hub in MaRS.",
    notes: "Co-located with McEwen Institute and CCRM in MaRS.",
    lat: 43.6605,
    lng: -79.3880,
  },
  {
    name: "CCRM (Centre for Commercialization of Regenerative Medicine)",
    url: "https://www.ccrm.ca/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "661 University Ave, Suite 1002, Toronto, ON M5G 0B7",
    specialization: "Public-private CDMO + translation hub for cell & gene therapy; GMP process + analytical development.",
    scale: "Hosts cGMP suites in MaRS; parent of OmniaBio; 100+ staff.",
    notes: "Hosted by University of Toronto in MaRS Centre.",
    lat: 43.6595,
    lng: -79.3886,
  },
  {
    name: "Sunnybrook Centre — GMP Facility",
    url: "https://sunnybrook.ca/research/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "2075 Bayview Ave, Toronto, ON M4N 3M5",
    specialization: "Academic-hospital GMP cleanroom suites for cell therapy / CAR-T / vector processing.",
    scale: "Four classified cleanrooms for cell isolation, expansion and banking.",
    notes: "Sunnybrook Research Institute GMP facility — bridge to clinical translation.",
    lat: 43.7228,
    lng: -79.3756,
  },
  {
    name: "Fusion Pharmaceuticals (AstraZeneca)",
    url: "https://fusionpharma.com/",
    status: "Already built",
    province: "ON",
    city: "Hamilton",
    address: "270 Longwood Rd S, Hamilton, ON L8P 0A6",
    specialization: "Radiopharmaceutical manufacturing — targeted alpha therapies (TATs) for oncology.",
    scale: "Acquired by AstraZeneca in 2024 for $2.4B; commercial-scale radiopharmaceutical facility opened May 2023.",
    notes: "Clinical-stage radioconjugate developer with in-house GMP facility.",
    lat: 43.2557,
    lng: -79.8711,
  },
  {
    name: "Centre for Probe Development and Commercialization (CPDC)",
    url: "https://cpdc.ca/",
    status: "Already built",
    province: "ON",
    city: "Hamilton",
    address: "McMaster Nuclear Research Bldg, 1280 Main St W, Hamilton, ON L8S 4K1",
    specialization: "Radiopharmaceutical CDMO — GMP manufacturing + global distribution of diagnostic and therapeutic radioligands.",
    scale: "FDA-cleared radiopharmaceutical manufacturing facility at McMaster.",
    notes: "Centre of Excellence for Commercialization and Research; not-for-profit.",
    lat: 43.2607,
    lng: -79.9192,
  },
  {
    name: "Eli Lilly (POINT Biopharma) Toronto",
    url: "https://www.lilly.com/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "4850 Keele St, Toronto, ON M3J 3K1",
    specialization: "Radioligand therapy R&D and pilot manufacturing for oncology.",
    scale: "Lilly subsidiary following $1.4B POINT Biopharma acquisition; Toronto R&D + pilot manufacturing site.",
    notes: "Complements Lilly's main Indianapolis production campus.",
    lat: 43.7745,
    lng: -79.5045,
  },
  {
    name: "Pharmascience",
    url: "https://www.pharmascience.com/",
    status: "Already built",
    province: "QC",
    city: "Candiac",
    address: "100 Industrial Blvd, Candiac, QC J5R 1J1",
    specialization: "Sterile injectables CDMO (vials, prefilled syringes); new biologics-capable CDMO business unit.",
    scale: "Largest Canadian-owned pharma; $120M Candiac expansion to >20M units/year by 2026.",
    notes: "New CDMO business unit serving biotech and complex injectable customers.",
    lat: 45.3823,
    lng: -73.5167,
  },
  {
    name: "Sterinova",
    url: "https://sterinova.com/",
    status: "Already built",
    province: "QC",
    city: "Saint-Hyacinthe",
    address: "5905 Rue Martineau, Saint-Hyacinthe, QC J2R 0A4",
    specialization: "Ready-to-use sterile injectables (syringes, premix containers) + biologics fill-finish.",
    scale: "67,000 sq ft Health Canada + FDA-inspected facility; ~100 staff.",
    notes: "B.Braun subsidiary; Quebec-based aseptic manufacturing.",
    lat: 45.6066,
    lng: -72.9582,
  },
  {
    name: "Prometic Bioproduction (Kedrion)",
    url: "https://www.prometicbio.com/",
    status: "Already built",
    province: "QC",
    city: "Laval",
    address: "440 Boul Armand-Frappier, Laval, QC H7V 4B4",
    specialization: "Plasma-derived therapeutics (Ryplazim) + GMP bioprocess for purified plasma proteins.",
    scale: "~130 employees in Laval; acquired by Kedrion 2021.",
    notes: "Patented chromatographic plasma purification platform.",
    lat: 45.5560,
    lng: -73.7438,
  },
  {
    name: "VIDO — Vaccine & Infectious Disease Organization",
    url: "https://www.vido.org/",
    status: "Already built",
    province: "SK",
    city: "Saskatoon",
    address: "120 Veterinary Rd, Saskatoon, SK S7N 5E3",
    specialization: "BSL-3 vaccine R&D + GMP biomanufacturing for human and animal vaccines; up to 40M doses/year.",
    scale: "World-class BSL-3 facility at University of Saskatchewan.",
    notes: "Vaccine Development Centre — one of only a few GMP CL3 biomanufacturing facilities globally.",
    lat: 52.1325,
    lng: -106.6304,
  },
  {
    name: "Providence Therapeutics",
    url: "https://providencetherapeutics.com/",
    status: "Already built",
    province: "AB",
    city: "Calgary",
    address: "8500 Macleod Trail SE, Calgary, AB T2H 2N1",
    specialization: "mRNA vaccine developer with in-house GMP mRNA + LNP production for clinical trials.",
    scale: "Canada's leading mRNA vaccine company; operations in Calgary and Toronto.",
    notes: "Lead asset PTX-COVID19-B; partnered with Emergent (Winnipeg) for commercial scale-up.",
    lat: 51.0289,
    lng: -114.0708,
  },
  {
    name: "Symvivo Corporation",
    url: "https://symvivo.com/",
    status: "Already built",
    province: "BC",
    city: "Burnaby",
    address: "102 - 4475 Wayburne Dr, Burnaby, BC V5G 4X4",
    specialization: "Bacterial-based gene delivery platform (bacTRL); oral biotherapeutics for cancer and infectious disease.",
    scale: "Small-mid biotech; NRC IRAP supported.",
    notes: "Lead candidate bacTRL-Spike COVID-19 oral vaccine.",
    lat: 49.2516,
    lng: -122.9990,
  },
  {
    name: "PnuVax",
    url: "https://www.pnuvax.com/",
    status: "Already built",
    province: "QC",
    city: "Montreal",
    address: "6100 Royalmount Ave, Montreal, QC H4P 2R2",
    specialization: "Contract biomanufacturing of vaccines and biopharmaceuticals using process intensification.",
    scale: "Montreal facility on former NRC land; multi-product capable.",
    notes: "Specializes in scalable, low-cost biomanufacturing.",
    lat: 45.5050,
    lng: -73.6580,
  },
  {
    name: "Inspire Bio Innovations",
    url: "https://inspirelabs.ca/",
    status: "Being built",
    province: "QC",
    city: "Montreal",
    address: "3650 Saint-Urbain St, Montreal, QC H2X 2P4",
    specialization: "Life-sciences hub + shared lab + GMP-ready space for biotech tenants (CellCarta HQ anchor, Ability Biotherapeutics).",
    scale: "Phase 1 completed summer 2025; Phase 2 expected 2026.",
    notes: "Built on former Montreal Chest Institute site.",
    lat: 45.5121,
    lng: -73.5710,
  },
  {
    name: "Ability Biotherapeutics",
    url: "https://www.ability.bio/",
    status: "Being built",
    province: "QC",
    city: "Montreal",
    address: "Inspire Bio Innovations, 3650 Saint-Urbain St, Montreal, QC H2X 2P4",
    specialization: "Targeted antibody therapeutics — next-generation biotherapeutic targeting platform.",
    scale: "Quebec biotech moving into Phase 2 at Inspire Bio.",
    notes: "Backed by Jadco Group.",
    lat: 45.5124,
    lng: -73.5704,
  },
  {
    name: "Repare Therapeutics",
    url: "https://www.reparerx.com/",
    status: "Already built",
    province: "QC",
    city: "Saint-Laurent",
    address: "7210 Rue Frederick-Banting, Saint-Laurent, QC H4S 2A1",
    specialization: "Precision oncology / synthetic lethality drug discovery + pilot biologics R&D.",
    scale: "~150 staff; clinical-stage pipeline.",
    notes: "SNIPRx CRISPR-enabled discovery platform.",
    lat: 45.5102,
    lng: -73.7405,
  },
  {
    name: "Inversago Pharma (Novo Nordisk)",
    url: "https://inversago.com/",
    status: "Already built",
    province: "QC",
    city: "Montreal",
    address: "400-1000 Sherbrooke St W, Montreal, QC H3A 3G4",
    specialization: "Peripherally acting CB1 receptor blocker biotherapeutics for metabolic and fibrotic diseases.",
    scale: "adMare-built portfolio company; acquired by Novo Nordisk 2023.",
    notes: "Pioneer in peripheral CB1 blockade.",
    lat: 45.5043,
    lng: -73.5783,
  },
  {
    name: "Sernova Biotherapeutics",
    url: "https://sernova.com/",
    status: "Already built",
    province: "ON",
    city: "London",
    address: "700 Collip Cir, London, ON N6G 4X8",
    specialization: "Implantable Cell Pouch System (bio-hybrid organ) for type 1 diabetes; cell therapy combination products.",
    scale: "Clinical-stage regenerative medicine; partnered with Evotec for iPSC islets.",
    notes: "Research Park facility at Western University.",
    lat: 43.0098,
    lng: -81.2773,
  },
  {
    name: "BioLyse Pharma",
    url: "https://biolyse.ca/",
    status: "Already built",
    province: "ON",
    city: "St. Catharines",
    address: "11 Burford Crt, St. Catharines, ON L2N 7G7",
    specialization: "Cytotoxic and oncology drug manufacturing (paclitaxel); biotech and gene therapy services.",
    scale: "Integrated GMP facility; ~29 staff.",
    notes: "Privately held Canadian oncology drug manufacturer.",
    lat: 43.1594,
    lng: -79.2469,
  },
  {
    name: "Edesa Biotech",
    url: "https://edesabiotech.com/",
    status: "Already built",
    province: "ON",
    city: "Markham",
    address: "100 Spy Court, Markham, ON L3R 5H6",
    specialization: "Monoclonal antibody therapeutics for inflammatory and immune disease (EB05 program).",
    scale: "Clinical-stage biopharma; ISED-supported COVID/ARDS programs.",
    notes: "Public on NASDAQ; pipeline includes anti-TLR4 mAb.",
    lat: 43.8762,
    lng: -79.3375,
  },
  {
    name: "PlantForm Corporation",
    url: "https://www.plantformcorp.com/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "MaRS Discovery District, 101 College St, Toronto, ON M5G 1L7",
    specialization: "Plant-based (tobacco) production of biosimilar antibodies and recombinant proteins via vivoXPRESS platform.",
    scale: "Greenhouse-contained biomanufacturing; pipeline includes pembrolizumab + ranibizumab biosimilars.",
    notes: "Founded on University of Guelph technology.",
    lat: 43.6605,
    lng: -79.3870,
  },
  {
    name: "Vasomune Therapeutics",
    url: "https://www.vasomune.com/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "MaRS Centre, 101 College St, Toronto, ON M5G 1L7",
    specialization: "Vascular protective biologic peptide therapeutics (Tie2 receptor agonists) — AV-001 program.",
    scale: "Clinical-stage biotech with pilot biologics development.",
    notes: "Made-in-Ontario; ARDS, sepsis indications.",
    lat: 43.6601,
    lng: -79.3865,
  },
  {
    name: "Triumvira Immunologics",
    url: "https://triumvira.com/",
    status: "Already built",
    province: "ON",
    city: "Hamilton",
    address: "175 Longwood Rd S, Hamilton, ON L8P 0A1",
    specialization: "T-cell antigen coupler (TAC) cell therapy for solid tumors; GMP manufacturing via C3i partnership.",
    scale: "Privately held biopharma; clinical Phase 1/2.",
    notes: "Manufacturing through C3i Centre / CETC GMP facility.",
    lat: 43.2570,
    lng: -79.8720,
  },
  {
    name: "IMV Inc.",
    url: "https://www.imv-inc.com/",
    status: "Already built",
    province: "NS",
    city: "Dartmouth",
    address: "130 Eileen Stubbs Ave, Dartmouth, NS B3B 2C4",
    specialization: "DPX lipid-based vaccine and immunotherapy platform (cancer, infectious disease).",
    scale: "Clinical-stage biopharma headquartered in Atlantic Canada.",
    notes: "DPX platform now owned by BioVaxys Technology Corp.",
    lat: 44.6735,
    lng: -63.5752,
  },
  {
    name: "3D BioFibR",
    url: "https://3dbiofibr.com/",
    status: "Already built",
    province: "NS",
    city: "Halifax",
    address: "5 Research Dr, Dartmouth, NS B2Y 4M9",
    specialization: "GMP-grade dry-spun collagen and biopolymer fibres for tissue engineering and regenerative medicine.",
    scale: "Spin-out from Dalhousie; $1.3M NGen scale-up grant.",
    notes: "World's first fully automated commercial collagen fibre manufacturing.",
    lat: 44.6620,
    lng: -63.5687,
  },
  {
    name: "Avivagen",
    url: "https://avivagen.com/",
    status: "Already built",
    province: "ON",
    city: "Ottawa",
    address: "100 Sussex Dr, Ottawa, ON K1A 0R6",
    specialization: "Biologics R&D and oxidized beta-carotene products; manufacturing at NRC partner facilities.",
    scale: "Public on TSXV; HQ at NRC Sussex Dr campus.",
    notes: "Operates from National Research Council partnership facilities.",
    lat: 45.4424,
    lng: -75.7000,
  },
  {
    name: "AbCellera Mission Critical GMP Campus",
    url: "https://www.abcellera.com/",
    status: "Being built",
    province: "BC",
    city: "Vancouver",
    address: "2215 Yukon St, Vancouver, BC V5Y 0A1",
    specialization: "First GMP-certified antibody drug manufacturing in Canada + preclinical antibody development.",
    scale: "$225M federal investment for new biotech campus.",
    notes: "Distinct new campus from AbCellera's existing R&D footprint.",
    lat: 49.2620,
    lng: -123.1018,
  },
  {
    name: "Precision NanoSystems Genetic Medicine Biomanufacturing Centre",
    url: "https://www.precisionnanosystems.com/",
    status: "Already built",
    province: "BC",
    city: "Vancouver",
    address: "1055 Vernon Dr, Vancouver, BC V6A 0G3",
    specialization: "RNA medicine GMP biomanufacturing — mRNA vaccines and LNP-formulated genetic medicines.",
    scale: "75,000 sq ft False Creek Flats site; capacity up to 240M doses/year.",
    notes: "$25.1M federal investment under Strategic Response Fund.",
    lat: 49.2780,
    lng: -123.0843,
  },
  {
    name: "adMare BioInnovations — M4 Innovation Centre",
    url: "https://www.admarebio.com/",
    status: "Already built",
    province: "BC",
    city: "Vancouver",
    address: "110 East 5th Ave, Vancouver, BC V5T 1G7",
    specialization: "Shared wet labs + scale-up biomanufacturing prep space for early-stage life sciences companies.",
    scale: "30,000 sq ft; $16M federal/provincial investment; supports 20+ ventures over 5 years.",
    notes: "Officially opened April 2026 in Mount Pleasant; CASTL training partner.",
    lat: 49.2660,
    lng: -123.1010,
  },
  {
    name: "adMare BioInnovations — UBC Headquarters",
    url: "https://www.admarebio.com/",
    status: "Already built",
    province: "BC",
    city: "Vancouver",
    address: "Pharmaceutical Sciences Bldg, 2405 Wesbrook Mall, Vancouver, BC V6T 1Z3",
    specialization: "National life-sciences accelerator with wet-lab and scale-up capability; Tx Accelerator program.",
    scale: "27 portfolio companies; >$1.4B raised; >900 employees.",
    notes: "Merger of CDRD (Vancouver) and NEOMED (Montréal).",
    lat: 49.2618,
    lng: -123.2462,
  },
  {
    name: "Advanced Therapeutics Manufacturing Facility (ATMF) — UBC",
    url: "https://immunoengineeringhub.ca/programs/atmf/",
    status: "Being built",
    province: "BC",
    city: "Vancouver",
    address: "2329 West Mall, UBC, Vancouver, BC V6T 1Z4",
    specialization: "Clinical-grade GMP biomanufacturing for advanced cell- and gene-based therapies.",
    scale: "First-of-its-kind in Western Canada; cornerstone of Canada's Immunoengineering and Biomanufacturing Hub.",
    notes: "Co-led by BC Cancer scientist Dr. Robert Holt.",
    lat: 49.2606,
    lng: -123.2460,
  },
  {
    name: "BC Cancer — Conconi Family Immunotherapy Lab",
    url: "https://www.bccrc.ca/",
    status: "Already built",
    province: "BC",
    city: "Victoria",
    address: "2410 Lee Ave, Victoria, BC V8R 6V5",
    specialization: "GMP CAR-T cell therapy manufacturing; Made-in-Canada CAR-T platform.",
    scale: "Provincial GMP cleanroom for CAR-T trials.",
    notes: "Part of BC Cancer Research Centre / BioCanRx CAR-T platform.",
    lat: 48.4284,
    lng: -123.3656,
  },
  {
    name: "BC Cancer — Genome Sciences Centre",
    url: "https://www.bcgsc.ca/",
    status: "Already built",
    province: "BC",
    city: "Vancouver",
    address: "675 W 10th Ave, Vancouver, BC V5Z 1L3",
    specialization: "Clinical-grade plasmid manufacturing and genomics for immunotherapy.",
    scale: "GLP plasmid lab supporting CAR-T and gene therapy clinical trials.",
    notes: "Affiliated with BC Cancer / BioCanRx.",
    lat: 49.2629,
    lng: -123.1240,
  },
  {
    name: "Critical Medicines Production Centre (Applied Pharmaceutical Innovation)",
    url: "https://appliedpharma.ca/",
    status: "Being built",
    province: "AB",
    city: "Edmonton",
    address: "Edmonton Research Park, 9504-41 Ave NW, Edmonton, AB T6E 5X1",
    specialization: "Small-molecule API + sterile aseptic fill-finish of traditional and biologic drugs; biologics manufacturing.",
    scale: "83,431 sq ft on 7-acre plot; projected 73.2M doses/year; ~$200M CCDI initiative.",
    notes: "U Alberta partnership with API; Canada's largest critical medicines facility.",
    lat: 53.5085,
    lng: -113.5025,
  },
  {
    name: "Innovotech Labs",
    url: "https://innovotech.ca/",
    status: "Already built",
    province: "AB",
    city: "Edmonton",
    address: "2011 - 94 Street NW, Edmonton, AB T6N 1H1",
    specialization: "GMP + ISO-accredited analytical, microbiological and biofilm/antimicrobial testing services for biologics + pharma.",
    scale: "Publicly traded on TSXV (IOT); Drug Establishment License.",
    notes: "MBEC Assay platform for antimicrobial susceptibility.",
    lat: 53.4980,
    lng: -113.4470,
  },
  {
    name: "CASTL — Charlottetown training facility",
    url: "https://castlcanada.ca/",
    status: "Already built",
    province: "PE",
    city: "Charlottetown",
    address: "550 University Ave, Charlottetown, PE C1A 4P3",
    specialization: "GMP-simulated biomanufacturing training facility — cell culture, fermentation, downstream, fill-finish.",
    scale: "National hub for biomanufacturing workforce training in partnership with adMare.",
    notes: "Located at UPEI; mirrored sites in Montreal and Vancouver.",
    lat: 46.2570,
    lng: -63.1370,
  },
  {
    name: "BIOVECTRA — Windsor (NS)",
    url: "https://www.biovectra.com/",
    status: "Already built",
    province: "NS",
    city: "Windsor",
    address: "70 Wentworth Rd, Windsor, NS B0N 2T0",
    specialization: "Microbial fermentation CDMO — single-use 100 L and 1,000 L fermenters for biologics.",
    scale: "First Canadian CDMO with single-use 1,000 L microbial fermentation; part of Agilent Advanced Therapeutics.",
    notes: "Complements BIOVECTRA's PEI biologics + mRNA campus.",
    lat: 44.9912,
    lng: -64.1357,
  },
  {
    name: "BioPharma Services",
    url: "https://biopharmaservices.com/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "4000 Weston Rd, Toronto, ON M9L 3A2",
    specialization: "Full-service CRO with GLP/GCP bioanalytical, Phase I/IIa, bioequivalence + PET imaging for biologics.",
    scale: "150+ bed clinical research unit; Health Canada + FDA inspected.",
    notes: "Now part of the Eurofins network.",
    lat: 43.7551,
    lng: -79.5421,
  },
  {
    name: "AmacaThera",
    url: "https://www.amacathera.com/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "661 University Ave, Toronto, ON M5G 1M1",
    specialization: "Injectable hydrogel drug-delivery platform for sustained delivery of antibodies, proteins and small molecules.",
    scale: "Toronto biotech; $230M Pacira partnership; AMT-143 in Phase 2.",
    notes: "Based out of MaRS Discovery District.",
    lat: 43.6590,
    lng: -79.3892,
  },
  {
    name: "Avir Pharma",
    url: "http://www.avirpharma.com/",
    status: "Already built",
    province: "QC",
    city: "Blainville",
    address: "660 Boul Industriel, Blainville, QC J7C 3V4",
    specialization: "Specialty pharma with biologics in-licensing and co-development; injectable distribution.",
    scale: "Affiliate of Laboratoire Riva Group (40+ years manufacturing).",
    notes: "Canadian rights for several specialty biologics.",
    lat: 45.6745,
    lng: -73.8821,
  },
  {
    name: "BioSyent Pharma",
    url: "https://www.biosyent.com/",
    status: "Already built",
    province: "ON",
    city: "Mississauga",
    address: "2476 Argentia Rd, Suite 402, Mississauga, ON L5N 6M1",
    specialization: "Specialty pharma in-licensing + commercialization of niche biologics and pharma products.",
    scale: "Public on TSXV; cardiometabolic, endocrinology, women's health.",
    notes: "Health Canada Drug Establishment License.",
    lat: 43.5995,
    lng: -79.7152,
  },
  {
    name: "Bioniche Animal Health (Vetoquinol)",
    url: "https://www.vetoquinol.com/",
    status: "Already built",
    province: "ON",
    city: "Belleville",
    address: "231 Dundas St E, Belleville, ON K8N 1E2",
    specialization: "Veterinary vaccines and biologicals manufacturing.",
    scale: "Acquired by Vetoquinol; Belleville GMP site.",
    notes: "Founded 1979 as Vetrepharm.",
    lat: 44.1628,
    lng: -77.3835,
  },
  {
    name: "Vetio Animal Health",
    url: "https://vetio.com/",
    status: "Already built",
    province: "ON",
    city: "London",
    address: "771 Wharncliffe Rd S, London, ON N6J 2N2",
    specialization: "Veterinary CDMO — soft chews, tablets, liquids, medicated dermatology products.",
    scale: "Global CDMO with sites in Canada, US, UK, Ireland.",
    notes: "Canadian London, Ontario site.",
    lat: 42.9645,
    lng: -81.2620,
  },
  {
    name: "BioVaxys Technology Corp",
    url: "https://www.biovaxys.com/",
    status: "Already built",
    province: "BC",
    city: "Vancouver",
    address: "Suite 200, 1620 W 8th Ave, Vancouver, BC V6J 1V4",
    specialization: "Immunotherapy R&D platform (DPX, HapTenix) for cancer, infectious disease, allergy.",
    scale: "Acquired IMV's DPX platform; clinical-stage.",
    notes: "Public on CSE (BIOV).",
    lat: 49.2640,
    lng: -123.1380,
  },
  {
    name: "OmniaBio — Toronto (MaRS)",
    url: "https://omniabio.com/",
    status: "Already built",
    province: "ON",
    city: "Toronto",
    address: "MaRS Discovery District, 661 University Ave, Toronto, ON M5G 1M1",
    specialization: "Cell & gene therapy CDMO satellite — process + analytical development with GMP suites.",
    scale: "~10 ISO Class 7 cleanrooms with development + GMP suites at MaRS, complementing the Hamilton flagship.",
    notes: "Toronto satellite of OmniaBio's CGT CDMO operations; main site is the McMaster Innovation Park facility in Hamilton.",
    lat: 43.6598,
    lng: -79.3884,
  },
];
