// Single source of truth for changelog content. Both the auto-publish
// helper (lib/changelog/registry.ts, called from /changelog) and the
// scripts/seed-changelog.ts CLI read from this list.
//
// Editing rules:
//   • Append new entries at the TOP with daysAgo: 0.
//   • Treat title as the natural key — once an entry has shipped, edit
//     its body in place rather than creating a duplicate.
//   • Pick visibleTo carefully: ALL for everything user-visible, STAFF
//     for instructor+, ADMINS for admin+.

export const ALL = ["trainee", "evaluating", "employer", "instructor", "admin", "superadmin"];
export const STAFF = ["instructor", "admin", "superadmin"];
export const ADMINS = ["admin", "superadmin"];

export interface ChangelogEntry {
  title: string;
  body: string;
  kind: "feature" | "fix" | "improvement" | "note";
  visibleTo: string[];
  daysAgo: number;
}

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
  {
    title: "AI course summary: edit manually, refine with a prompt, publish with confirmation",
    body: "Three improvements to the course publish-and-summarise loop.\n\n(1) The AI summary card now has three modes for staff. Edit lets you type the summary directly — verbatim save, no AI call. Refine takes the existing summary and a short instruction (e.g. 'make it shorter', 'more technical', 'lead with what learners can do after') and rewrites it. Regenerate still rebuilds from the course's modules and assessments. Three quick-pick example prompts on the Refine view, plus ⌘/Ctrl + Enter to send.\n\n(2) The Publish button now confirms the action with a green toast bottom-centred on the page: 'Course published' + a primary 'Inspect course →' button that opens the trainee view, plus a secondary 'View in catalog' link. Unpublishing shows an amber confirmation. Errors get a rose toast with the server message. Toast auto-dismisses after 8 seconds; or click Dismiss.\n\n(3) The publish API path now returns errors as JSON for the toast to surface — small reliability win.",
    kind: "improvement",
    visibleTo: STAFF,
    daysAgo: 0,
  },
  {
    title: "New Course dialog: add and remove Topic / Delivery / Provider options inline",
    body: "When an admin opens the New Course dialog, the Topic / Delivery / Provider fields now load the canonical option list from /admin/course-filters. Each option appears as a small chip beneath the input — click the × to remove it. Type a custom value and a 'Save' chip appears inline; click it (or hit Enter) to promote it to the canonical list so it shows up as a suggestion everywhere. No more side trip to /admin/course-filters just to add one option for the course you're about to create. Fallback: if the user can't read the admin endpoint, the dialog still works against the static seed lists.",
    kind: "improvement",
    visibleTo: STAFF,
    daysAgo: 0,
  },
  {
    title: "Trainee registration — auto sign-in, password confirm, role + language at signup",
    body: "Eight UX fixes on /register based on the audit:\n\n• Auto sign-in after creating the account — the /login round-trip is gone. New users land directly in /dashboard with their JWT cookie set. A three-step progress card replaces the silent spinner so something visibly happens between click and dashboard.\n• Name is now required (2–80 chars) with an explicit asterisk. Server re-validates so back-channel POSTs can't slip a null name through.\n• Confirm-password field — typing your password twice prevents the lock-out scenario where a typo at signup forces a password reset.\n• Show-password toggle (eye icon) on both password fields. Mobile signup no longer requires typing 8+ chars blind.\n• autoComplete + autoFocus on every field so password managers prompt to save and the cursor lands in the name field on page-load.\n• 'I am a…' dropdown matching the talent-application's seven positions (Master's / PhD / Postdoc / Research Associate / Lab Technician / Industry Professional / Other), persisted to User.jobTitle so the dashboard greeting and AI tagline can use it from minute one.\n• Language picker (8 supported locales) defaulting from navigator.language and persisted to User.locale, so non-English users aren't stuck on the English UI until they discover the switcher.\n• Inline credits explainer ('most courses cost 50–200') so '200 credits to begin' lands with context.\n• Warmer h1 and a slate-blue CTA gradient.\n\nLogin page now honours ?registered=1 + ?email=… from the fallback path: title flips to 'Account created — sign in', a green confirmation banner appears, and the email field pre-fills. The fallback only triggers if auto sign-in fails for some reason (which it shouldn't).",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "New theme: Mist — Apple visionOS-inspired translucent panels",
    body: "A premium glass theme tuned to feel like visionOS, iOS Control Center, and macOS translucent panels — calm, airy, physical. Off-white background with a desaturated blue-gray atmospheric mesh (no chromatic blooms, no neon, no aurora). Cards are translucent with 30px backdrop-blur + 180% saturation; popovers go to 40px. Each panel renders layered shadows: a diffused outer drop (`0 8px 32px rgba(15,23,42,0.10)`), a bright top inset highlight (specular edge), and a barely-there bottom inset for the lower lip. Hairline white borders, large rounded corners (16 / 24 / 32 / 40 px), Apple SF Pro typography with light-to-medium weights, and a subtle SVG noise overlay so panels read as physical material rather than flat gradients. Brand is a desaturated slate-blue picked to recede rather than draw attention. Pick it from the Theme picker at the bottom of the sidebar.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Sandbox accounts: one-click magic-link sign-in (no more copy email + copy password)",
    body: "Spawn a sandbox and you now get a magic-link URL per account: click it (or open in incognito to keep your admin session) and you're signed in instantly as the sandbox employer or trainee. No email to copy, no password to copy, no /login screen. Same pattern as demo workspaces and employer invites. Token is stored on User.magicToken (sandbox + demo accounts only — real accounts can never have one, so a leaked sandbox token can't escalate). Existing sandboxes from before this change show a 'Reset to generate magic link' nudge — one click and they're upgraded.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Talent Application — broader audience options + 12 sample personas",
    body: "Three changes. (1) The 'What best describes your current position' radio is now Master's student / PhD candidate / Postdoctoral Fellow / Research Associate / Lab Technician / Industry Professional / Other — covering the full BioHubNet life-sciences audience instead of collapsing everything into 'Graduate Program'. The 'status and goal' radio gains a third option for working professionals exploring new opportunities. (2) /admin/forms/talent-application has a new 'Reset schema' button that overwrites the live form with the latest source seed — click it once after a deploy that changes options in code. (3) 'Fill with sample' now offers 12 personas instead of 5, spanning masters / PhD / postdoc / research associate / lab technician / industry professional. Every preset fills every non-file field with valid option strings. Personas span U of T, McGill, UBC, Calgary, Western, Université Laval, Manitoba, and Dalhousie, with realistic mixes of citizenship status and French proficiency.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Course form: contrast fix + custom topic / delivery / provider",
    body: "Two issues on the New Course modal: (1) inputs had no background or text colour set, so on dark themes (Nightfall / Hi-Tech / Rosalind) text rendered light on the user-agent's white default — invisible. Switched all inputs / textarea / selects to the standard theme-aware classes (bg-card-solid, text-fg, border-line). (2) Topic / Delivery / Provider were locked-down dropdowns. Now they're input+datalist combos: pick from the curated list (sourced from /admin/course-filters) OR type a custom value. Same change applied to the per-course quick-edit pencil dialog. The bulk-apply dialog keeps its select-only paradigm (it needs a tri-state 'don't change / clear / set').",
    kind: "fix",
    visibleTo: STAFF,
    daysAgo: 0,
  },
  {
    title: "Employer invites: bulk-mint, search/filter, undo revoke, open-tracking, first-run guide",
    body: "A round of UX polish on the magic-link invite system based on the review.\n\nAdmin side (Administration → Experience → Employer invites):\n• Bulk invite — paste up to 100 emails, mint one magic-link per address.\n• Filter chips (All / Pending / Claimed / Expired) and a search box that matches email or company name.\n• Undo revoke — clicking the trash icon kicks off a 5-second client-side window with an Undo toast before the DELETE actually fires.\n• Open count + last-opened display per invite — shows how many times the recipient (or you) has clicked the link.\n• 'Testing' badge auto-applied to invites with @biohubnet.test placeholder emails so you can tell quick-test invites apart from real-prospect ones at a glance.\n\nEmployer side:\n• First-run welcome card on /employer for fresh accounts (no postings, empty profile) with three click-through steps: fill profile → post first internship → review applicants.\n• 'Set a password' banner for users who signed in via magic link and have no password set — prevents the 'locked out when invite expires' trap. Dismissible per session.\n\nExpired / conflict / unknown-link error page now offers two relevant action links per case (e.g. for email conflict: 'Sign in to existing account' OR 'Request a new invite with a different email').",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Sandbox + demo accounts are now hidden from platform stats by default",
    body: "/admin/users now opens on a Real tab (real accounts only) with separate Sandbox and Demo tabs you can flip to. The admin dashboard, system-status page, /admin/analytics, /admin/stats, /admin/newsletter, the public /for-employers and /for-trainees pulse stats, and the recent-logins feed all filter to accountKind='real' so dummy accounts don't pollute the numbers prospects and admins see. System status keeps a small footer line below the vitals (`Plus N sandbox · M demo`) for transparency, with deep links to the dedicated management pages.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Employer HR invites are now magic links — one click, no claim form",
    body: "The signup-link flow is rewritten end-to-end. Recipient clicks the URL, lands in /employer signed in. No name to type, no password to set up front, no claim screen. Magic links are reusable bookmarks until expiry, so partners can come back later from any device. Admins get two new buttons on /admin/employer-invites: Quick invite (zero inputs, mints + auto-copies the URL in one click) and a per-invite Test button that opens the link in a new tab so admins can experience exactly what the recipient experiences. All form fields are now optional. Cross-device password sign-in still works for partners who later set a password from /profile.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Admin Inbox — one place for everything waiting on review",
    body: "New /admin/inbox (Administration → Platform → Inbox) gathers the four streams admins triage: role-change requests, credit applications, pathway-enrolment approvals, and access requests from the public marketing pages. Top of the page shows four lanes with live counts colour-coded by urgency; below, a unified time-ordered feed of the most recent pending items across all four streams, each with a Review link to the existing dedicated page. The individual pages still work — this is the hub, not a replacement.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Admin menu re-balanced: skills moved to Experience, requests live under Platform",
    body: "The Engage / Experience / Platform sub-grouping is tighter now. Engage stays focused on running courses (enrolments, groups, credit apps, pathway enrolments, course filters, certificates). Skill ontology moved to Experience — it's the matching marketplace vocabulary, not a course property. Users / Role requests / Announcements / Newsletter exports moved to Platform alongside the other operations links. The new Inbox sits at the top of Platform.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Administration menu now grouped: Engage · Experience · Platform",
    body: "The Administration sidebar group used to be a long flat list of 20+ links. It's now sub-grouped to mirror the user-facing ENGAGE / EXPERIENCE vocabulary you already see at the top of the sidebar. Engage covers learning content + people management (Users, Enrollments, Groups, Skills, Course filters, Certificates, Announcements, Newsletter exports, Pathway / Credit / Role applications). Experience covers the employer side (Employer invites, Access requests, Sandbox accounts, Demo workspaces). Platform covers operations (Analytics, Reports, Audit Log, plus superadmin-only LTI / System status / Settings). Overview stays as a single link at the top of the section.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Per-admin sandbox accounts — multiple admins can test in parallel",
    body: "Administration → Sandbox accounts (its own page now, not buried in System status) lets each admin spawn their own Employer HR + Trainee pair (idempotent, deterministic emails). The pair comes pre-loaded with a posting and a talent-application submission so the kanban, scoring, and interview flows all light up. Reset wipes and re-seeds; Delete cleans up. You can also see other admins' sandboxes — handy for spotting who's testing what.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "'Fill with sample' chip on long forms (admin-only)",
    body: "Talent Application, internship posting form, employer company profile, and trainee personal info now show a discreet amber 'Fill with sample' chip next to the title — visible only to admin and superadmin. Click for 5 curated presets; pick one and the form populates with realistic biomanufacturing dummy data. Tweak, submit, see the real downstream flow. Ideal for hands-on demos and onboarding new admins.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Demo workspaces — true one-click magic-link sign-in",
    body: "Administration → Demo workspaces lets you mint a magic-link URL for a prospective partner. They click — that's it. The server validates the token, spawns a populated workspace (or looks up their existing one for return visits), mints a NextAuth session scoped to the invite expiry, sets the cookie, and redirects straight to the employer dashboard. No claim form, no name typing, no copy-paste credentials. The link is reusable until expiry, so the prospect can bookmark it and come back. Workspace ships pre-loaded with 3 sample postings, 10 applicants spread across the kanban funnel, scheduled interviews, ratings, and notes. Time-limited (default 7 days); a sweeper deletes everything when the timer runs out.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Sandbox / demo banner — clear visual cue when you're not in real data",
    body: "When you're signed in as a sandbox or demo account, a slim cyan (sandbox) or violet (demo) banner sits at the top of every page so you never confuse 'this is real' with 'this is my dummy.' Demo banner shows a live countdown to expiry.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Skill ontology — the platform now knows what it's teaching, hiring, and learning",
    body: "Every course, internship posting, and trainee profile is now wired to a shared, curated Skill vocabulary. AI extracts skills from course descriptions, posting bodies, talent-application pitches, and (optionally) uploaded resumes. Course completions automatically infer skills onto the trainee's profile with evidence. Aliases and embeddings let synonyms (USP / Upstream Processing / upstream bioprocessing) resolve to the same canonical Skill. Admins curate the vocabulary at Administration → Skill ontology.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "My Skills — your verified skill profile, on every dashboard",
    body: "EXPERIENCE → My Skills lists what BHN knows you can do, with evidence: which course, which line of your resume, or what you self-claimed. Adjust levels, remove a skill, or claim from a curated suggestion list of common biomanufacturing skills employers ask for.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "How you match — skill gap widget on the trainee dashboard",
    body: "Pick any active internship from the new 'How you match' widget on /dashboard and we show your 0–100 match score, the skills you bring (green), the skills you're missing (rose for required, amber for nice-to-have), plus a list of BHN courses that would close the gap. No mystery scoring — every weight is shown.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Applicant kanban with live skill scoring (employer + admin)",
    body: "Open any of your postings → Applicants and you'll find a six-column kanban: New / Reviewing / Shortlisted / Phone screen / Onsite / Offer (with Hired / Rejected / Closed collapsed at the bottom). Each card shows the candidate's match score, top matched skills, completed-BHN-course count, plus a side drawer for notes, 1–5 star rating, and the full skill breakdown.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Interview scheduling — propose time slots in one click",
    body: "From an applicant's drawer in the kanban, click Schedule interview. Propose 1–5 datetime slots, pick a format (video / phone / onsite), drop the meeting link, send. The applicant sees the choice on their /interviews page (also linked from the sidebar) and accepts one or declines. Acceptance auto-stamps Phone screen on the kanban. No external calendar OAuth in v1 — keep an eye on /interviews to see what's confirmed.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Public marketing — /for-employers and /for-trainees",
    body: "BHN Training now has two public, no-auth marketing pages: /for-employers pitches the platform to industry partners with live pulse stats and a sample candidate match; /for-trainees pitches it to learners with a sample skill-gap card. Both have an access-request form that lands in a new admin inbox at Administration → Access requests, where admins approve into a regular employer invite or trainee welcome.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Newsletter sign-up: three options instead of one tick-box",
    body: "Registration now asks 'Yes, sign me up' (default), 'I'm already subscribed', or 'No thanks' — three radio cards, not one checkbox. The middle option stops us from accidentally double-adding existing BioHubNet readers when they make a BHN Training account.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Newsletter exports — admins can copy new sign-ups in one click",
    body: "New page at Administration → Newsletter exports. The 'New to export' tab lists everyone who opted in and hasn't been copied yet. Pick a format (one email per line, CSV with name, or comma-separated), Copy to clipboard, paste into Mailchimp / your ESP, then click 'Mark as exported' — the rows drop off the New tab so you don't double-export them next time. An All tab and per-row 'Re-arm' cover re-running, and the Export history panel shows every previous copy with who did it and how many. Audit-logged automatically.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "AI-written greeting tagline on the dashboard",
    body: "Below 'Hi, {your name}.' on the dashboard hero, a small italic tagline now appears, freshly written by AI for your role and the time of day — quietly warm, occasionally witty, never cringe. The line reads on its own; hover or focus it and a discreet strip fades in below with four chips: Nice (thumbs up), Meh (thumbs down), Retry (regenerate), and Turn off (disable greetings entirely). Cached per browser session so re-navigating doesn't burn fresh AI calls; regenerates each new sign-in. Falls back to a friendly canned line if the AI isn't reachable.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Rosalind theme — parchment, sage, italic serif",
    body: "New theme in the picker, named after Rosalind Franklin (X-ray crystallographer who imaged DNA). Warm oat-parchment background, deep botanical sage as the CTA colour, dusty-rose accent, espresso text. Italic serif headings on a humanist sans body, generous radii, soft warm shadows — herbarium-academic feel without the kitsch. Designed for life-sciences readers who want sophisticated and refined, not pink. Try it from the Theme picker at the bottom of the sidebar.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Stop-viewing-as banner is now impossible to miss",
    body: "When a superadmin is impersonating another role, the top banner now wears a hard amber stripe pattern, a pulsing eye icon, and a high-contrast white-on-espresso 'Stop viewing as · Restore superadmin' button with a 3D shadow that lifts on hover. The old translucent pill was easy to skim past — this one isn't.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Test employer + trainee seed, surfaced in the admin UI",
    body: "Superadmins: open Administration → System status and you'll find a Test data panel. One click stands up the dummy Employer (test.employer@biohubnet.test / test1234), Trainee (test.trainee@biohubnet.test / test1234), an internship posting, and a talent-application submission tying them together. Another click cleans them up. No CLI needed. The panel shows a live status grid (employer / trainee / posting / submission — present or missing) so you can confirm at a glance.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "System status page for superadmins — DB, AI, and security at a glance",
    body: "New /admin/system-status (superadmin-only) gives a one-page read-out of the platform's health. Top card rolls up an overall traffic-light verdict — Database (live ping with millisecond latency), AI provider (failure rate over the last 7 days), Superadmin redundancy (warns if there's only one), and the action queue size. Below it: vitals row (active users, AI calls in 24h, DB ping, build commit), a database row-count grid for the major tables, an AI-usage breakdown by feature for the last 30 days with calls / failures / failure-% / avg latency, and six security signals — privileged accounts, pending role-change requests, idle 90+ days, employer invites, deactivated accounts, sessions. Footer streams the latest role-related audit entries, recent logins (24h), and the audit-log feed. Read-only — no actions, no caching.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Changelog page got a dashboard + timeline view",
    body: "Open /changelog and you'll see a stat panel up top — total entries, this-month / last-30-day counts, days since the last update, by-kind breakdown chips, and a 12-month sparkbar showing release cadence. Below it, entries now flow as a vertical timeline with month sub-headings and a rail of coloured dots, so it's easy to scan how busy a given period was at a glance.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Sidebar group titles now describe the programmes underneath",
    body: "Hover (or focus) the ENGAGE / EXPERIENCE labels in the sidebar — a small popover slides out to the right with BioHubNet's official one-line description and the named programmes inside each track. ENGAGE: industry-led training, workshops, and mentorship — Medical Affairs Learning Pathway (MSL Accelerator with Agilis Health) and Entrepreneurship Learning Pathway. EXPERIENCE: bridging theory and practice — Knowledge Exchange Round 4 (1/4/6-month placements), Talent Application, and Internship Opportunities.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Per-role dashboards — instructors and admins now land on a tailored view",
    body: "/dashboard now branches four ways: trainees keep the existing learner view; instructors see their own courses, recent enrolments, and assessment attempts; admins / superadmins land on a platform-overview with action queues (credit apps, role-change requests, pending pathway enrolments) plus live counters and the latest audit-log entries; employers continue to get the HR portal view shipped earlier. Superadmins also get an extra system-health row (AI calls in the last 7 days) and a quick-links panel for settings, LTI, and course filters.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Employer dashboard tailored to HR — postings, applicants, profile",
    body: "When an Employer HR signs in, /dashboard now lands on a portal-shaped overview instead of the learner view. Hero greets them by name + company with stats for active postings, applicants, new this week, and a profile-completeness percentage. A nudge card prompts them to finish the profile if it's sparse, four quick-action tiles cover post / browse / edit / apply, and the lower half lists the latest five applicants and the latest five of their own postings inline. The learner dashboard is unchanged for trainees / instructors / admins.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Employer self-signup via invite link + AI-filled company profile",
    body: "Admins can now invite an industry partner from /admin/employer-invites — paste an email, optionally a company name and website, and we generate a one-time link with a configurable expiry. The recipient clicks through, sets a name + password, and lands on /employer with the Employer HR role auto-assigned. The new /employer/profile page lets them paste their website and one-click 'Auto-fill' — the AI fetches the homepage, extracts industry / HQ / size / founding year / a short description, and pulls the favicon as a starter logo. Existing values aren't overwritten, so re-running just fills in blanks.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Test data: dummy employer + trainee + posting + application",
    body: "Run scripts/seed-test-employer-flow.ts to drop in a ready-to-test pair: an Employer HR (test.employer@biohubnet.test / test1234) at Acme Biotherapeutics with one active internship posting, and a Trainee (test.trainee@biohubnet.test / test1234) who has already submitted the talent application. Idempotent — re-running won't duplicate. Pass --cleanup to delete the test rows when you're done. Three ways to verify the flow: sign in as the employer, view-as Employer HR from the superadmin avatar menu, or sign in as the trainee.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Catalog admin tools — quick-edit, bulk filter assignment, and DB-driven option lists",
    body: "Three connected admin upgrades on the course catalog. (1) Each card now has a pencil for admins — opens a small dialog to set topic / delivery / provider / Special-program in one place; saves via PATCH and stays on page. (2) Each card also has a checkbox; selecting one or more reveals a sticky toolbar at the bottom of the screen with 'Apply filters to N' — the dialog has a 'Don't change' option per field so you only touch what you mean to. (3) New /admin/course-filters page lets admins add, rename, hide, or delete the option lists themselves; the catalog filter rail reads from the DB now, so additions show up everywhere immediately. Existing courses keep their assigned values even when you hide an option from the picker.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Employer HR role exposed in admin role-pickers + view-as menu",
    body: "Admins can now pick \"Employer HR\" in the Users page role dropdown (single-row select and the batch role action both list it), and the superadmin View-as menu can preview the platform as an employer. Set a user's role to Employer HR and they're routed to /employer on next login — full portal with Postings, Applicants, and the ATS scaffold.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Course catalog filters — by topic, delivery, special programs, and provider",
    body: "A filter rail now sits next to the catalog. Pick from nine topics (Sector/Tech, Career Insights, Regulatory Affairs, Industry Fundamentals, Quality, Biomanufacturing USP/DSP, etc.), four delivery types (Asynchronous, Online Synchronous, In-Person, Blended), the Special Programs (Instructor-led, limited seats) flag, and any of nine providers (Talent Accelerator, BioTalent Canada, CASTL, Seneca, CRAFT, Agilis Health, U of T, INSPIRE, CANTRAIN). Filters are URL-driven so they survive a refresh and are shareable.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Sidebar groups now sit in lettered boxes",
    body: "ENGAGE and EXPERIENCE (and Administration for admins) are wrapped in bordered boxes with the group title sitting at the top opening — the fieldset / legend pattern. Visually clearer at a glance which feature lives in which track.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "New 'Employer HR' user type — portal scaffold for industry partners",
    body: "Added an Employer HR role for industry partners who post internships and review applicants. They land in a dedicated /employer portal with overview tiles, their own postings list, and a read-only roster of talent applications (with one-click links to resume, 1-min video, and email). A per-account toggle (allowPlatformContent, default off) decides whether they can also browse Engage / Experience content. The full ATS workflow — Save / Shortlist / Interview status, candidate notes, side-by-side comparison, Calendly-style interview booking — is the next iteration.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Pathway cards: full-width horizontal layout, more breathing room",
    body: "Learning Pathways now lists each pathway and event registration in a single full-width column rather than a 3-up grid. Each card uses a horizontal layout — the gradient hero panel sits on the left, with title, eyebrow, three lines of description, course count, learner count, and a 'Pathway certificate' chip on the right. ~20% more vertical space per card so the description actually breathes.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Hi-Tech theme is now full TRON",
    body: "Switched the Hi-Tech palette to TRON's signature electric-cyan on inky black. Surfaces glow at the edges, headings sit in uppercase JetBrains Mono with wider tracking, corners are nearly square (0–6px), and the page background now carries a 64px grid pattern — the lightcycle arena floor look. Open the Theme picker to try it.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Internship parser now accepts dropped PDFs, DOCX, images, and text — all on Cloudflare's free AI",
    body: "Drag a PDF, Word document, screenshot, or text file straight onto the paste panel and the AI parses it. PDFs are extracted server-side via unpdf, DOCX via mammoth, and routed through Cloudflare Llama 3.3 70B; images go through Cloudflare's Llama 3.2 Vision model. Everything stays on the free Workers AI tier — no Gemini quota or Google billing involved. The browser-default behaviour of opening dropped files in a new tab is intercepted; the parser handles up to 20 MB.",
    kind: "improvement",
    visibleTo: STAFF,
    daysAgo: 0,
  },
  {
    title: "Internship Opportunities — a job board, AI-assisted",
    body: "EXPERIENCE → Internship Opportunities lists open internships and co-ops from BioHubNet's industry partners. Each posting shows the company, role, location, duration, hours, compensation, deadline, key skills, and full position details, with a one-click link to apply on the company site. Admins create new postings by pasting a job description from any source — email, PDF, web page, doc — and the AI parses it into structured fields they can review and save.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "EXPERIENCE track is open — apply through the Talent Application",
    body: "The new EXPERIENCE section in the sidebar opens with the Talent Application — a structured intake for students and postdocs applying to BioHubNet's industry-placement track. It collects your bio, citizenship and locations, French proficiency, education timeline, supervisor letter (PDF), 650-character pitch, one-minute STAR video, resume (PDF), and a supporting transcript. Resume / video upload directly to BioHubNet's encrypted storage; admins review every submission and export to CSV.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Changelog now auto-publishes — no more manual seeding",
    body: "When we ship an entry, it's now live on the changelog page automatically. Previously the entries lived in a script that had to be re-run against the database; now the /changelog page reads from a registry and idempotently upserts anything new. The audience filter (trainee / staff / admin) still applies per entry.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Hero banner brightened up",
    body: "The hero band on the dashboard, pathways, and catalog now paints a saturated marine mesh — deep cyan, mint-teal, deep blue — instead of inheriting the muted UI brand colours. The rest of the platform stays editorial-quiet; the hero gets to shout.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Sidebar reorganised into ENGAGE and EXPERIENCE",
    body: "Course Catalog, Learning Pathways (renamed from Pathways), My Courses, Gradebook, Certificates, and My Credits now sit under an ENGAGE section. EXPERIENCE opens the industry-placement track via Talent Application.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Palette shifted toward dark blue-teal",
    body: "The brand scale now reads as a refined marine slate-navy — same desaturated weight as before, just hue-shifted toward teal so cards and CTAs feel more editorial than corporate. Hi-Tech keeps its neon character.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Quieter, more refined palette — desaturated slate replaces bright royal blue",
    body: "Daylight, Nightfall, and Scientific now read as editorial rather than consumer-tech. Background goes from cool bright blue to a warm putty / charcoal off-white; text shifts from cool navy to warm graphite; the brand scale is a desaturated steel-slate (about 60% of the previous saturation). Hi-Tech keeps its neon character. CTAs still pass AAA contrast with white text — they just don't shout anymore.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Theme list trimmed to the four that earn their keep",
    body: "Aurora, Modern, Pink, Lab, and Lab Mouse are gone. The picker now shows Daylight, Nightfall, Scientific, and Hi-Tech — each one a distinct design language (typography + surface + radii), not just a colour swap. If you were on a retired theme, you've been bumped back to your OS preference automatically.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Bolder, more organic interface — full-bleed heroes, drifting blobs",
    body: "The dashboard, pathways, and course catalog now open with a bold full-bleed hero band: mesh gradient backgrounds, decorative blobs that drift gently behind the headline, asymmetric organic-cornered cards, and a curved organic edge into the content below. The hero greets you by name in gradient type and shows your stats in tiles with hand-shaped corners. Less generic, more intentional.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Course catalog: AI-generated thumbnails for every course",
    body: "Run scripts/auto-thumbnail-courses.ts to fill in cover art for the entire catalog. Each course gets a one-word focal subject (the strongest word from its title or category) rendered as an editorial brand-blue illustration via Cloudflare SDXL, uploaded to R2, and saved on the Course row. Idempotent — re-running only fills in what's still missing, or pass --force to regenerate.",
    kind: "feature",
    visibleTo: STAFF,
    daysAgo: 0,
  },
  {
    title: "Submissions table fits the screen + URL fields stop fighting you",
    body: "The /admin/forms/[slug] table is now compact (text-xs, tight padding, truncated cells with hover tooltips for the full value) and breaks out of the dashboard's max-width on large screens so it has room. URL fields on registration forms now accept anything you paste — no more 'please match the format' error if you skip the http:// scheme.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Themes are now full design languages — typography, shadows, and silhouette",
    body: "Each theme now defines its own typography (Modern uses Inter, Scientific is set in Charter serif, Hi-Tech in JetBrains Mono with uppercase headings, Pink and Lab Mouse in rounded Quicksand) plus its own surface treatment — Modern is shadowless with hard 1px borders, Hi-Tech glows neon, Pink and Lab Mouse have soft pink halos, Scientific reads as etched paper. Switching themes now changes how the platform feels, not just what colour it is.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Six new theme designs to choose from",
    body: "The Theme picker now ships nine looks: Modern (minimalist red), Scientific (cool sky-blue), Hi-Tech (neon cyan on near-black), Pink (rose), Lab (sterile white + emerald), and Lab Mouse (warm cream + mouse pink), in addition to Daylight, Nightfall, and Aurora. Each theme reshapes corner radii too, so the platform's silhouette changes with the palette.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Event registration forms now live on Pathways",
    body: "The OBIO Entrepreneurship Bootcamp registration is the first one — you'll see it as a teal card on the Pathways page. Submit once and we keep your last response on file. Admins can edit the form fields in place (add, remove, reorder) and export every submission as a CSV.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Pathway editor: clearer Edit button, draggable + resizable window",
    body: "The Edit button on a pathway hero is now a solid white pill so it actually stands out against the gradient. Open the editor and you can drag the title bar to move the dialog or grab the bottom-right corner to resize it. The course picker on the right grows with the dialog, so you can see more options at a glance.",
    kind: "improvement",
    visibleTo: STAFF,
    daysAgo: 0,
  },
  {
    title: "Dark-mode contrast pass — readable text, no over-bright cards",
    body: "Rebalanced the dark brand palette so saturated CTAs keep their contrast with white text while subtle blue tints work as active backgrounds. Tailwind's hard-coded state tints (rose-50, amber-100, emerald-50, etc.) are now muted in dark mode so alert banners and cert ribbons stop blasting. Body, muted, and subtle text all clear AA on the dark background.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Translations are near-instant on repeat visits",
    body: "Page translation now caches every result in two layers: a Postgres-backed cache shared across users (one translation per string per language, ever) and a per-tab sessionStorage cache for the current visit. Re-visiting any page in your chosen language is a no-network operation; first-time strings still go through Cloudflare m2m100.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Translate menu: real errors, no more retry loops",
    body: "If translation fails, the menu now shows the actual server response inline instead of a generic alert that wouldn't dismiss. The saved language is also cleared on failure so the next page load doesn't immediately re-trigger the same error.",
    kind: "fix",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Cookie banner no longer flashes on every refresh",
    body: "Decided cookie consent? You shouldn't see the banner again. We were rendering it briefly during the SSR pass before the client picked up your saved preference — that's the half-second flash. The banner now waits for the client to confirm a decision before deciding whether to show.",
    kind: "fix",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "View-as menu refresh",
    body: "Superadmins viewing as another role: the menu trigger and active-role highlight now use brand blue (was amber). The menu pops on a teal surface that's distinct from the rest of the app so it's hard to miss you're impersonating. Stop viewing-as · Restore superadmin moved to the top of the menu and only shows when you're actually impersonating someone.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Build commit SHA in the sidebar (staff)",
    body: "A small mono-font 7-char SHA chip is now docked above the user block in the sidebar. Click-and-drag to copy when filing bug reports — tells us which build you were running.",
    kind: "feature",
    visibleTo: STAFF,
    daysAgo: 0,
  },
  {
    title: "Marketing splash retired — / goes straight where you need to be",
    body: "The 267-line marketing landing page on / is gone. Signed in? You go to /dashboard. Signed out? You go to /login. One less click in a typical session.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Change log is here",
    body: "Track what's new in the platform from one place. Trainees see it as What's new; staff see full release notes. Every entry's audience is configurable per-role.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 0,
  },
  {
    title: "Multi-select batch actions on the Users page",
    body: "Admins can now select multiple users at once and run a single action across all of them: activate / deactivate, change role, adjust BHN credits, or add to a group. Every batch is logged in the audit trail.",
    kind: "feature",
    visibleTo: ADMINS,
    daysAgo: 0,
  },
  {
    title: "Trainee role renamed",
    body: "The default learner role is now Trainee. All existing accounts with the old name were migrated automatically. No action needed.",
    kind: "improvement",
    visibleTo: STAFF,
    daysAgo: 0,
  },
  {
    title: "Ten elegant interface themes",
    body: "Pick from Daylight, Slate, Ocean, Forest, Sunset, Rose, Lavender, Twilight, Midnight, or Espresso. Your choice persists across sessions and respects your OS preference on first visit. Find the picker at the bottom of the sidebar.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 1,
  },
  {
    title: "Remember me on sign-in",
    body: "A new checkbox on the login page keeps you signed in for 30 days on this device. Uncheck it on shared computers and your session ends after a day.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 1,
  },
  {
    title: "BioHubNet newsletter opt-in at registration",
    body: "New accounts are invited to subscribe to the BioHubNet newsletter at sign-up. Unsubscribing happens via the link at the bottom of any newsletter email.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 1,
  },
  {
    title: "New brand mark and logo",
    body: "A graduation cap with a tassel on a brand-blue tile — appears across the app, the login screen, and the favicon.",
    kind: "improvement",
    visibleTo: ALL,
    daysAgo: 2,
  },
  {
    title: "Instructor role",
    body: "A new role between Trainee and Admin that can author courses, upload SCORM packages, and manage modules and assessments — but cannot manage users, settings, or audit logs.",
    kind: "feature",
    visibleTo: STAFF,
    daysAgo: 2,
  },
  {
    title: "Edit course information after creation",
    body: "Course detail pages now have an Edit button for instructors and admins. Update title, description, passing score, credit cost, duration, and more without leaving the page.",
    kind: "feature",
    visibleTo: STAFF,
    daysAgo: 3,
  },
  {
    title: "Training Pathways",
    body: "Bundle courses into a curated learning journey. When learners complete every required course, the platform automatically issues a pathway-level certificate. Find pathways in the sidebar.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 3,
  },
  {
    title: "Public marketing home page",
    body: "Visit the root URL while signed out to see the new landing page with live platform stats, feature highlights, and a pathway-focused callout.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 4,
  },
  {
    title: "5,000 BHN credits to start",
    body: "Every new account is provisioned with 5,000 BHN credits, enough to enroll in the most popular courses right away.",
    kind: "feature",
    visibleTo: ALL,
    daysAgo: 4,
  },
  {
    title: "SCORM packages now stored in object storage",
    body: "SCORM zip uploads are extracted in /tmp and streamed to Cloudflare R2 with zero egress cost. Existing courses keep working, with content served through a same-origin proxy so the SCORM runtime still talks to the LMS API.",
    kind: "improvement",
    visibleTo: STAFF,
    daysAgo: 5,
  },
  {
    title: "Production database upgraded to Postgres",
    body: "Migrated from local SQLite to managed Neon Postgres for reliability, concurrency, and proper backups. Session pooling configured for serverless function compatibility.",
    kind: "improvement",
    visibleTo: ADMINS,
    daysAgo: 5,
  },
  {
    title: "Welcome to BHN Training",
    body: "The first public release of the BHN Training Platform — courses, modules, assessments, certification, BHN credits, and a foundation to grow on.",
    kind: "note",
    visibleTo: ALL,
    daysAgo: 6,
  },
];
